// Code generated by mwsapigen, DO NOT EDIT.

package mkafka

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	ctxvalues "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/mkafka/client"
	resourcesdk "go.mws.cloud/go-sdk/service/mkafka/sdk"
	"go.mws.cloud/terraform-provider-mws/internal/cmp"
	"go.mws.cloud/terraform-provider-mws/internal/diag"
	provider "go.mws.cloud/terraform-provider-mws/internal/provider/public"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mkafka/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/mkafka/model"
)

var (
	_ datasource.DataSource = &KafkaConnectorDataSource{}
)

type KafkaConnectorDataSource struct {
	sdk    *resourcesdk.KafkaConnector
	config *provider.Config
}

func NewKafkaConnectorDataSource() datasource.DataSource {
	return &KafkaConnectorDataSource{}
}

func (m *KafkaConnectorDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	tflog.Info(ctx, "KafkaConnectorDataSource.Metadata")
	resp.TypeName = req.ProviderTypeName + "_mkafka_kafka_connector"
}

func (m *KafkaConnectorDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	tflog.Info(ctx, "KafkaConnectorDataSource.Schema")
	resp.Schema = new(tfmodel.KafkaConnector).GetSchema()
	resp.Schema.Attributes["cluster"] = schema.StringAttribute{
		MarkdownDescription: `Название или идентификатор кластера.`,
		Required:            true,
	}
	resp.Schema.Attributes["connector"] = schema.StringAttribute{
		MarkdownDescription: `Имя коннектора.`,
		Required:            true,
	}
	resp.Schema.Attributes["project"] = schema.StringAttribute{
		MarkdownDescription: `Путь к проекту.`,
		Optional:            true,
		Computed:            true,
	}
}

func (m *KafkaConnectorDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	var err error
	tflog.Info(ctx, "KafkaConnectorDataSource.Configure")
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*provider.Data)
	if !ok || providerData == nil {
		resp.Diagnostics.AddError("Internal Provider Error", "Unexpected type of req.ProviderData")
		return
	}

	m.config = providerData.Config

	m.sdk, err = resourcesdk.NewKafkaConnector(ctx, providerData.SDK)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create SDK client for KafkaConnector",
			diag.FormatError(err),
		)
		return
	}
}

func (m *KafkaConnectorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	tflog.Info(ctx, "KafkaConnectorDataSource.Read")

	var config tfmodel.KafkaConnectorModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(config.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	config.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	apiRes, err := m.sdk.GetKafkaConnector(
		ctx,
		client.GetKafkaConnectorRequest{
			Project:   config.ProjectParam.ValueString(),
			Cluster:   config.ClusterParam.ValueString(),
			Connector: config.ConnectorParam.ValueString(),
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Get KafkaConnector",
			diag.FormatError(err),
		)
		return
	}

	tfRes, diags := conv.KafkaConnectorAPIOptionalResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "KafkaConnectorDataSource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	config.KafkaConnector = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
