// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	apimodel "go.mws.cloud/go-sdk/service/mk8s/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/model"
)

func ClusterVersionControlSpecAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.ClusterVersionControlSpecOptionalResponse) (*tfmodel.ClusterVersionControlSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ClusterVersionControlSpec

	t.ReleaseChannel = types.StringValue(am.ReleaseChannel)

	if val, ok := am.Version.Get(); ok {
		t.Version = types.StringValue(val)
	} else {
		t.Version = types.StringNull()
	}

	if val, ok := am.MaintenanceWindow.Get(); ok {
		maintenanceWindowTmp, d := commonconv.MaintenanceWindowAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		maintenanceWindowTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfcommon.MaintenanceWindow).GetSchema().Attributes),
			*maintenanceWindowTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.MaintenanceWindow = maintenanceWindowTfObject
	} else {
		t.MaintenanceWindow = types.ObjectNull(tfconv.GetAttributesTypes(new(tfcommon.MaintenanceWindow).GetSchema().Attributes))
	}

	return &t, diags
}

func ClusterVersionControlSpecTFToAPIRequestModel(ctx context.Context, tm *tfmodel.ClusterVersionControlSpec) (*apimodel.ClusterVersionControlSpecRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.ClusterVersionControlSpecRequest

	if !tm.ReleaseChannel.IsNull() && !tm.ReleaseChannel.IsUnknown() {
		am.ReleaseChannel = tm.ReleaseChannel.ValueString()
	}

	if !tm.Version.IsNull() && !tm.Version.IsUnknown() {
		am.Version = tm.Version.ValueStringPointer()
	}

	if !tm.MaintenanceWindow.IsNull() && !tm.MaintenanceWindow.IsUnknown() {
		maintenanceWindowTfModel := tfcommon.MaintenanceWindow{}
		maintenanceWindowDiag := tm.MaintenanceWindow.As(ctx, &maintenanceWindowTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, maintenanceWindowDiag...)
		if diags.HasError() {
			return nil, diags
		}

		maintenanceWindowTmp, maintenanceWindowDiag := commonconv.MaintenanceWindowTFToAPIRequestModel(ctx, &maintenanceWindowTfModel)
		diags = append(diags, maintenanceWindowDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.MaintenanceWindow = maintenanceWindowTmp
	}

	return &am, diags
}
