// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	"go.mws.cloud/go-sdk/service/mk8s/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/model"
)

func ClusterPublicEndpointSpecOrRefAPIOptionalResponseToTFModel(ctx context.Context, am *model.ClusterPublicEndpointSpecOrRefOptionalResponse) (*tfmodel.ClusterPublicEndpointSpecOrRef, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ClusterPublicEndpointSpecOrRef

	if val, ok := am.Ref.Get(); ok {
		t.Ref = types.StringPointerValue(ptr.Get(val.Path()))
	} else {
		t.Ref = types.StringNull()
	}

	if val, ok := am.Spec.Get(); ok {
		specTmp, d := ClusterPublicEndpointSpecAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		specTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClusterPublicEndpointSpec).GetSchema().Attributes),
			*specTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Spec = specTfObject
	} else {
		t.Spec = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClusterPublicEndpointSpec).GetSchema().Attributes))
	}

	return &t, diags
}

func ClusterPublicEndpointSpecOrRefTFToAPIRequestModel(ctx context.Context, plan *tfmodel.ClusterPublicEndpointSpecOrRef) (*model.ClusterPublicEndpointSpecOrRefRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.ClusterPublicEndpointSpecOrRefRequest

	if !plan.Ref.IsNull() && !plan.Ref.IsUnknown() {
		refRef, err := vpc.ParseExternalAddressRef(ctx, plan.Ref.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Ref = &refRef
	}

	if !plan.Spec.IsNull() && !plan.Spec.IsUnknown() {
		specPlan := tfmodel.ClusterPublicEndpointSpec{}
		specPlanDiag := plan.Spec.As(ctx, &specPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, specPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		specTmp, specDiag := ClusterPublicEndpointSpecTFToAPIRequestModel(ctx, &specPlan)
		diags = append(diags, specDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec = specTmp
	}

	return &am, diags
}

func ClusterPublicEndpointSpecOrRefTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.ClusterPublicEndpointSpecOrRef) (*model.UpdateClusterPublicEndpointSpecOrRefRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.ClusterPublicEndpointSpecOrRef{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateClusterPublicEndpointSpecOrRefRequest

	if !plan.Ref.Equal(state.Ref) {
		if !plan.Ref.IsNull() && !plan.Ref.IsUnknown() {
			refRef, err := vpc.ParseExternalAddressRef(ctx, plan.Ref.ValueString())
			if err != nil {
				diags.AddError("reference parsing", err.Error())
				return nil, diags
			}
			am.Ref.SetTo(refRef)
		} else if plan.Ref.IsNull() {
			am.Ref.SetToNull()
		}
	}

	if !plan.Spec.Equal(state.Spec) {
		if !plan.Spec.IsNull() && !plan.Spec.IsUnknown() {
			specPlan := tfmodel.ClusterPublicEndpointSpec{}
			specPlanDiag := plan.Spec.As(ctx, &specPlan, basetypes.ObjectAsOptions{})
			diags = append(diags, specPlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			specState := tfmodel.ClusterPublicEndpointSpec{}
			if !state.Spec.IsNull() && !state.Spec.IsUnknown() {
				specStateDiag := state.Spec.As(ctx, &specState, basetypes.ObjectAsOptions{})
				diags = append(diags, specStateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			specTmp, specDiag := ClusterPublicEndpointSpecTFToAPIUpdateRequestModel(ctx, &specPlan, &specState)
			diags = append(diags, specDiag...)
			if diags.HasError() {
				return nil, diags
			}
			am.Spec.SetTo(*specTmp)
		} else if plan.Spec.IsNull() {
			am.Spec.SetToNull()
		}
	}

	return &am, diags
}
