// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	"go.mws.cloud/go-sdk/service/mk8s/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/model"
)

func NodeGroupSpecNetworkAPIOptionalResponseToTFModel(ctx context.Context, am *model.NodeGroupSpecNetworkOptionalResponse) (*tfmodel.NodeGroupSpecNetwork, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NodeGroupSpecNetwork

	if val, ok := am.PrimaryInterface.Get(); ok {
		primaryInterfaceTmp, d := NodeGroupSpecNetworkPrimaryInterfaceAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		primaryInterfaceTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecNetworkPrimaryInterface).GetSchema().Attributes),
			*primaryInterfaceTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.PrimaryInterface = primaryInterfaceTfObject
	} else {
		t.PrimaryInterface = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecNetworkPrimaryInterface).GetSchema().Attributes))
	}

	return &t, diags
}

func NodeGroupSpecNetworkTFToAPIRequestModel(ctx context.Context, plan *tfmodel.NodeGroupSpecNetwork) (*model.NodeGroupSpecNetworkRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.NodeGroupSpecNetworkRequest

	if !plan.PrimaryInterface.IsNull() && !plan.PrimaryInterface.IsUnknown() {
		primaryInterfacePlan := tfmodel.NodeGroupSpecNetworkPrimaryInterface{}
		primaryInterfacePlanDiag := plan.PrimaryInterface.As(ctx, &primaryInterfacePlan, basetypes.ObjectAsOptions{})
		diags = append(diags, primaryInterfacePlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		primaryInterfaceTmp, primaryInterfaceDiag := NodeGroupSpecNetworkPrimaryInterfaceTFToAPIRequestModel(ctx, &primaryInterfacePlan)
		diags = append(diags, primaryInterfaceDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.PrimaryInterface = primaryInterfaceTmp
	}

	return &am, diags
}

func NodeGroupSpecNetworkTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.NodeGroupSpecNetwork) (*model.UpdateNodeGroupSpecNetworkRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.NodeGroupSpecNetwork{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateNodeGroupSpecNetworkRequest

	if !plan.PrimaryInterface.Equal(state.PrimaryInterface) {
		if !plan.PrimaryInterface.IsNull() && !plan.PrimaryInterface.IsUnknown() {
			primaryInterfacePlan := tfmodel.NodeGroupSpecNetworkPrimaryInterface{}
			primaryInterfacePlanDiag := plan.PrimaryInterface.As(ctx, &primaryInterfacePlan, basetypes.ObjectAsOptions{})
			diags = append(diags, primaryInterfacePlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			primaryInterfaceState := tfmodel.NodeGroupSpecNetworkPrimaryInterface{}
			if !state.PrimaryInterface.IsNull() && !state.PrimaryInterface.IsUnknown() {
				primaryInterfaceStateDiag := state.PrimaryInterface.As(ctx, &primaryInterfaceState, basetypes.ObjectAsOptions{})
				diags = append(diags, primaryInterfaceStateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			primaryInterfaceTmp, primaryInterfaceDiag := NodeGroupSpecNetworkPrimaryInterfaceTFToAPIUpdateRequestModel(ctx, &primaryInterfacePlan, &primaryInterfaceState)
			diags = append(diags, primaryInterfaceDiag...)
			if diags.HasError() {
				return nil, diags
			}
			am.PrimaryInterface.SetTo(*primaryInterfaceTmp)
		} else if plan.PrimaryInterface.IsNull() {
			am.PrimaryInterface.SetToNull()
		}
	}

	return &am, diags
}

func NodeGroupSpecNetworkPrimaryInterfaceAPIOptionalResponseToTFModel(ctx context.Context, am *model.NodeGroupSpecNetworkPrimaryInterfaceOptionalResponse) (*tfmodel.NodeGroupSpecNetworkPrimaryInterface, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NodeGroupSpecNetworkPrimaryInterface

	if val, ok := am.ExternalIpv4.Get(); ok {
		externalIpv4Tmp, d := NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4APIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		externalIpv4TfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4).GetSchema().Attributes),
			*externalIpv4Tmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.ExternalIpv4 = externalIpv4TfObject
	} else {
		t.ExternalIpv4 = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4).GetSchema().Attributes))
	}

	return &t, diags
}

func NodeGroupSpecNetworkPrimaryInterfaceTFToAPIRequestModel(ctx context.Context, plan *tfmodel.NodeGroupSpecNetworkPrimaryInterface) (*model.NodeGroupSpecNetworkPrimaryInterfaceRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.NodeGroupSpecNetworkPrimaryInterfaceRequest

	if !plan.ExternalIpv4.IsNull() && !plan.ExternalIpv4.IsUnknown() {
		externalIpv4Plan := tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4{}
		externalIpv4PlanDiag := plan.ExternalIpv4.As(ctx, &externalIpv4Plan, basetypes.ObjectAsOptions{})
		diags = append(diags, externalIpv4PlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		externalIpv4Tmp, externalIpv4Diag := NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4TFToAPIRequestModel(ctx, &externalIpv4Plan)
		diags = append(diags, externalIpv4Diag...)
		if diags.HasError() {
			return nil, diags
		}
		am.ExternalIpv4 = externalIpv4Tmp
	}

	return &am, diags
}

func NodeGroupSpecNetworkPrimaryInterfaceTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.NodeGroupSpecNetworkPrimaryInterface) (*model.UpdateNodeGroupSpecNetworkPrimaryInterfaceRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.NodeGroupSpecNetworkPrimaryInterface{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateNodeGroupSpecNetworkPrimaryInterfaceRequest

	if !plan.ExternalIpv4.Equal(state.ExternalIpv4) {
		if !plan.ExternalIpv4.IsNull() && !plan.ExternalIpv4.IsUnknown() {
			externalIpv4Plan := tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4{}
			externalIpv4PlanDiag := plan.ExternalIpv4.As(ctx, &externalIpv4Plan, basetypes.ObjectAsOptions{})
			diags = append(diags, externalIpv4PlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			externalIpv4State := tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4{}
			if !state.ExternalIpv4.IsNull() && !state.ExternalIpv4.IsUnknown() {
				externalIpv4StateDiag := state.ExternalIpv4.As(ctx, &externalIpv4State, basetypes.ObjectAsOptions{})
				diags = append(diags, externalIpv4StateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			externalIpv4Tmp, externalIpv4Diag := NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4TFToAPIUpdateRequestModel(ctx, &externalIpv4Plan, &externalIpv4State)
			diags = append(diags, externalIpv4Diag...)
			if diags.HasError() {
				return nil, diags
			}
			am.ExternalIpv4.SetTo(*externalIpv4Tmp)
		} else if plan.ExternalIpv4.IsNull() {
			am.ExternalIpv4.SetToNull()
		}
	}

	return &am, diags
}

func NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4APIOptionalResponseToTFModel(ctx context.Context, am *model.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4OptionalResponse) (*tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4

	if val, ok := am.Enabled.Get(); ok {
		t.Enabled = types.BoolValue(val)
	} else {
		t.Enabled = types.BoolNull()
	}

	return &t, diags
}

func NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4TFToAPIRequestModel(ctx context.Context, plan *tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4) (*model.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4Request, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4Request

	if !plan.Enabled.IsNull() && !plan.Enabled.IsUnknown() {
		am.Enabled = plan.Enabled.ValueBoolPointer()
	}

	return &am, diags
}

func NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4TFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4) (*model.UpdateNodeGroupSpecNetworkPrimaryInterfaceExternalIpv4Request, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.NodeGroupSpecNetworkPrimaryInterfaceExternalIpv4{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateNodeGroupSpecNetworkPrimaryInterfaceExternalIpv4Request

	if !plan.Enabled.Equal(state.Enabled) {
		if !plan.Enabled.IsNull() && !plan.Enabled.IsUnknown() {
			am.Enabled.SetTo(plan.Enabled.ValueBool())
		}
	}

	return &am, diags
}
