// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	"go.mws.cloud/go-sdk/service/mk8s/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/model"
)

func NodeGroupVersionControlSpecAPIOptionalResponseToTFModel(ctx context.Context, am *model.NodeGroupVersionControlSpecOptionalResponse) (*tfmodel.NodeGroupVersionControlSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NodeGroupVersionControlSpec

	if val, ok := am.Version.Get(); ok {
		t.Version = types.StringValue(val)
	} else {
		t.Version = types.StringNull()
	}

	if val, ok := am.AutoUpdate.Get(); ok {
		t.AutoUpdate = types.BoolValue(val)
	} else {
		t.AutoUpdate = types.BoolNull()
	}

	if val, ok := am.MaintenanceWindow.Get(); ok {
		maintenanceWindowTmp, d := commonconv.MaintenanceWindowAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		maintenanceWindowTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfcommon.MaintenanceWindow).GetSchema().Attributes),
			*maintenanceWindowTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.MaintenanceWindow = maintenanceWindowTfObject
	} else {
		t.MaintenanceWindow = types.ObjectNull(tfconv.GetAttributesTypes(new(tfcommon.MaintenanceWindow).GetSchema().Attributes))
	}

	return &t, diags
}

func NodeGroupVersionControlSpecTFToAPIRequestModel(ctx context.Context, plan *tfmodel.NodeGroupVersionControlSpec) (*model.NodeGroupVersionControlSpecRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.NodeGroupVersionControlSpecRequest

	if !plan.Version.IsNull() && !plan.Version.IsUnknown() {
		am.Version = plan.Version.ValueStringPointer()
	}

	if !plan.AutoUpdate.IsNull() && !plan.AutoUpdate.IsUnknown() {
		am.AutoUpdate = plan.AutoUpdate.ValueBoolPointer()
	}

	if !plan.MaintenanceWindow.IsNull() && !plan.MaintenanceWindow.IsUnknown() {
		maintenanceWindowPlan := tfcommon.MaintenanceWindow{}
		maintenanceWindowPlanDiag := plan.MaintenanceWindow.As(ctx, &maintenanceWindowPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, maintenanceWindowPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		maintenanceWindowTmp, maintenanceWindowDiag := commonconv.MaintenanceWindowTFToAPIRequestModel(ctx, &maintenanceWindowPlan)
		diags = append(diags, maintenanceWindowDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.MaintenanceWindow = maintenanceWindowTmp
	}

	return &am, diags
}

func NodeGroupVersionControlSpecTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.NodeGroupVersionControlSpec) (*model.UpdateNodeGroupVersionControlSpecRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.NodeGroupVersionControlSpec{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateNodeGroupVersionControlSpecRequest

	if !plan.Version.Equal(state.Version) {
		if !plan.Version.IsNull() && !plan.Version.IsUnknown() {
			am.Version.SetTo(plan.Version.ValueString())
		}
	}

	if !plan.AutoUpdate.Equal(state.AutoUpdate) {
		if !plan.AutoUpdate.IsNull() && !plan.AutoUpdate.IsUnknown() {
			am.AutoUpdate.SetTo(plan.AutoUpdate.ValueBool())
		}
	}

	if !plan.MaintenanceWindow.Equal(state.MaintenanceWindow) {
		if !plan.MaintenanceWindow.IsNull() && !plan.MaintenanceWindow.IsUnknown() {
			maintenanceWindowPlan := tfcommon.MaintenanceWindow{}
			maintenanceWindowPlanDiag := plan.MaintenanceWindow.As(ctx, &maintenanceWindowPlan, basetypes.ObjectAsOptions{})
			diags = append(diags, maintenanceWindowPlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			maintenanceWindowState := tfcommon.MaintenanceWindow{}
			if !state.MaintenanceWindow.IsNull() && !state.MaintenanceWindow.IsUnknown() {
				maintenanceWindowStateDiag := state.MaintenanceWindow.As(ctx, &maintenanceWindowState, basetypes.ObjectAsOptions{})
				diags = append(diags, maintenanceWindowStateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			maintenanceWindowTmp, maintenanceWindowDiag := commonconv.MaintenanceWindowTFToAPIUpdateRequestModel(ctx, &maintenanceWindowPlan, &maintenanceWindowState)
			diags = append(diags, maintenanceWindowDiag...)
			if diags.HasError() {
				return nil, diags
			}
			am.MaintenanceWindow.SetTo(*maintenanceWindowTmp)
		} else if plan.MaintenanceWindow.IsNull() {
			am.MaintenanceWindow.SetToNull()
		}
	}

	return &am, diags
}
