// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ClusterModel struct {
	ProjectParam     types.String   `tfsdk:"project"`
	ClusterNameParam types.String   `tfsdk:"cluster_name"`
	Timeouts         timeouts.Value `tfsdk:"timeouts"`
	ID               types.String   `tfsdk:"id"`
	Cluster
}
