// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

type ClusterVersionControlStatus struct {
	ReleaseChannel    types.String `tfsdk:"release_channel"`
	Version           types.String `tfsdk:"version"`
	MaintenanceWindow types.Object `tfsdk:"maintenance_window"`
}

func (s *ClusterVersionControlStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"release_channel": schema.StringAttribute{
				MarkdownDescription: `Cluster обновляется всегда до default версии, поэтому необходимо выбрать релизный канал и настроить окно обслуживания`,
				Computed:            true,
			},
			"version": schema.StringAttribute{
				MarkdownDescription: `Текущая версия Cluster`,
				Computed:            true,
			},
			"maintenance_window": schema.SingleNestedAttribute{
				Attributes: new(tfcommon.MaintenanceWindow2).GetSchema().Attributes,
				Computed:   true,
			},
		},
	}
}
