// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ClusterPrimaryEndpointSpec struct {
	IpAddress types.String `tfsdk:"ip_address"`
	Subnet    types.String `tfsdk:"subnet"`
}

func (s *ClusterPrimaryEndpointSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описание subnet пользователя, из которого будет выделен ip-адрес`,
		Attributes: map[string]schema.Attribute{
			"ip_address": schema.StringAttribute{
				MarkdownDescription: `Желаемый IP адрес. Если не указан, то будет выделен из пула адресов подсети.`,
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"subnet": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
		},
	}
}
