// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NodeGroupSpecRolloutStrategy struct {
	MaxSurge       types.Int64 `tfsdk:"max_surge"`
	MaxUnavailable types.Int64 `tfsdk:"max_unavailable"`
}

func (s *NodeGroupSpecRolloutStrategy) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля RolloutStrategy анонимного типа структуры NodeGroupSpec`,
		Attributes: map[string]schema.Attribute{
			"max_surge": schema.Int64Attribute{
				Optional: true,
			},
			"max_unavailable": schema.Int64Attribute{
				Optional: true,
			},
		},
	}
}

type NodeGroupSpecScale struct {
	Fixed       types.Int64  `tfsdk:"fixed"`
	Autoscaling types.Object `tfsdk:"autoscaling"`
}

func (s *NodeGroupSpecScale) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля Scale анонимного типа структуры NodeGroupSpec`,
		Attributes: map[string]schema.Attribute{
			"fixed": schema.Int64Attribute{
				MarkdownDescription: `Количество узлов в node group`,
				Optional:            true,
			},
			"autoscaling": schema.SingleNestedAttribute{
				Attributes: new(NodeGroupSpecScaleAutoscaling).GetSchema().Attributes,
				Optional:   true,
			},
		},
	}
}

type NodeGroupSpecScaleAutoscaling struct {
	Min types.Int64 `tfsdk:"min"`
	Max types.Int64 `tfsdk:"max"`
}

func (s *NodeGroupSpecScaleAutoscaling) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля Autoscaling анонимного типа структуры NodeGroupSpecScale`,
		Attributes: map[string]schema.Attribute{
			"min": schema.Int64Attribute{
				MarkdownDescription: `Минимально количество нод в Node group.`,
				Required:            true,
			},
			"max": schema.Int64Attribute{
				MarkdownDescription: `Максимальное количество нод в Node group.`,
				Required:            true,
			},
		},
	}
}

type NodeGroupSpecServiceAccount struct {
	Ref types.String `tfsdk:"ref"`
}

func (s *NodeGroupSpecServiceAccount) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля ServiceAccount анонимного типа структуры NodeGroupSpec`,
		Attributes: map[string]schema.Attribute{
			"ref": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type NodeGroupSpecSubnet struct {
	Ref types.String `tfsdk:"ref"`
}

func (s *NodeGroupSpecSubnet) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля Subnet анонимного типа структуры NodeGroupSpec`,
		Attributes: map[string]schema.Attribute{
			"ref": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type NodeGroupSpecVmType struct {
	Ref types.String `tfsdk:"ref"`
}

func (s *NodeGroupSpecVmType) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля VmType анонимного типа структуры NodeGroupSpec`,
		Attributes: map[string]schema.Attribute{
			"ref": schema.StringAttribute{
				Required: true,
			},
		},
	}
}
