// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"
	"time"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	apimodel "go.mws.cloud/go-sdk/service/iam/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/iam/model"
)

func HmacKeyAPIResponseToTFModel(ctx context.Context, am *apimodel.HmacKeyResponse) (*tfmodel.HmacKey, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.HmacKey

	if am.Kind != nil {
		t.Kind = types.StringPointerValue(am.Kind)
	} else {
		t.Kind = types.StringNull()
	}

	if am.Metadata != nil {
		metadataTmp, d := HmacKeyMetadataAPIResponseToTFModel(ctx, am.Metadata)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		metadataTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.HmacKeyMetadata).GetSchema().Attributes),
			*metadataTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Metadata = metadataTfObject
	} else {
		t.Metadata = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.HmacKeyMetadata).GetSchema().Attributes))
	}

	if am.Status != nil {
		statusTmp, d := HmacKeyResourceStatusAPIResponseToTFModel(ctx, am.Status)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		statusTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.HmacKeyResourceStatus).GetSchema().Attributes),
			*statusTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Status = statusTfObject
	} else {
		t.Status = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.HmacKeyResourceStatus).GetSchema().Attributes))
	}

	if am.Spec.ExpirationTime != nil {
		t.ExpirationTime = types.StringPointerValue(ptr.Get(am.Spec.ExpirationTime.Format(time.RFC3339)))
	} else {
		t.ExpirationTime = types.StringNull()
	}

	return &t, diags
}

func HmacKeyTFToAPIRequestModel(ctx context.Context, plan *tfmodel.HmacKey) (*apimodel.HmacKeyRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.HmacKeyRequest

	if !plan.Metadata.IsNull() && !plan.Metadata.IsUnknown() {
		metadataPlan := tfmodel.HmacKeyMetadata{}
		metadataPlanDiag := plan.Metadata.As(ctx, &metadataPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, metadataPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		metadataTmp, metadataDiag := HmacKeyMetadataTFToAPIRequestModel(ctx, &metadataPlan)
		diags = append(diags, metadataDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Metadata = metadataTmp
	}

	if !plan.ExpirationTime.IsNull() && !plan.ExpirationTime.IsUnknown() {
		tmpExpirationTime, err := time.Parse(time.RFC3339, plan.ExpirationTime.ValueString())
		if err != nil {
			diags.AddError("time string parsing", err.Error())
			return nil, diags
		}
		am.Spec.ExpirationTime = &tmpExpirationTime
	}

	return &am, diags
}

func HmacKeyTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.HmacKey) (*apimodel.UpdateHmacKeyRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.HmacKey{}
	}

	var diags tfdiag.Diagnostics
	var am apimodel.UpdateHmacKeyRequest

	if !plan.Metadata.Equal(state.Metadata) {
		if !plan.Metadata.IsNull() && !plan.Metadata.IsUnknown() {
			metadataPlan := tfmodel.HmacKeyMetadata{}
			metadataPlanDiag := plan.Metadata.As(ctx, &metadataPlan, basetypes.ObjectAsOptions{})
			diags = append(diags, metadataPlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			metadataState := tfmodel.HmacKeyMetadata{}
			if !state.Metadata.IsNull() && !state.Metadata.IsUnknown() {
				metadataStateDiag := state.Metadata.As(ctx, &metadataState, basetypes.ObjectAsOptions{})
				diags = append(diags, metadataStateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			metadataTmp, metadataDiag := HmacKeyMetadataTFToAPIUpdateRequestModel(ctx, &metadataPlan, &metadataState)
			diags = append(diags, metadataDiag...)
			if diags.HasError() {
				return nil, diags
			}
			am.Metadata.SetTo(*metadataTmp)
		} else if plan.Metadata.IsNull() {
			am.Metadata.SetToNull()
		}
	}

	if !plan.ExpirationTime.Equal(state.ExpirationTime) {
		if !plan.ExpirationTime.IsNull() && !plan.ExpirationTime.IsUnknown() {
			if !am.Spec.IsSet() {
				am.Spec.SetTo(apimodel.UpdateHmacKeySpecRequest{})
			}
			tmpExpirationTime, err := time.Parse(time.RFC3339, plan.ExpirationTime.ValueString())
			if err != nil {
				diags.AddError("time string parsing", err.Error())
				return nil, diags
			}
			am.Spec.Value.ExpirationTime.SetTo(tmpExpirationTime)
		}
	}

	return &am, diags
}

func HmacKeyMetadataAPIResponseToTFModel(ctx context.Context, am *apimodel.HmacKeyMetadataResponse) (*tfmodel.HmacKeyMetadata, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.HmacKeyMetadata

	if am.DisplayName != nil {
		t.DisplayName = types.StringPointerValue(am.DisplayName)
	} else {
		t.DisplayName = types.StringNull()
	}

	if am.CreateTime != nil {
		t.CreateTime = types.StringPointerValue(ptr.Get(am.CreateTime.Format(time.RFC3339)))
	} else {
		t.CreateTime = types.StringNull()
	}

	if am.DeleteTime != nil {
		t.DeleteTime = types.StringPointerValue(ptr.Get(am.DeleteTime.Format(time.RFC3339)))
	} else {
		t.DeleteTime = types.StringNull()
	}

	if am.PurgeTime != nil {
		t.PurgeTime = types.StringPointerValue(ptr.Get(am.PurgeTime.Format(time.RFC3339)))
	} else {
		t.PurgeTime = types.StringNull()
	}

	if am.Usages != nil {
		usages := make([]tfcommon.TypedUsage, 0, len(am.Usages))

		for _, entity := range am.Usages {
			tmp, d := commonconv.TypedUsageAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			usages = append(usages, *tmp)
		}

		usagesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.TypedUsage).GetSchema().Attributes),
		}, usages)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Usages = usagesList
	} else {
		t.Usages = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.TypedUsage).GetSchema().Attributes),
		})
	}

	if am.Description != nil {
		t.Description = types.StringPointerValue(am.Description)
	} else {
		t.Description = types.StringNull()
	}

	if am.Id != nil {
		t.Id = types.StringPointerValue(ptr.Get(am.Id.ID()))
	} else {
		t.Id = types.StringNull()
	}

	return &t, diags
}

func HmacKeyMetadataTFToAPIRequestModel(ctx context.Context, plan *tfmodel.HmacKeyMetadata) (*apimodel.HmacKeyMetadataRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.HmacKeyMetadataRequest

	if !plan.DisplayName.IsNull() && !plan.DisplayName.IsUnknown() {
		am.DisplayName = plan.DisplayName.ValueStringPointer()
	}

	if !plan.Usages.IsNull() && !plan.Usages.IsUnknown() {
		usages := make([]tfcommon.TypedUsage, 0)
		dUsages := plan.Usages.ElementsAs(ctx, &usages, false)
		diags = append(diags, dUsages...)
		if diags.HasError() {
			return nil, diags
		}

		am.Usages = make([]commonapimodel.TypedUsageRequest, 0, len(usages))

		for _, entity := range usages {
			tmp, d := commonconv.TypedUsageTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Usages = append(am.Usages, *tmp)
		}
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		am.Description = plan.Description.ValueStringPointer()
	}

	return &am, diags
}

func HmacKeyMetadataTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.HmacKeyMetadata) (*apimodel.UpdateHmacKeyMetadataRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.HmacKeyMetadata{}
	}

	var diags tfdiag.Diagnostics
	var am apimodel.UpdateHmacKeyMetadataRequest

	if !plan.DisplayName.Equal(state.DisplayName) {
		if !plan.DisplayName.IsNull() && !plan.DisplayName.IsUnknown() {
			am.DisplayName.SetTo(plan.DisplayName.ValueString())
		}
	}

	if !plan.Usages.Equal(state.Usages) {
		if !plan.Usages.IsNull() && !plan.Usages.IsUnknown() {
			usages := make([]tfcommon.TypedUsage, 0)
			dUsages := plan.Usages.ElementsAs(ctx, &usages, false)
			diags = append(diags, dUsages...)
			if diags.HasError() {
				return nil, diags
			}

			usagesTmp := make([]commonapimodel.UpdateTypedUsageRequest, 0, len(usages))

			for _, entity := range usages {
				stateEntity := tfcommon.TypedUsage{}
				tmp, d := commonconv.TypedUsageTFToAPIUpdateRequestModel(ctx, &entity, &stateEntity)
				diags = append(diags, d...)
				if diags.HasError() {
					return nil, diags
				}
				usagesTmp = append(usagesTmp, *tmp)
			}
			am.Usages.SetTo(usagesTmp)
		}
	}

	if !plan.Description.Equal(state.Description) {
		if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
			am.Description.SetTo(plan.Description.ValueString())
		}
	}

	return &am, diags
}
