// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type KafkaInstanceStatus struct {
	Disk types.Object `tfsdk:"disk"`
}

func (s *KafkaInstanceStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Параметры виртуальной машины, где работает брокер Кафки.`,
		Attributes: map[string]schema.Attribute{
			"disk": schema.SingleNestedAttribute{
				Attributes:          new(KafkaDataDiskStatus).GetSchema().Attributes,
				MarkdownDescription: `Параметры диска с данными на узле кластера Managed Kafka.`,
				Computed:            true,
			},
		},
	}
}
