// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type KafkaEndpointStatus struct {
	Name             types.String `tfsdk:"name"`
	Network          types.String `tfsdk:"network"`
	BootstrapServers types.String `tfsdk:"bootstrap_servers"`
	Port             types.Int64  `tfsdk:"port"`
	BrokerAddresses  types.List   `tfsdk:"broker_addresses"`
	ExternalAccess   types.Object `tfsdk:"external_access"`
}

func (s *KafkaEndpointStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описание эндпойнтов кластера в пользовательской сети (VPC)`,
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: `Имя эндпойнта.`,
				Computed:            true,
			},
			"network": schema.StringAttribute{
				MarkdownDescription: `Идентификатор пользовательской сети (VPC).`,
				Computed:            true,
			},
			"bootstrap_servers": schema.StringAttribute{
				MarkdownDescription: `Список адресов для первоначального подключения к кластеру внутри пользовательской (VPC).`,
				Computed:            true,
			},
			"port": schema.Int64Attribute{
				MarkdownDescription: `Порт для доступа к кластеру Kafka внутри пользовательской сети (VPC).`,
				Computed:            true,
			},
			"broker_addresses": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: new(KafkaEndpointBrokerAddressStatus).GetSchema().Attributes,
				},
				MarkdownDescription: `Список адресов в пользовательской сети, на которые "отображаются" брокеры.`,
				Computed:            true,
			},
			"external_access": schema.SingleNestedAttribute{
				Attributes:          new(KafkaEndpointExternalAccessesStatus).GetSchema().Attributes,
				MarkdownDescription: `Настройка внешнего доступа к кластеру Kafka.`,
				Computed:            true,
			},
		},
	}
}
