// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
)

type KafkaClusterStatus struct {
	tfcommon.ResourceStatus
	State                ClusterState  `tfsdk:"state"`
	Health               ClusterHealth `tfsdk:"health"`
	Message              types.String  `tfsdk:"message"`
	EffectiveKafkaConfig types.Map     `tfsdk:"effective_kafka_config"`
	Instances            types.Object  `tfsdk:"instances"`
	Endpoints            types.List    `tfsdk:"endpoints"`
	MaintenanceWindow    types.Object  `tfsdk:"maintenance_window"`
	SchemaRegistry       types.Object  `tfsdk:"schema_registry"`
}

func (s *KafkaClusterStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"ready": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.ResourceStatusReady).GetSchema().Attributes,
				MarkdownDescription: `Информация о статусе реконсиляции`,
				Computed:            true,
			},
			"state": schema.StringAttribute{
				MarkdownDescription: `Состояние кластера
  * "CREATING"     - Создаётся
  * "RUNNING"      - Работает в штатном режиме
  * "STOPPING"     - Останавливается
  * "STOPPED"      - Остановлен
  * "STARTING"     - Запуск ранее остановленного
  * "UPDATING"     - Выполняется обновление
  * "ERROR"        - Произошла ошибка, требуется участие команды поддержки
  * "DELETING"     - Удаляется
  * "DELETED"      - Удалён
  * "UNIDENTIFIED" - Не удаётся определить статус
  * "RESTORING"    - Восстанавливается`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"CREATING",
						"RUNNING",
						"STOPPING",
						"STOPPED",
						"STARTING",
						"UPDATING",
						"ERROR",
						"UNIDENTIFIED",
						"DELETING",
						"DELETED",
						"RESTORING",
					),
				},
				Computed: true,
			},
			"health": schema.StringAttribute{
				MarkdownDescription: `Работоспособность кластера
  * "ALIVE"    - Полностью работоспособен
  * "DEGRADED" - Деградирует (некоторые, но не все, экземпляры неработоспособны)
  * "FAILED"   - Неработоспособен
  * "UNKNOWN"  - Не удаётся определить состояние (на этапе создания)`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"ALIVE",
						"DEGRADED",
						"FAILED",
						"UNKNOWN",
					),
				},
				Computed: true,
			},
			"message": schema.StringAttribute{
				Computed: true,
			},
			"effective_kafka_config": schema.MapAttribute{
				ElementType:         types.StringType,
				MarkdownDescription: `Конфигурация параметров кластера после валидации и преобразования из пользователского ввода`,
				Computed:            true,
			},
			"instances": schema.SingleNestedAttribute{
				Attributes:          new(KafkaInstancesStatus).GetSchema().Attributes,
				MarkdownDescription: `Описание ресурсов хостов брокеров и контроллеров.`,
				Computed:            true,
			},
			"endpoints": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: new(KafkaEndpointStatus).GetSchema().Attributes,
				},
				MarkdownDescription: `Описание эндпойнтов в сетях пользователя (VPC) для подключения к брокерам кластера.`,
				Computed:            true,
			},
			"maintenance_window": schema.SingleNestedAttribute{
				Attributes: new(tfcommon.MaintenanceWindow2).GetSchema().Attributes,
				Computed:   true,
			},
			"schema_registry": schema.SingleNestedAttribute{
				Attributes:          new(KafkaSchemaRegistrySpec).GetSchema().Attributes,
				MarkdownDescription: `Настройка Schema Registry для кластера.`,
				Computed:            true,
			},
		},
	}
}
