// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/gpt/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/gpt/converter"
)

func TestCapabilitiesAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.CapabilitiesResponse{}
	_, diags := conv.CapabilitiesAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
