// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/iam"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

func CommonRoleBindingFederationAPIToTFModel(ctx context.Context, am *commonapimodel.CommonRoleBindingFederation) (*tfcommon.CommonRoleBindingFederation, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.CommonRoleBindingFederation

	t.Id = types.StringValue(am.Id.Path())

	if am.Context != nil {
		contextTmp, d := CommonRoleBindingFederationContextAPIToTFModel(ctx, am.Context)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		contextTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfcommon.CommonRoleBindingFederationContext).GetSchema().Attributes),
			*contextTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Context = contextTfObject
	} else {
		t.Context = types.ObjectNull(tfconv.GetAttributesTypes(new(tfcommon.CommonRoleBindingFederationContext).GetSchema().Attributes))
	}

	return &t, diags
}

func CommonRoleBindingFederationAPIResponseToTFModel(ctx context.Context, am *commonapimodel.CommonRoleBindingFederationResponse) (*tfcommon.CommonRoleBindingFederation, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.CommonRoleBindingFederation

	t.Id = types.StringValue(am.Id.Path())

	if am.Context != nil {
		contextTmp, d := CommonRoleBindingFederationContextAPIResponseToTFModel(ctx, am.Context)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		contextTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfcommon.CommonRoleBindingFederationContext).GetSchema().Attributes),
			*contextTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Context = contextTfObject
	} else {
		t.Context = types.ObjectNull(tfconv.GetAttributesTypes(new(tfcommon.CommonRoleBindingFederationContext).GetSchema().Attributes))
	}

	return &t, diags
}

func CommonRoleBindingFederationAPIOptionalResponseToTFModel(ctx context.Context, am *commonapimodel.CommonRoleBindingFederationOptionalResponse) (*tfcommon.CommonRoleBindingFederation, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.CommonRoleBindingFederation

	t.Id = types.StringValue(am.Id.Path())

	if val, ok := am.Context.Get(); ok {
		contextTmp, d := CommonRoleBindingFederationContextAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		contextTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfcommon.CommonRoleBindingFederationContext).GetSchema().Attributes),
			*contextTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Context = contextTfObject
	} else {
		t.Context = types.ObjectNull(tfconv.GetAttributesTypes(new(tfcommon.CommonRoleBindingFederationContext).GetSchema().Attributes))
	}

	return &t, diags
}

func CommonRoleBindingFederationTFToAPIModel(ctx context.Context, plan *tfcommon.CommonRoleBindingFederation) (*commonapimodel.CommonRoleBindingFederation, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.CommonRoleBindingFederation

	if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
		idRef, err := iam.ParseUserFederationRef(ctx, plan.Id.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Id = idRef
	}

	if !plan.Context.IsNull() && !plan.Context.IsUnknown() {
		contextPlan := tfcommon.CommonRoleBindingFederationContext{}
		contextPlanDiag := plan.Context.As(ctx, &contextPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, contextPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		contextTmp, contextDiag := CommonRoleBindingFederationContextTFToAPIModel(ctx, &contextPlan)
		diags = append(diags, contextDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Context = contextTmp
	}

	return &am, diags
}

func CommonRoleBindingFederationTFToAPIRequestModel(ctx context.Context, plan *tfcommon.CommonRoleBindingFederation) (*commonapimodel.CommonRoleBindingFederationRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.CommonRoleBindingFederationRequest

	if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
		idRef, err := iam.ParseUserFederationRef(ctx, plan.Id.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Id = idRef
	}

	if !plan.Context.IsNull() && !plan.Context.IsUnknown() {
		contextPlan := tfcommon.CommonRoleBindingFederationContext{}
		contextPlanDiag := plan.Context.As(ctx, &contextPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, contextPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		contextTmp, contextDiag := CommonRoleBindingFederationContextTFToAPIRequestModel(ctx, &contextPlan)
		diags = append(diags, contextDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Context = contextTmp
	}

	return &am, diags
}

func CommonRoleBindingFederationTFToAPIUpdateModel(ctx context.Context, plan, state *tfcommon.CommonRoleBindingFederation) (*commonapimodel.UpdateCommonRoleBindingFederation, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfcommon.CommonRoleBindingFederation{}
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.UpdateCommonRoleBindingFederation

	if !plan.Id.Equal(state.Id) {
		if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
			idRef, err := iam.ParseUserFederationRef(ctx, plan.Id.ValueString())
			if err != nil {
				diags.AddError("reference parsing", err.Error())
				return nil, diags
			}
			am.Id.SetTo(idRef)
		}
	}

	if !plan.Context.Equal(state.Context) {
		if !plan.Context.IsNull() && !plan.Context.IsUnknown() {
			contextPlan := tfcommon.CommonRoleBindingFederationContext{}
			contextPlanDiag := plan.Context.As(ctx, &contextPlan, basetypes.ObjectAsOptions{})
			diags = append(diags, contextPlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			contextState := tfcommon.CommonRoleBindingFederationContext{}
			if !state.Context.IsNull() && !state.Context.IsUnknown() {
				contextStateDiag := state.Context.As(ctx, &contextState, basetypes.ObjectAsOptions{})
				diags = append(diags, contextStateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			contextTmp, contextDiag := CommonRoleBindingFederationContextTFToAPIUpdateModel(ctx, &contextPlan, &contextState)
			diags = append(diags, contextDiag...)
			if diags.HasError() {
				return nil, diags
			}
			am.Context.SetTo(*contextTmp)
		} else if plan.Context.IsNull() {
			am.Context.SetToNull()
		}
	}

	return &am, diags
}

func CommonRoleBindingFederationTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfcommon.CommonRoleBindingFederation) (*commonapimodel.UpdateCommonRoleBindingFederationRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfcommon.CommonRoleBindingFederation{}
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.UpdateCommonRoleBindingFederationRequest

	if !plan.Id.Equal(state.Id) {
		if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
			idRef, err := iam.ParseUserFederationRef(ctx, plan.Id.ValueString())
			if err != nil {
				diags.AddError("reference parsing", err.Error())
				return nil, diags
			}
			am.Id.SetTo(idRef)
		}
	}

	if !plan.Context.Equal(state.Context) {
		if !plan.Context.IsNull() && !plan.Context.IsUnknown() {
			contextPlan := tfcommon.CommonRoleBindingFederationContext{}
			contextPlanDiag := plan.Context.As(ctx, &contextPlan, basetypes.ObjectAsOptions{})
			diags = append(diags, contextPlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			contextState := tfcommon.CommonRoleBindingFederationContext{}
			if !state.Context.IsNull() && !state.Context.IsUnknown() {
				contextStateDiag := state.Context.As(ctx, &contextState, basetypes.ObjectAsOptions{})
				diags = append(diags, contextStateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			contextTmp, contextDiag := CommonRoleBindingFederationContextTFToAPIUpdateRequestModel(ctx, &contextPlan, &contextState)
			diags = append(diags, contextDiag...)
			if diags.HasError() {
				return nil, diags
			}
			am.Context.SetTo(*contextTmp)
		} else if plan.Context.IsNull() {
			am.Context.SetToNull()
		}
	}

	return &am, diags
}
