// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/go-sdk/pkg/apimodels/ipaddress"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

func ResourceExternalAddressStatusAPIToTFModel(ctx context.Context, am *commonapimodel.ResourceExternalAddressStatus) (*tfcommon.ResourceExternalAddressStatus, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressStatus

	t.Ref = types.StringValue(am.Ref.Path())

	t.IpAddress = types.StringValue(ptr.Value(am.IpAddress.RawValue()))

	return &t, diags
}

func ResourceExternalAddressStatusAPIResponseToTFModel(ctx context.Context, am *commonapimodel.ResourceExternalAddressStatusResponse) (*tfcommon.ResourceExternalAddressStatus, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressStatus

	t.Ref = types.StringValue(am.Ref.Path())

	t.IpAddress = types.StringValue(ptr.Value(am.IpAddress.RawValue()))

	return &t, diags
}

func ResourceExternalAddressStatusAPIOptionalResponseToTFModel(ctx context.Context, am *commonapimodel.ResourceExternalAddressStatusOptionalResponse) (*tfcommon.ResourceExternalAddressStatus, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressStatus

	t.Ref = types.StringValue(am.Ref.Path())

	t.IpAddress = types.StringValue(ptr.Value(am.IpAddress.RawValue()))

	return &t, diags
}

func ResourceExternalAddressStatusTFToAPIModel(ctx context.Context, plan *tfcommon.ResourceExternalAddressStatus) (*commonapimodel.ResourceExternalAddressStatus, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.ResourceExternalAddressStatus

	if !plan.Ref.IsNull() && !plan.Ref.IsUnknown() {
		refRef, err := vpc.ParseExternalAddressRef(ctx, plan.Ref.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Ref = refRef
	}

	if !plan.IpAddress.IsNull() && !plan.IpAddress.IsUnknown() {
		tmpIpAddress, err := ipaddress.ParseIPAddressString(plan.IpAddress.ValueString())
		if err != nil {
			diags.AddError("IPAddress string parsing", err.Error())
			return nil, diags
		}
		am.IpAddress = tmpIpAddress
	}

	return &am, diags
}

func ResourceExternalAddressStatusTFToAPIRequestModel(ctx context.Context, plan *tfcommon.ResourceExternalAddressStatus) (*commonapimodel.ResourceExternalAddressStatusRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.ResourceExternalAddressStatusRequest

	if !plan.Ref.IsNull() && !plan.Ref.IsUnknown() {
		refRef, err := vpc.ParseExternalAddressRef(ctx, plan.Ref.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Ref = refRef
	}

	if !plan.IpAddress.IsNull() && !plan.IpAddress.IsUnknown() {
		tmpIpAddress, err := ipaddress.ParseIPAddressString(plan.IpAddress.ValueString())
		if err != nil {
			diags.AddError("IPAddress string parsing", err.Error())
			return nil, diags
		}
		am.IpAddress = tmpIpAddress
	}

	return &am, diags
}
