// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

func ResourceExternalAddressSpecAPIToTFModel(ctx context.Context, am *commonmodel.ResourceExternalAddressSpec) (*tfcommon.ResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressSpec

	if am.NatGateway != nil {
		t.NatGateway = types.StringPointerValue(ptr.Get(am.NatGateway.Path()))
	} else {
		t.NatGateway = types.StringNull()
	}

	return &t, diags
}

func ResourceExternalAddressSpecAPIResponseToTFModel(ctx context.Context, am *commonmodel.ResourceExternalAddressSpecResponse) (*tfcommon.ResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressSpec

	if am.NatGateway != nil {
		t.NatGateway = types.StringPointerValue(ptr.Get(am.NatGateway.Path()))
	} else {
		t.NatGateway = types.StringNull()
	}

	return &t, diags
}

func ResourceExternalAddressSpecAPIOptionalResponseToTFModel(ctx context.Context, am *commonmodel.ResourceExternalAddressSpecOptionalResponse) (*tfcommon.ResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressSpec

	if val, ok := am.NatGateway.Get(); ok {
		t.NatGateway = types.StringPointerValue(ptr.Get(val.Path()))
	} else {
		t.NatGateway = types.StringNull()
	}

	return &t, diags
}

func ResourceExternalAddressSpecTFToAPIModel(ctx context.Context, plan *tfcommon.ResourceExternalAddressSpec) (*commonmodel.ResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonmodel.ResourceExternalAddressSpec

	if !plan.NatGateway.IsNull() && !plan.NatGateway.IsUnknown() {
		natGatewayRef, err := vpc.ParseNatGatewayRef(ctx, plan.NatGateway.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.NatGateway = &natGatewayRef
	}

	return &am, diags
}

func ResourceExternalAddressSpecTFToAPIRequestModel(ctx context.Context, plan *tfcommon.ResourceExternalAddressSpec) (*commonmodel.ResourceExternalAddressSpecRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonmodel.ResourceExternalAddressSpecRequest

	if !plan.NatGateway.IsNull() && !plan.NatGateway.IsUnknown() {
		natGatewayRef, err := vpc.ParseNatGatewayRef(ctx, plan.NatGateway.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.NatGateway = &natGatewayRef
	}

	return &am, diags
}

func ResourceExternalAddressSpecTFToAPIUpdateModel(ctx context.Context, plan, state *tfcommon.ResourceExternalAddressSpec) (*commonmodel.UpdateResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfcommon.ResourceExternalAddressSpec{}
	}

	var diags tfdiag.Diagnostics
	var am commonmodel.UpdateResourceExternalAddressSpec

	if !plan.NatGateway.Equal(state.NatGateway) {
		if !plan.NatGateway.IsNull() && !plan.NatGateway.IsUnknown() {
			natGatewayRef, err := vpc.ParseNatGatewayRef(ctx, plan.NatGateway.ValueString())
			if err != nil {
				diags.AddError("reference parsing", err.Error())
				return nil, diags
			}
			am.NatGateway.SetTo(natGatewayRef)
		}
	}

	return &am, diags
}

func ResourceExternalAddressSpecTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfcommon.ResourceExternalAddressSpec) (*commonmodel.UpdateResourceExternalAddressSpecRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfcommon.ResourceExternalAddressSpec{}
	}

	var diags tfdiag.Diagnostics
	var am commonmodel.UpdateResourceExternalAddressSpecRequest

	if !plan.NatGateway.Equal(state.NatGateway) {
		if !plan.NatGateway.IsNull() && !plan.NatGateway.IsUnknown() {
			natGatewayRef, err := vpc.ParseNatGatewayRef(ctx, plan.NatGateway.ValueString())
			if err != nil {
				diags.AddError("reference parsing", err.Error())
				return nil, diags
			}
			am.NatGateway.SetTo(natGatewayRef)
		}
	}

	return &am, diags
}
