// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

func UsageAPIToTFModel(ctx context.Context, am *commonapimodel.Usage) (*tfcommon.Usage, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.Usage

	t.UsageType = types.StringValue(am.UsageType)

	t.Name = types.StringValue(am.Name)

	t.Resource = types.StringValue(am.Resource)

	return &t, diags
}

func UsageAPIResponseToTFModel(ctx context.Context, am *commonapimodel.UsageResponse) (*tfcommon.Usage, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.Usage

	t.UsageType = types.StringValue(am.UsageType)

	t.Name = types.StringValue(am.Name)

	t.Resource = types.StringValue(am.Resource)

	return &t, diags
}

func UsageAPIOptionalResponseToTFModel(ctx context.Context, am *commonapimodel.UsageOptionalResponse) (*tfcommon.Usage, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.Usage

	t.UsageType = types.StringValue(am.UsageType)

	t.Name = types.StringValue(am.Name)

	t.Resource = types.StringValue(am.Resource)

	return &t, diags
}

func UsageTFToAPIModel(ctx context.Context, plan *tfcommon.Usage) (*commonapimodel.Usage, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.Usage

	if !plan.UsageType.IsNull() && !plan.UsageType.IsUnknown() {
		am.UsageType = plan.UsageType.ValueString()
	}

	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		am.Name = plan.Name.ValueString()
	}

	if !plan.Resource.IsNull() && !plan.Resource.IsUnknown() {
		am.Resource = plan.Resource.ValueString()
	}

	return &am, diags
}

func UsageTFToAPIRequestModel(ctx context.Context, plan *tfcommon.Usage) (*commonapimodel.UsageRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.UsageRequest

	if !plan.UsageType.IsNull() && !plan.UsageType.IsUnknown() {
		am.UsageType = plan.UsageType.ValueString()
	}

	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		am.Name = plan.Name.ValueString()
	}

	if !plan.Resource.IsNull() && !plan.Resource.IsUnknown() {
		am.Resource = plan.Resource.ValueString()
	}

	return &am, diags
}

func UsageTFToAPIUpdateModel(ctx context.Context, plan, state *tfcommon.Usage) (*commonapimodel.UpdateUsage, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfcommon.Usage{}
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.UpdateUsage

	if !plan.UsageType.Equal(state.UsageType) {
		if !plan.UsageType.IsNull() && !plan.UsageType.IsUnknown() {
			am.UsageType.SetTo(plan.UsageType.ValueString())
		}
	}

	if !plan.Name.Equal(state.Name) {
		if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
			am.Name.SetTo(plan.Name.ValueString())
		}
	}

	if !plan.Resource.Equal(state.Resource) {
		if !plan.Resource.IsNull() && !plan.Resource.IsUnknown() {
			am.Resource.SetTo(plan.Resource.ValueString())
		}
	}

	return &am, diags
}

func UsageTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfcommon.Usage) (*commonapimodel.UpdateUsageRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfcommon.Usage{}
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.UpdateUsageRequest

	if !plan.UsageType.Equal(state.UsageType) {
		if !plan.UsageType.IsNull() && !plan.UsageType.IsUnknown() {
			am.UsageType.SetTo(plan.UsageType.ValueString())
		}
	}

	if !plan.Name.Equal(state.Name) {
		if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
			am.Name.SetTo(plan.Name.ValueString())
		}
	}

	if !plan.Resource.Equal(state.Resource) {
		if !plan.Resource.IsNull() && !plan.Resource.IsUnknown() {
			am.Resource.SetTo(plan.Resource.ValueString())
		}
	}

	return &am, diags
}
