// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	localint64planmodifier "go.mws.cloud/terraform-provider-mws/internal/planmodifier/int64planmodifier"
	localstringplanmodifier "go.mws.cloud/terraform-provider-mws/internal/planmodifier/stringplanmodifier"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

type Disk struct {
	Kind      types.String `tfsdk:"kind"`
	Metadata  types.Object `tfsdk:"metadata"`
	Status    types.Object `tfsdk:"status"`
	Zone      types.String `tfsdk:"zone"`
	Size      types.String `tfsdk:"size"`
	Source    types.Object `tfsdk:"source"`
	DiskType  types.String `tfsdk:"disk_type"`
	Iops      Iops         `tfsdk:"iops"`
	BlockSize types.String `tfsdk:"block_size"`
	OsType    OsType       `tfsdk:"os_type"`
}

func (s *Disk) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Диск — виртуальный аналог физического накопителя, предназначенный для хранения данных виртуальных машин (ВМ) и приложений`,
		Attributes: map[string]schema.Attribute{
			"kind": schema.StringAttribute{
				MarkdownDescription: `Тип объекта (disk)`,
				Computed:            true,
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes,
				MarkdownDescription: `Дополнительная информация об объекте`,
				Computed:            true,
				Optional:            true,
			},
			"status": schema.SingleNestedAttribute{
				Attributes:          new(DiskStatus).GetSchema().Attributes,
				MarkdownDescription: `Статус глобального диска`,
				Computed:            true,
			},
			"zone": schema.StringAttribute{
				MarkdownDescription: `Зона доступности (ЦОД)`,
				Computed:            true,
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"size": schema.StringAttribute{
				MarkdownDescription: `Размер диска`,
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					localstringplanmodifier.RequiresReplaceIfRemoved(),
				},
			},
			"source": schema.SingleNestedAttribute{
				Attributes:          new(DiskSpecSource).GetSchema().Attributes,
				MarkdownDescription: `Источник для создания диска`,
				Optional:            true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"disk_type": schema.StringAttribute{
				MarkdownDescription: `ID типа диска`,
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"iops": schema.Int64Attribute{
				MarkdownDescription: `Запрашиваемое пользователем количество операций ввода-вывода в секунду (IOPS)`,
				Optional:            true,
				PlanModifiers: []planmodifier.Int64{
					localint64planmodifier.RequiresReplaceIfRemoved(),
				},
			},
			"block_size": schema.StringAttribute{
				MarkdownDescription: `Размер блока диска`,
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"os_type": schema.StringAttribute{
				MarkdownDescription: `Тип операционной системы`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"LINUX",
						"WINDOWS",
					),
				},
				Optional: true,
				PlanModifiers: []planmodifier.String{
					localstringplanmodifier.RequiresReplaceIfRemoved(),
				},
			},
		},
	}
}
