// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DiskBackupModel struct {
	ProjectParam    types.String   `tfsdk:"project"`
	DiskBackupParam types.String   `tfsdk:"disk_backup"`
	Timeouts        timeouts.Value `tfsdk:"timeouts"`
	ID              types.String   `tfsdk:"id"`
	DiskBackup
}
