// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ImageModel struct {
	ProjectParam types.String   `tfsdk:"project"`
	ImageParam   types.String   `tfsdk:"image"`
	Timeouts     timeouts.Value `tfsdk:"timeouts"`
	ID           types.String   `tfsdk:"id"`
	Image
}
