// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	localmapplanmodifier "go.mws.cloud/terraform-provider-mws/internal/planmodifier/mapplanmodifier"
)

type OsSpec struct {
	Hostname           types.String `tfsdk:"hostname"`
	LocalDomain        types.String `tfsdk:"local_domain"`
	StandardDnsRecords types.Bool   `tfsdk:"standard_dns_records"`
	Metadata           types.Object `tfsdk:"metadata"`
}

func (s *OsSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"hostname": schema.StringAttribute{
				Optional: true,
			},
			"local_domain": schema.StringAttribute{
				Optional: true,
			},
			"standard_dns_records": schema.BoolAttribute{
				Optional: true,
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes: new(OsSpecMetadata).GetSchema().Attributes,
				Optional:   true,
			},
		},
	}
}

type OsSpecMetadata struct {
	Attributes types.Map `tfsdk:"attributes"`
}

func (s *OsSpecMetadata) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля Metadata анонимного типа структуры OsSpec`,
		Attributes: map[string]schema.Attribute{
			"attributes": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
				PlanModifiers: []planmodifier.Map{
					localmapplanmodifier.RequiresReplaceIfRemoved(),
				},
			},
		},
	}
}
