// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SnapshotSource struct {
	Disk types.Object `tfsdk:"disk"`
}

func (s *SnapshotSource) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Источник для создания снимка (На текущий момент поддерживается только диск, но в будущем будут и другие источники)`,
		Attributes: map[string]schema.Attribute{
			"disk": schema.SingleNestedAttribute{
				Attributes:          new(SnapshotSourceDisk).GetSchema().Attributes,
				MarkdownDescription: `Диск как источник для снимка`,
				Optional:            true,
			},
		},
	}
}

type SnapshotSourceDisk struct {
	Id types.String `tfsdk:"id"`
}

func (s *SnapshotSourceDisk) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля Disk анонимного типа структуры SnapshotSource`,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: `ID диска-источника`,
				Required:            true,
			},
		},
	}
}
