// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type StorageDiskSpecOrRef struct {
	Ref  types.String `tfsdk:"ref"`
	Spec types.Object `tfsdk:"spec"`
}

func (s *StorageDiskSpecOrRef) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"ref": schema.StringAttribute{
				Optional: true,
			},
			"spec": schema.SingleNestedAttribute{
				Attributes: new(StorageDiskSpec).GetSchema().Attributes,
				Optional:   true,
			},
		},
	}
}
