// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

type VirtualMachineAddressStatus struct {
	Subnet      types.String `tfsdk:"subnet"`
	Network     types.String `tfsdk:"network"`
	Ref         types.String `tfsdk:"ref"`
	IpAddress   types.String `tfsdk:"ip_address"`
	StandardDns types.Object `tfsdk:"standard_dns"`
	Dns         types.List   `tfsdk:"dns"`
	Ready       types.Object `tfsdk:"ready"`
	OneToOneNat types.Object `tfsdk:"one_to_one_nat"`
}

func (s *VirtualMachineAddressStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"subnet": schema.StringAttribute{
				MarkdownDescription: `Подсеть, в которой был создан адрес
`,
				Computed: true,
			},
			"network": schema.StringAttribute{
				MarkdownDescription: `Сеть, в которой был создан адрес
`,
				Computed: true,
			},
			"ref": schema.StringAttribute{
				MarkdownDescription: `ref на ресурс Адрес
`,
				Computed: true,
			},
			"ip_address": schema.StringAttribute{
				MarkdownDescription: `Выделенный IP-адрес
`,
				Computed: true,
			},
			"standard_dns": schema.SingleNestedAttribute{
				Attributes: new(VirtualMachineAddressDnsStatus).GetSchema().Attributes,
				Computed:   true,
			},
			"dns": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: new(VirtualMachineAddressDnsStatus).GetSchema().Attributes,
				},
				Computed: true,
			},
			"ready": schema.SingleNestedAttribute{
				Attributes: new(tfcommon.ResourceStatusReady).GetSchema().Attributes,
				MarkdownDescription: `Статус ресурса Адрес
`,
				Computed: true,
			},
			"one_to_one_nat": schema.SingleNestedAttribute{
				Attributes: new(VirtualMachineOneToOneNatStatus).GetSchema().Attributes,
				Computed:   true,
			},
		},
	}
}
