// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/mk8s/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mk8s/converter"
)

func TestClusterStatusAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ClusterStatusResponse{
		ResourceStatusResponse: commonmodel.ResourceStatusResponse{
			Ready: commonmodel.ResourceStatusReadyResponse{
				State: "",
			},
		},
	}
	_, diags := conv.ClusterStatusAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestClusterStatusClusterStatusAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ClusterStatusClusterStatusResponse{}
	_, diags := conv.ClusterStatusClusterStatusAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestClusterStatusNetworkAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ClusterStatusNetworkResponse{}
	_, diags := conv.ClusterStatusNetworkAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestClusterStatusNetworkPrimaryEndpointAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ClusterStatusNetworkPrimaryEndpointResponse{
		Ref: vpc.NewMustAddressRef("projectID", "networkID", "addressID"),
	}
	_, diags := conv.ClusterStatusNetworkPrimaryEndpointAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestClusterStatusNetworkPublicEndpointAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ClusterStatusNetworkPublicEndpointResponse{
		Ref: vpc.NewMustExternalAddressRef("projectID", "externalAddressID"),
	}
	_, diags := conv.ClusterStatusNetworkPublicEndpointAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestClusterStatusNetworkSubnetAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ClusterStatusNetworkSubnetResponse{
		Ref: vpc.NewMustSubnetRef("projectID", "networkID", "subnetID"),
	}
	_, diags := conv.ClusterStatusNetworkSubnetAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestClusterStatusNetworkVpcNetworkAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ClusterStatusNetworkVpcNetworkResponse{
		Ref: vpc.NewMustNetworkRef("projectID", "networkID"),
	}
	_, diags := conv.ClusterStatusNetworkVpcNetworkAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
