// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mk8s/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mk8s/converter"
)

func TestClusterAvailabilitySpecAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.ClusterAvailabilitySpecOptionalResponse{}
	_, diags := conv.ClusterAvailabilitySpecAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestClusterAvailabilitySpecRegionalAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.ClusterAvailabilitySpecRegionalOptionalResponse{}
	_, diags := conv.ClusterAvailabilitySpecRegionalAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestClusterAvailabilitySpecStandaloneAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.ClusterAvailabilitySpecStandaloneOptionalResponse{}
	_, diags := conv.ClusterAvailabilitySpecStandaloneAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestClusterAvailabilitySpecZonalHaAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.ClusterAvailabilitySpecZonalHaOptionalResponse{}
	_, diags := conv.ClusterAvailabilitySpecZonalHaAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
