// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	apimodel "go.mws.cloud/go-sdk/service/mk8s/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mk8s/converter"
)

func TestLocalDiskSpecAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.LocalDiskSpecOptionalResponse{}
	_, diags := conv.LocalDiskSpecAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestLocalDiskSpecOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.LocalDiskSpecRequest{
		Name: "name",
		Size: bytesize.MustParseString("0 B"),
	}

	emptyApiModelResponse, err := apimodel.LocalDiskSpecRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.LocalDiskSpecAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.LocalDiskSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.LocalDiskSpecRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}
