// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mk8s/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mk8s/converter"
)

func TestNodeGroupVersionControlStatusAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.NodeGroupVersionControlStatusResponse{}
	_, diags := conv.NodeGroupVersionControlStatusAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
