// Code generated by mwsapigen, DO NOT EDIT.

package kms

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	tfpath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"go.mws.cloud/go-sdk/mws/wait"
	ctxvalues "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/kms/client"
	resourcesdk "go.mws.cloud/go-sdk/service/kms/sdk"
	kmsref "go.mws.cloud/go-sdk/service/resources/references/kms"
	"go.mws.cloud/terraform-provider-mws/internal/cmp"
	"go.mws.cloud/terraform-provider-mws/internal/diag"
	provider "go.mws.cloud/terraform-provider-mws/internal/provider/public"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/kms/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/kms/model"
)

var (
	_ resource.Resource                = &CryptoKeyRoleBindingResource{}
	_ resource.ResourceWithImportState = &CryptoKeyRoleBindingResource{}
)

type CryptoKeyRoleBindingResource struct {
	sdk    *resourcesdk.CryptoKeyRoleBinding
	config *provider.Config
}

func NewCryptoKeyRoleBindingResource() resource.Resource {
	return &CryptoKeyRoleBindingResource{}
}

func (m *CryptoKeyRoleBindingResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	tflog.Info(ctx, "CryptoKeyRoleBindingResource.Metadata")
	resp.TypeName = req.ProviderTypeName + "_kms_crypto_key_role_binding"
}

func (m *CryptoKeyRoleBindingResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	tflog.Info(ctx, "CryptoKeyRoleBindingResource.Schema")
	resp.Schema = new(tfmodel.CryptoKeyRoleBinding).GetSchema()
	resp.Schema.Attributes["key"] = schema.StringAttribute{
		MarkdownDescription: `Название крипто-ключа`,
		Required:            true,
	}
	resp.Schema.Attributes["project"] = schema.StringAttribute{
		MarkdownDescription: `Путь к проекту`,
		Optional:            true,
		Computed:            true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}
	resp.Schema.Attributes["role_binding"] = schema.StringAttribute{
		MarkdownDescription: `Название биндинга роли для крипто-ключа`,
		Required:            true,
	}
	resp.Schema.Attributes["timeouts"] = timeouts.Attributes(ctx, timeouts.Opts{
		Create: true,
		Update: true,
		Delete: true,
	})
	resp.Schema.Attributes["id"] = schema.StringAttribute{
		Computed: true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}
}

func (m *CryptoKeyRoleBindingResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	var err error
	tflog.Info(ctx, "CryptoKeyRoleBindingResource.Configure")
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*provider.Data)
	if !ok || providerData == nil {
		resp.Diagnostics.AddError("Internal Provider Error", "Unexpected type of req.ProviderData")
		return
	}

	m.config = providerData.Config

	m.sdk, err = resourcesdk.NewCryptoKeyRoleBinding(ctx, providerData.SDK)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create SDK client for CryptoKeyRoleBinding",
			diag.FormatError(err),
		)
		return
	}
}

func (m *CryptoKeyRoleBindingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "CryptoKeyRoleBindingResource.Create")

	var data tfmodel.CryptoKeyRoleBindingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Create(ctx, 3600*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.Timeouts")
		return
	}

	body, diags := conv.CryptoKeyRoleBindingTFToAPIRequestModel(ctx, &data.CryptoKeyRoleBinding)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.TFToAPI")
		return
	}

	apiRes, err := m.sdk.CreateCryptoKeyRoleBinding(
		ctx,
		client.UpsertCryptoKeyRoleBindingRequest{
			Project:     data.ProjectParam.ValueString(),
			Key:         data.KeyParam.ValueString(),
			RoleBinding: data.RoleBindingParam.ValueString(),
			Body:        *body,
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create CryptoKeyRoleBinding",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Value.Id.ID())

	tfRes, diags := conv.CryptoKeyRoleBindingAPIOptionalResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.CryptoKeyRoleBinding = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (m *CryptoKeyRoleBindingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	tflog.Info(ctx, "CryptoKeyRoleBindingResource.Read")

	var data tfmodel.CryptoKeyRoleBindingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	apiRes, err := m.sdk.GetCryptoKeyRoleBinding(
		ctx,
		client.GetCryptoKeyRoleBindingRequest{
			Project:     data.ProjectParam.ValueString(),
			Key:         data.KeyParam.ValueString(),
			RoleBinding: data.RoleBindingParam.ValueString(),
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Get CryptoKeyRoleBinding",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Value.Id.ID())

	tfRes, diags := conv.CryptoKeyRoleBindingAPIOptionalResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.CryptoKeyRoleBinding = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (m *CryptoKeyRoleBindingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	tflog.Info(ctx, "CryptoKeyRoleBindingResource.Update")

	var data tfmodel.CryptoKeyRoleBindingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Update(ctx, 3600*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.Timeouts")
		return
	}

	body, diags := conv.CryptoKeyRoleBindingTFToAPIRequestModel(ctx, &data.CryptoKeyRoleBinding)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.TFToAPI")
		return
	}

	apiRes, err := m.sdk.UpdateCryptoKeyRoleBinding(
		ctx,
		client.UpdateCryptoKeyRoleBindingRequest{
			Project:     data.ProjectParam.ValueString(),
			Key:         data.KeyParam.ValueString(),
			RoleBinding: data.RoleBindingParam.ValueString(),
			Body:        body.AsUpdateModel(),
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Update CryptoKeyRoleBinding",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Value.Id.ID())

	tfRes, diags := conv.CryptoKeyRoleBindingAPIOptionalResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.CryptoKeyRoleBinding = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (m *CryptoKeyRoleBindingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	tflog.Info(ctx, "CryptoKeyRoleBindingResource.Delete")

	var data tfmodel.CryptoKeyRoleBindingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Delete(ctx, 3600*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.Timeouts")
		return
	}

	err := m.sdk.DeleteCryptoKeyRoleBinding(
		ctx,
		client.DeleteCryptoKeyRoleBindingRequest{
			Project:     data.ProjectParam.ValueString(),
			Key:         data.KeyParam.ValueString(),
			RoleBinding: data.RoleBindingParam.ValueString(),
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Delete CryptoKeyRoleBinding",
			diag.FormatError(err),
		)
		return
	}
}

func (m *CryptoKeyRoleBindingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Info(ctx, "CryptoKeyRoleBindingResource.ImportState")

	var data tfmodel.CryptoKeyRoleBindingModel

	ref, err := kmsref.ParseCryptoKeyRoleBindingRef(ctx, req.ID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Parse reference for CryptoKeyRoleBinding",
			diag.FormatError(err),
		)
		return
	}

	apiRes, err := m.sdk.GetCryptoKeyRoleBinding(
		ctx,
		client.GetCryptoKeyRoleBindingRequest{
			Project:     ref.GetProject(),
			Key:         ref.GetKey(),
			RoleBinding: ref.GetRoleBinding(),
		})
	if err != nil {
		resp.Diagnostics.AddError(
			"Get CryptoKeyRoleBinding",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Value.Id.ID())

	tfRes, diags := conv.CryptoKeyRoleBindingAPIOptionalResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.CryptoKeyRoleBinding = *tfRes

	data.ProjectParam = types.StringValue(ref.GetProject())
	data.KeyParam = types.StringValue(ref.GetKey())
	data.RoleBindingParam = types.StringValue(ref.GetRoleBinding())

	var rwTimeouts timeouts.Value
	resp.Diagnostics.Append(resp.State.GetAttribute(ctx, tfpath.Root("timeouts"), &rwTimeouts)...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "CryptoKeyRoleBindingResource.timeouts.GetAttribute")
		return
	}
	data.Timeouts = rwTimeouts

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
