// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	"go.mws.cloud/go-sdk/service/certmanager/model"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/certmanager/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/certmanager/model"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

func TestCertificateAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.CertificateOptionalResponse{}
	_, diags := conv.CertificateAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestCertificateOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.CertificateRequest{
		Spec: model.CertificateSpecRequest{},
	}

	emptyApiModelResponse, err := model.CertificateRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.CertificateAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.CertificateTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.CertificateRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateCertificateRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.Certificate
	var stateTfModel tfmodel.Certificate
	stateTfModel.Metadata = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes))
	stateTfModel.SelfManaged = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfmodel.SelfManagedSpec).GetSchema().Attributes))
	stateTfModel.Managed = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfmodel.CertificateManagedSpec).GetSchema().Attributes))

	expectedUpdateModel := &model.UpdateCertificateRequest{
		Metadata: optional.OptionalNil[commonmodel.UpdateCommonTypedResourceMetadataRequest]{
			Set:  true,
			Null: true,
		},
		Spec: optional.NewOptional(model.UpdateCertificateSpecRequest{
			SelfManaged: optional.OptionalNil[model.UpdateSelfManagedSpecRequest]{
				Set:  true,
				Null: true,
			},
			Managed: optional.OptionalNil[model.UpdateCertificateManagedSpecRequest]{
				Set:  true,
				Null: true,
			},
		}),
	}

	result, diags := conv.CertificateTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
