// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/certmanager/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/certmanager/converter"
)

func TestCertificateManagedSpecAcmeServerAPIToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.CertificateManagedSpecAcmeServer("")
	_, diags := conv.CertificateManagedSpecAcmeServerAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestCertificateManagedSpecAcmeServerConverters(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.CertificateManagedSpecAcmeServer("")

	tfModel, diags := conv.CertificateManagedSpecAcmeServerAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())

	result, diags := conv.CertificateManagedSpecAcmeServerTFToAPIModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	require.Equal(t, emptyApiModel, *result)
}
