// Code generated by mwsapigen, DO NOT EDIT.

package rm

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	ctxvalues "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/rm/client"
	resourcesdk "go.mws.cloud/go-sdk/service/rm/sdk"
	"go.mws.cloud/terraform-provider-mws/internal/cmp"
	"go.mws.cloud/terraform-provider-mws/internal/diag"
	provider "go.mws.cloud/terraform-provider-mws/internal/provider/public"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/rm/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/rm/model"
)

var (
	_ datasource.DataSource = &ZoneDataSource{}
)

type ZoneDataSource struct {
	sdk    *resourcesdk.Zone
	config *provider.Config
}

func NewZoneDataSource() datasource.DataSource {
	return &ZoneDataSource{}
}

func (m *ZoneDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	tflog.Info(ctx, "ZoneDataSource.Metadata")
	resp.TypeName = req.ProviderTypeName + "_resmanager_zone"
}

func (m *ZoneDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	tflog.Info(ctx, "ZoneDataSource.Schema")
	resp.Schema = new(tfmodel.Zone).GetSchema()
	resp.Schema.Attributes["zone"] = schema.StringAttribute{
		MarkdownDescription: `Зона (ЦОД).`,
		Optional:            true,
		Computed:            true,
	}
}

func (m *ZoneDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	var err error
	tflog.Info(ctx, "ZoneDataSource.Configure")
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*provider.Data)
	if !ok || providerData == nil {
		resp.Diagnostics.AddError("Internal Provider Error", "Unexpected type of req.ProviderData")
		return
	}

	m.config = providerData.Config

	m.sdk, err = resourcesdk.NewZone(ctx, providerData.SDK)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create SDK client for Zone",
			diag.FormatError(err),
		)
		return
	}
}

func (m *ZoneDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	tflog.Info(ctx, "ZoneDataSource.Read")

	var data tfmodel.ZoneModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	zoneParam := cmp.Or(data.ZoneParam, m.config.Zone)
	if zoneParam.IsNull() || zoneParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "zone" is null or unknown`,
		)
		return
	}
	data.ZoneParam = zoneParam
	ctx = ctxvalues.With(ctx, "zone", zoneParam.String())

	apiRes, err := m.sdk.GetZone(
		ctx,
		client.GetZoneRequest{
			Zone: data.ZoneParam.ValueString(),
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Get Zone",
			diag.FormatError(err),
		)
		return
	}

	tfRes, diags := conv.ZoneAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "ZoneDataSource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.Zone = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
