// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/nlb/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/nlb/converter"
)

func TestNlbStatusHealthCheckTcpAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.NlbStatusHealthCheckTcpResponse{}
	_, diags := conv.NlbStatusHealthCheckTcpAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
