// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CertificateManagedSpec struct {
	PreferredChallengeType CertificateChallengeType `tfsdk:"preferred_challenge_type"`
	Provider               CertificateProvider      `tfsdk:"provider"`
	Domains                types.List               `tfsdk:"domains"`
}

func (s *CertificateManagedSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"preferred_challenge_type": schema.StringAttribute{
				MarkdownDescription: `Предпочтительный тип проверки домена (challenge).  
Возможные значения: DNS01 или HTTP01. По умолчанию используется DNS01.
`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"DNS01",
						"HTTP01",
					),
				},
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"provider": schema.StringAttribute{
				MarkdownDescription: `Провайдер сертификатов, например Let's Encrypt или другой центр сертификации.
`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"LETS_ENCRYPT",
					),
				},
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"domains": schema.ListAttribute{
				ElementType: types.StringType,
				MarkdownDescription: `Список доменов, для которых будет выдан сертификат.
`,
				Required: true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
		},
	}
}
