// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mpostgres/converter"
)

func TestDataDiskTypeAPIToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.DataDiskType("")
	_, diags := conv.DataDiskTypeAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
