// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mpostgres/converter"
)

func TestPostgresBackupAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.PostgresBackupResponse{}
	_, diags := conv.PostgresBackupAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestPostgresBackupMetadataAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.PostgresBackupMetadataResponse{
		TypedResourceMetadataResponse: commonmodel.TypedResourceMetadataResponse{},
	}
	_, diags := conv.PostgresBackupMetadataAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
