// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mpostgres/converter"
)

func TestPostgresEndpointAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.PostgresEndpointResponse{
		Name:             "name",
		Network:          vpc.NewMustNetworkRef("projectID", "networkID"),
		PrimaryAddresses: []model.PostgresNetworkAddressResponse{},
	}
	_, diags := conv.PostgresEndpointAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
