// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/kms/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/kms/converter"
)

func TestCryptoKeyVersionStatusAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.CryptoKeyVersionStatusResponse{}
	_, diags := conv.CryptoKeyVersionStatusAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestCryptoKeyVersionStatusDestructionAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.CryptoKeyVersionStatusDestructionResponse{}
	_, diags := conv.CryptoKeyVersionStatusDestructionAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
