// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"go.mws.cloud/go-sdk/service/compute/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/compute/model"
)

func NetworkInterfaceSpecAPIOptionalResponseToTFModel(ctx context.Context, am *model.NetworkInterfaceSpecOptionalResponse) (*tfmodel.NetworkInterfaceSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NetworkInterfaceSpec

	t.Name = types.StringValue(am.Name)

	if val, ok := am.Primary.Get(); ok {
		t.Primary = types.BoolValue(val)
	} else {
		t.Primary = types.BoolNull()
	}

	if val, ok := am.IpForwardingEnabled.Get(); ok {
		t.IpForwardingEnabled = types.BoolValue(val)
	} else {
		t.IpForwardingEnabled = types.BoolNull()
	}

	if am.Addresses != nil {
		addresses := make([]tfmodel.AddressSpecOrRefWithAttachments, 0, len(am.Addresses))

		for _, entity := range am.Addresses {
			tmp, d := AddressSpecOrRefWithAttachmentsAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			addresses = append(addresses, *tmp)
		}

		addressesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.AddressSpecOrRefWithAttachments).GetSchema().Attributes),
		}, addresses)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Addresses = addressesList
	} else {
		t.Addresses = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.AddressSpecOrRefWithAttachments).GetSchema().Attributes),
		})
	}

	return &t, diags
}

func NetworkInterfaceSpecTFToAPIRequestModel(ctx context.Context, plan *tfmodel.NetworkInterfaceSpec) (*model.NetworkInterfaceSpecRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.NetworkInterfaceSpecRequest

	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		am.Name = plan.Name.ValueString()
	}

	if !plan.Primary.IsNull() && !plan.Primary.IsUnknown() {
		am.Primary = plan.Primary.ValueBoolPointer()
	}

	if !plan.IpForwardingEnabled.IsNull() && !plan.IpForwardingEnabled.IsUnknown() {
		am.IpForwardingEnabled = plan.IpForwardingEnabled.ValueBoolPointer()
	}

	if !plan.Addresses.IsNull() && !plan.Addresses.IsUnknown() {
		addresses := make([]tfmodel.AddressSpecOrRefWithAttachments, 0)
		dAddresses := plan.Addresses.ElementsAs(ctx, &addresses, false)
		diags = append(diags, dAddresses...)
		if diags.HasError() {
			return nil, diags
		}

		am.Addresses = make([]model.AddressSpecOrRefWithAttachmentsRequest, 0, len(addresses))

		for _, entity := range addresses {
			tmp, d := AddressSpecOrRefWithAttachmentsTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Addresses = append(am.Addresses, *tmp)
		}
	}

	return &am, diags
}

func NetworkInterfaceSpecTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.NetworkInterfaceSpec) (*model.UpdateNetworkInterfaceSpecRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.NetworkInterfaceSpec{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateNetworkInterfaceSpecRequest

	if !plan.Name.Equal(state.Name) {
		if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
			am.Name.SetTo(plan.Name.ValueString())
		}
	}

	if !plan.Primary.Equal(state.Primary) {
		if !plan.Primary.IsNull() && !plan.Primary.IsUnknown() {
			am.Primary.SetTo(plan.Primary.ValueBool())
		}
	}

	if !plan.IpForwardingEnabled.Equal(state.IpForwardingEnabled) {
		if !plan.IpForwardingEnabled.IsNull() && !plan.IpForwardingEnabled.IsUnknown() {
			am.IpForwardingEnabled.SetTo(plan.IpForwardingEnabled.ValueBool())
		}
	}

	if !plan.Addresses.Equal(state.Addresses) {
		if !plan.Addresses.IsNull() && !plan.Addresses.IsUnknown() {
			addresses := make([]tfmodel.AddressSpecOrRefWithAttachments, 0)
			dAddresses := plan.Addresses.ElementsAs(ctx, &addresses, false)
			diags = append(diags, dAddresses...)
			if diags.HasError() {
				return nil, diags
			}

			addressesTmp := make([]model.UpdateAddressSpecOrRefWithAttachmentsRequest, 0, len(addresses))

			for _, entity := range addresses {
				stateEntity := tfmodel.AddressSpecOrRefWithAttachments{}
				tmp, d := AddressSpecOrRefWithAttachmentsTFToAPIUpdateRequestModel(ctx, &entity, &stateEntity)
				diags = append(diags, d...)
				if diags.HasError() {
					return nil, diags
				}
				addressesTmp = append(addressesTmp, *tmp)
			}
			am.Addresses.SetTo(addressesTmp)
		}
	}

	return &am, diags
}
