// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	"go.mws.cloud/go-sdk/service/compute/model"
	"go.mws.cloud/go-sdk/service/resources/references/compute"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/compute/model"
)

func SnapshotSourceAPIOptionalResponseToTFModel(ctx context.Context, am *model.SnapshotSourceOptionalResponse) (*tfmodel.SnapshotSource, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.SnapshotSource

	if val, ok := am.Disk.Get(); ok {
		diskTmp, d := SnapshotSourceDiskAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		diskTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.SnapshotSourceDisk).GetSchema().Attributes),
			*diskTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Disk = diskTfObject
	} else {
		t.Disk = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.SnapshotSourceDisk).GetSchema().Attributes))
	}

	return &t, diags
}

func SnapshotSourceTFToAPIRequestModel(ctx context.Context, plan *tfmodel.SnapshotSource) (*model.SnapshotSourceRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.SnapshotSourceRequest

	if !plan.Disk.IsNull() && !plan.Disk.IsUnknown() {
		diskPlan := tfmodel.SnapshotSourceDisk{}
		diskPlanDiag := plan.Disk.As(ctx, &diskPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, diskPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		diskTmp, diskDiag := SnapshotSourceDiskTFToAPIRequestModel(ctx, &diskPlan)
		diags = append(diags, diskDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Disk = diskTmp
	}

	return &am, diags
}

func SnapshotSourceTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.SnapshotSource) (*model.UpdateSnapshotSourceRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.SnapshotSource{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateSnapshotSourceRequest

	if !plan.Disk.Equal(state.Disk) {
		if !plan.Disk.IsNull() && !plan.Disk.IsUnknown() {
			diskPlan := tfmodel.SnapshotSourceDisk{}
			diskPlanDiag := plan.Disk.As(ctx, &diskPlan, basetypes.ObjectAsOptions{})
			diags = append(diags, diskPlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			diskState := tfmodel.SnapshotSourceDisk{}
			if !state.Disk.IsNull() && !state.Disk.IsUnknown() {
				diskStateDiag := state.Disk.As(ctx, &diskState, basetypes.ObjectAsOptions{})
				diags = append(diags, diskStateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			diskTmp, diskDiag := SnapshotSourceDiskTFToAPIUpdateRequestModel(ctx, &diskPlan, &diskState)
			diags = append(diags, diskDiag...)
			if diags.HasError() {
				return nil, diags
			}
			am.Disk.SetTo(*diskTmp)
		} else if plan.Disk.IsNull() {
			am.Disk.SetToNull()
		}
	}

	return &am, diags
}

func SnapshotSourceDiskAPIOptionalResponseToTFModel(ctx context.Context, am *model.SnapshotSourceDiskOptionalResponse) (*tfmodel.SnapshotSourceDisk, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.SnapshotSourceDisk

	t.Id = types.StringValue(am.Id.Path())

	return &t, diags
}

func SnapshotSourceDiskTFToAPIRequestModel(ctx context.Context, plan *tfmodel.SnapshotSourceDisk) (*model.SnapshotSourceDiskRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.SnapshotSourceDiskRequest

	if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
		idRef, err := compute.ParseDiskRef(ctx, plan.Id.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Id = idRef
	}

	return &am, diags
}

func SnapshotSourceDiskTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.SnapshotSourceDisk) (*model.UpdateSnapshotSourceDiskRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.SnapshotSourceDisk{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateSnapshotSourceDiskRequest

	if !plan.Id.Equal(state.Id) {
		if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
			idRef, err := compute.ParseDiskRef(ctx, plan.Id.ValueString())
			if err != nil {
				diags.AddError("reference parsing", err.Error())
				return nil, diags
			}
			am.Id.SetTo(idRef)
		}
	}

	return &am, diags
}
