// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/throughput"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	apimodel "go.mws.cloud/go-sdk/service/compute/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/compute/model"
)

func ThroughputAPIToTFModel(ctx context.Context, am *apimodel.Throughput) (tfmodel.Throughput, tfdiag.Diagnostics) {
	if am == nil {
		return tfmodel.Throughput{}, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.Throughput

	t = tfmodel.Throughput(types.StringValue(ptr.Value(am.RawValue())))

	return t, diags
}

func ThroughputTFToAPIModel(ctx context.Context, tm tfmodel.Throughput) (*apimodel.Throughput, tfdiag.Diagnostics) {
	var diags tfdiag.Diagnostics
	var am apimodel.Throughput

	var tmp = types.String(tm)
	t, err := throughput.ParseString(tmp.ValueString())
	if err != nil {
		diags.AddError("Throughput string parsing", err.Error())
		return nil, diags
	}

	am = apimodel.Throughput(t)

	return &am, diags
}
