// Code generated by mwsapigen, DO NOT EDIT.

package iam

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	ctxvalues "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/iam/client"
	resourcesdk "go.mws.cloud/go-sdk/service/iam/sdk"
	"go.mws.cloud/terraform-provider-mws/internal/cmp"
	"go.mws.cloud/terraform-provider-mws/internal/diag"
	provider "go.mws.cloud/terraform-provider-mws/internal/provider/public"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/iam/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/iam/model"
)

var (
	_ datasource.DataSource = &ServiceAccountDataSource{}
)

type ServiceAccountDataSource struct {
	sdk    *resourcesdk.ServiceAccount
	config *provider.Config
}

func NewServiceAccountDataSource() datasource.DataSource {
	return &ServiceAccountDataSource{}
}

func (m *ServiceAccountDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	tflog.Info(ctx, "ServiceAccountDataSource.Metadata")
	resp.TypeName = req.ProviderTypeName + "_iam_service_account"
}

func (m *ServiceAccountDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	tflog.Info(ctx, "ServiceAccountDataSource.Schema")
	resp.Schema = new(tfmodel.ServiceAccount).GetSchema()
	resp.Schema.Attributes["project"] = schema.StringAttribute{
		MarkdownDescription: `Путь к проекту.`,
		Optional:            true,
		Computed:            true,
	}
	resp.Schema.Attributes["service_account"] = schema.StringAttribute{
		Required: true,
	}
}

func (m *ServiceAccountDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	var err error
	tflog.Info(ctx, "ServiceAccountDataSource.Configure")
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*provider.Data)
	if !ok || providerData == nil {
		resp.Diagnostics.AddError("Internal Provider Error", "Unexpected type of req.ProviderData")
		return
	}

	m.config = providerData.Config

	m.sdk, err = resourcesdk.NewServiceAccount(ctx, providerData.SDK)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create SDK client for ServiceAccount",
			diag.FormatError(err),
		)
		return
	}
}

func (m *ServiceAccountDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	tflog.Info(ctx, "ServiceAccountDataSource.Read")

	var config tfmodel.ServiceAccountModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(config.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	config.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	apiRes, err := m.sdk.GetServiceAccount(
		ctx,
		client.GetServiceAccountRequest{
			Project:        config.ProjectParam.ValueString(),
			ServiceAccount: config.ServiceAccountParam.ValueString(),
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Get ServiceAccount",
			diag.FormatError(err),
		)
		return
	}

	tfRes, diags := conv.ServiceAccountAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "ServiceAccountDataSource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	config.ServiceAccount = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
