// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/rm"
	"go.mws.cloud/go-sdk/service/rm/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/rm/converter"
)

func TestZoneAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ZoneResponse{
		Spec: model.ZoneSpecResponse{
			Region: rm.NewMustRegionRef("regionID"),
		},
	}
	_, diags := conv.ZoneAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestZoneMetadataAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ZoneMetadataResponse{
		TypedResourceMetadataResponse: commonmodel.TypedResourceMetadataResponse{},
	}
	_, diags := conv.ZoneMetadataAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
