// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/rm/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/rm/converter"
)

func TestZoneAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.ZoneResponse{}
	_, diags := conv.ZoneAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestZoneMetadataAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.ZoneMetadataResponse{}
	_, diags := conv.ZoneMetadataAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
