// Code generated by mwsapigen, DO NOT EDIT.

package mkafka

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	tfpath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"go.mws.cloud/go-sdk/mws/wait"
	ctxvalues "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/mkafka/client"
	apimodel "go.mws.cloud/go-sdk/service/mkafka/model"
	resourcesdk "go.mws.cloud/go-sdk/service/mkafka/sdk"
	mkafkaref "go.mws.cloud/go-sdk/service/resources/references/mkafka"
	"go.mws.cloud/terraform-provider-mws/internal/cmp"
	"go.mws.cloud/terraform-provider-mws/internal/diag"
	provider "go.mws.cloud/terraform-provider-mws/internal/provider/public"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/model"
)

var (
	_ resource.Resource                = &ClusterUserResource{}
	_ resource.ResourceWithImportState = &ClusterUserResource{}
)

type ClusterUserResource struct {
	sdk    *resourcesdk.KafkaUser
	config *provider.Config
}

func NewClusterUserResource() resource.Resource {
	return &ClusterUserResource{}
}

func (m *ClusterUserResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	tflog.Info(ctx, "ClusterUserResource.Metadata")
	resp.TypeName = req.ProviderTypeName + "_mkafka_cluster_user"
}

func (m *ClusterUserResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	tflog.Info(ctx, "ClusterUserResource.Schema")
	resp.Schema = new(tfmodel.KafkaUser).GetSchema()
	resp.Schema.Attributes["cluster"] = schema.StringAttribute{
		MarkdownDescription: `Название или идентификатор кластера.`,
		Required:            true,
	}
	resp.Schema.Attributes["project"] = schema.StringAttribute{
		MarkdownDescription: `Путь к проекту`,
		Optional:            true,
		Computed:            true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}
	resp.Schema.Attributes["user"] = schema.StringAttribute{
		MarkdownDescription: `Пользователь кластера.`,
		Required:            true,
	}
	resp.Schema.Attributes["timeouts"] = timeouts.Attributes(ctx, timeouts.Opts{
		Create: true,
		Update: true,
		Delete: true,
	})
	resp.Schema.Attributes["id"] = schema.StringAttribute{
		Computed: true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}
}

func (m *ClusterUserResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	var err error
	tflog.Info(ctx, "ClusterUserResource.Configure")
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*provider.Data)
	if !ok || providerData == nil {
		resp.Diagnostics.AddError("Internal Provider Error", "Unexpected type of req.ProviderData")
		return
	}

	m.config = providerData.Config

	m.sdk, err = resourcesdk.NewKafkaUser(ctx, providerData.SDK)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create SDK client for ClusterUser",
			diag.FormatError(err),
		)
		return
	}
}

func (m *ClusterUserResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "ClusterUserResource.Create")

	var data tfmodel.ClusterUserModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var specPasswordVersion types.Int64

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Create(ctx, 3600*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "ClusterUserResource.Timeouts")
		return
	}

	body, diags := conv.KafkaUserTFToAPIRequestModel(ctx, &data.KafkaUser)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "ClusterUserResource.TFToAPI")
		return
	}

	body, diags = func(ctx context.Context, planApiRequest *apimodel.KafkaUserRequest) (*apimodel.KafkaUserRequest, tfdiag.Diagnostics) {

		var configData tfmodel.ClusterUserModel
		resp.Diagnostics.Append(req.Config.Get(ctx, &configData)...)
		if resp.Diagnostics.HasError() {
			return nil, resp.Diagnostics
		}

		configRequest, wdiags := conv.KafkaUserTFToAPIRequestModel(ctx, &configData.KafkaUser)
		if wdiags.HasError() {
			return nil, wdiags
		}

		resp.Diagnostics.Append(req.Plan.GetAttribute(ctx, tfpath.Root("password_version"), &specPasswordVersion)...)
		if resp.Diagnostics.HasError() {
			tflog.Debug(ctx, "ClusterUserResource.GetWriteOnlyAttributeFromConfig")
			return nil, resp.Diagnostics
		}
		if !specPasswordVersion.IsNull() && !specPasswordVersion.IsUnknown() {
			planApiRequest.Spec.Password = configRequest.Spec.Password
		}

		return planApiRequest, nil
	}(ctx, body)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "ClusterUserResource.GetWriteOnlyAttributesFromConfig")
		return
	}

	apiRes, err := m.sdk.CreateKafkaUser(
		ctx,
		client.UpsertKafkaUserRequest{
			Project: data.ProjectParam.ValueString(),
			Cluster: data.ClusterParam.ValueString(),
			User:    data.UserParam.ValueString(),
			Body:    *body,
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create ClusterUser",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Id.ID())

	tfRes, diags := conv.KafkaUserAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "ClusterUserResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.KafkaUser = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	if !specPasswordVersion.IsNull() && !specPasswordVersion.IsUnknown() {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, tfpath.Root("password_version"), specPasswordVersion)...)
	}
}

func (m *ClusterUserResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	tflog.Info(ctx, "ClusterUserResource.Read")

	var data tfmodel.ClusterUserModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var specPasswordVersion types.Int64

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	apiRes, err := m.sdk.GetKafkaUser(
		ctx,
		client.GetKafkaUserRequest{
			Project: data.ProjectParam.ValueString(),
			Cluster: data.ClusterParam.ValueString(),
			User:    data.UserParam.ValueString(),
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Get ClusterUser",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Id.ID())

	tfRes, diags := conv.KafkaUserAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "ClusterUserResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.KafkaUser = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	resp.Diagnostics.Append(req.State.GetAttribute(ctx, tfpath.Root("password_version"), &specPasswordVersion)...)
	if !specPasswordVersion.IsNull() && !specPasswordVersion.IsUnknown() {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, tfpath.Root("password_version"), specPasswordVersion)...)
	}
}

func (m *ClusterUserResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	tflog.Info(ctx, "ClusterUserResource.Update")

	var data tfmodel.ClusterUserModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var specPasswordVersion types.Int64

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Update(ctx, 3600*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "ClusterUserResource.Timeouts")
		return
	}

	body, diags := conv.KafkaUserTFToAPIRequestModel(ctx, &data.KafkaUser)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "ClusterUserResource.TFToAPI")
		return
	}

	body, diags = func(ctx context.Context, planApiRequest *apimodel.KafkaUserRequest) (*apimodel.KafkaUserRequest, tfdiag.Diagnostics) {

		var configData tfmodel.ClusterUserModel
		resp.Diagnostics.Append(req.Config.Get(ctx, &configData)...)
		if resp.Diagnostics.HasError() {
			return nil, resp.Diagnostics
		}

		configRequest, wdiags := conv.KafkaUserTFToAPIRequestModel(ctx, &configData.KafkaUser)
		if wdiags.HasError() {
			return nil, wdiags
		}

		resp.Diagnostics.Append(req.Plan.GetAttribute(ctx, tfpath.Root("password_version"), &specPasswordVersion)...)
		if resp.Diagnostics.HasError() {
			tflog.Debug(ctx, "ClusterUserResource.GetWriteOnlyAttributeFromConfig")
			return nil, resp.Diagnostics
		}
		if !specPasswordVersion.IsNull() && !specPasswordVersion.IsUnknown() {
			planApiRequest.Spec.Password = configRequest.Spec.Password
		}

		return planApiRequest, nil
	}(ctx, body)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "ClusterUserResource.GetWriteOnlyAttributesFromConfig")
		return
	}

	apiRes, err := m.sdk.UpdateKafkaUser(
		ctx,
		client.UpdateKafkaUserRequest{
			Project: data.ProjectParam.ValueString(),
			Cluster: data.ClusterParam.ValueString(),
			User:    data.UserParam.ValueString(),
			Body:    body.AsUpdateModel(),
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Update ClusterUser",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Id.ID())

	tfRes, diags := conv.KafkaUserAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "ClusterUserResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.KafkaUser = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	if !specPasswordVersion.IsNull() && !specPasswordVersion.IsUnknown() {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, tfpath.Root("password_version"), specPasswordVersion)...)
	}
}

func (m *ClusterUserResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	tflog.Info(ctx, "ClusterUserResource.Delete")

	var data tfmodel.ClusterUserModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Delete(ctx, 3600*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "ClusterUserResource.Timeouts")
		return
	}

	err := m.sdk.DeleteKafkaUser(
		ctx,
		client.DeleteKafkaUserRequest{
			Project: data.ProjectParam.ValueString(),
			Cluster: data.ClusterParam.ValueString(),
			User:    data.UserParam.ValueString(),
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Delete ClusterUser",
			diag.FormatError(err),
		)
		return
	}
}

func (m *ClusterUserResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Info(ctx, "ClusterUserResource.ImportState")

	var data tfmodel.ClusterUserModel

	ref, err := mkafkaref.ParseKafkaClusterUserRef(ctx, req.ID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Parse reference for ClusterUser",
			diag.FormatError(err),
		)
		return
	}

	apiRes, err := m.sdk.GetKafkaUser(
		ctx,
		client.GetKafkaUserRequest{
			Project: ref.GetProject(),
			Cluster: ref.GetCluster(),
			User:    ref.GetUser(),
		})
	if err != nil {
		resp.Diagnostics.AddError(
			"Get ClusterUser",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Id.ID())

	tfRes, diags := conv.KafkaUserAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "ClusterUserResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.KafkaUser = *tfRes

	data.ProjectParam = types.StringValue(ref.GetProject())
	data.ClusterParam = types.StringValue(ref.GetCluster())
	data.UserParam = types.StringValue(ref.GetUser())

	var rwTimeouts timeouts.Value
	resp.Diagnostics.Append(resp.State.GetAttribute(ctx, tfpath.Root("timeouts"), &rwTimeouts)...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "ClusterUserResource.timeouts.GetAttribute")
		return
	}
	data.Timeouts = rwTimeouts

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
