// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/mpostgres/model"
)

func BackupTriggerAPIToTFModel(ctx context.Context, am *model.BackupTrigger) (tfmodel.BackupTrigger, tfdiag.Diagnostics) {
	if am == nil {
		return tfmodel.BackupTrigger{}, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.BackupTrigger

	t = tfmodel.BackupTrigger(types.StringValue(string(*am)))

	return t, diags
}
