// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	apimodel "go.mws.cloud/go-sdk/service/mpostgres/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/mpostgres/model"
)

func PostgresNetworkAddressAPIResponseToTFModel(ctx context.Context, am *apimodel.PostgresNetworkAddressResponse) (*tfmodel.PostgresNetworkAddress, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.PostgresNetworkAddress

	if am.Ref != nil {
		t.Ref = types.StringPointerValue(ptr.Get(am.Ref.Path()))
	} else {
		t.Ref = types.StringNull()
	}

	if am.Spec != nil {
		specTmp, d := PostgresNetworkAddressSpecAPIResponseToTFModel(ctx, am.Spec)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		specTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.PostgresNetworkAddressSpec).GetSchema().Attributes),
			*specTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Spec = specTfObject
	} else {
		t.Spec = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.PostgresNetworkAddressSpec).GetSchema().Attributes))
	}

	if am.ExternalAccess != nil {
		externalAccessTmp, d := PostgresExternalAccessSpecAPIResponseToTFModel(ctx, am.ExternalAccess)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		externalAccessTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.PostgresExternalAccessSpec).GetSchema().Attributes),
			*externalAccessTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.ExternalAccess = externalAccessTfObject
	} else {
		t.ExternalAccess = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.PostgresExternalAccessSpec).GetSchema().Attributes))
	}

	return &t, diags
}

func PostgresNetworkAddressTFToAPIRequestModel(ctx context.Context, plan *tfmodel.PostgresNetworkAddress) (*apimodel.PostgresNetworkAddressRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.PostgresNetworkAddressRequest

	if !plan.Ref.IsNull() && !plan.Ref.IsUnknown() {
		refRef, err := vpc.ParseAddressRef(ctx, plan.Ref.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Ref = &refRef
	}

	if !plan.Spec.IsNull() && !plan.Spec.IsUnknown() {
		specPlan := tfmodel.PostgresNetworkAddressSpec{}
		specPlanDiag := plan.Spec.As(ctx, &specPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, specPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		specTmp, specDiag := PostgresNetworkAddressSpecTFToAPIRequestModel(ctx, &specPlan)
		diags = append(diags, specDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec = specTmp
	}

	if !plan.ExternalAccess.IsNull() && !plan.ExternalAccess.IsUnknown() {
		externalAccessPlan := tfmodel.PostgresExternalAccessSpec{}
		externalAccessPlanDiag := plan.ExternalAccess.As(ctx, &externalAccessPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, externalAccessPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		externalAccessTmp, externalAccessDiag := PostgresExternalAccessSpecTFToAPIRequestModel(ctx, &externalAccessPlan)
		diags = append(diags, externalAccessDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.ExternalAccess = externalAccessTmp
	}

	return &am, diags
}
