// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"
	"time"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	apimodel "go.mws.cloud/go-sdk/service/mpostgres/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/mpostgres/model"
)

func PostgresClusterUserAPIResponseToTFModel(ctx context.Context, am *apimodel.PostgresClusterUserResponse) (*tfmodel.PostgresClusterUser, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.PostgresClusterUser

	if am.Kind != nil {
		t.Kind = types.StringPointerValue(am.Kind)
	} else {
		t.Kind = types.StringNull()
	}

	if am.Metadata != nil {
		metadataTmp, d := PostgresClusterUserMetadataAPIResponseToTFModel(ctx, am.Metadata)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		metadataTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.PostgresClusterUserMetadata).GetSchema().Attributes),
			*metadataTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Metadata = metadataTfObject
	} else {
		t.Metadata = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.PostgresClusterUserMetadata).GetSchema().Attributes))
	}

	if am.Status != nil {
		statusTmp, d := PostgresClusterUserStatusAPIResponseToTFModel(ctx, am.Status)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		statusTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.PostgresClusterUserStatus).GetSchema().Attributes),
			*statusTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Status = statusTfObject
	} else {
		t.Status = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.PostgresClusterUserStatus).GetSchema().Attributes))
	}

	if am.Spec.Role != nil {
		roleTmp, d := PostgresUserRoleAPIToTFModel(ctx, am.Spec.Role)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Role = roleTmp
	} else {
		t.Role = types.StringNull()
	}

	if am.Spec.AdditionalRoles != nil {
		additionalRoles := make([]tfmodel.PostgresUserAdditionalRole, 0, len(am.Spec.AdditionalRoles))

		for _, entity := range am.Spec.AdditionalRoles {
			tmp, d := PostgresUserAdditionalRoleAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			additionalRoles = append(additionalRoles, *tmp)
		}

		additionalRolesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.PostgresUserAdditionalRole).GetSchema().Attributes),
		}, additionalRoles)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.AdditionalRoles = additionalRolesList
	} else {
		t.AdditionalRoles = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.PostgresUserAdditionalRole).GetSchema().Attributes),
		})
	}

	if am.Spec.AccessControlPolicy != nil {
		accessControlPolicyTmp, d := PostgresUserAccessControlPolicyAPIToTFModel(ctx, am.Spec.AccessControlPolicy)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.AccessControlPolicy = accessControlPolicyTmp
	} else {
		t.AccessControlPolicy = types.StringNull()
	}

	return &t, diags
}

func PostgresClusterUserTFToAPIRequestModel(ctx context.Context, plan *tfmodel.PostgresClusterUser) (*apimodel.PostgresClusterUserRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.PostgresClusterUserRequest

	if !plan.Metadata.IsNull() && !plan.Metadata.IsUnknown() {
		metadataPlan := tfmodel.PostgresClusterUserMetadata{}
		metadataPlanDiag := plan.Metadata.As(ctx, &metadataPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, metadataPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		metadataTmp, metadataDiag := PostgresClusterUserMetadataTFToAPIRequestModel(ctx, &metadataPlan)
		diags = append(diags, metadataDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Metadata = metadataTmp
	}

	if !plan.Role.IsNull() && !plan.Role.IsUnknown() {
		roleTmp, roleDiag := PostgresUserRoleTFToAPIModel(ctx, plan.Role)
		diags = append(diags, roleDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.Role = roleTmp
	}

	if !plan.AdditionalRoles.IsNull() && !plan.AdditionalRoles.IsUnknown() {
		additionalRoles := make([]tfmodel.PostgresUserAdditionalRole, 0)
		dAdditionalRoles := plan.AdditionalRoles.ElementsAs(ctx, &additionalRoles, false)
		diags = append(diags, dAdditionalRoles...)
		if diags.HasError() {
			return nil, diags
		}

		am.Spec.AdditionalRoles = make([]apimodel.PostgresUserAdditionalRoleRequest, 0, len(additionalRoles))

		for _, entity := range additionalRoles {
			tmp, d := PostgresUserAdditionalRoleTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Spec.AdditionalRoles = append(am.Spec.AdditionalRoles, *tmp)
		}
	}

	if !plan.AccessControlPolicy.IsNull() && !plan.AccessControlPolicy.IsUnknown() {
		accessControlPolicyTmp, accessControlPolicyDiag := PostgresUserAccessControlPolicyTFToAPIModel(ctx, plan.AccessControlPolicy)
		diags = append(diags, accessControlPolicyDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.AccessControlPolicy = accessControlPolicyTmp
	}

	return &am, diags
}

func PostgresClusterUserMetadataAPIResponseToTFModel(ctx context.Context, am *apimodel.PostgresClusterUserMetadataResponse) (*tfmodel.PostgresClusterUserMetadata, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.PostgresClusterUserMetadata

	if am.DisplayName != nil {
		t.DisplayName = types.StringPointerValue(am.DisplayName)
	} else {
		t.DisplayName = types.StringNull()
	}

	if am.CreateTime != nil {
		t.CreateTime = types.StringPointerValue(ptr.Get(am.CreateTime.Format(time.RFC3339)))
	} else {
		t.CreateTime = types.StringNull()
	}

	if am.DeleteTime != nil {
		t.DeleteTime = types.StringPointerValue(ptr.Get(am.DeleteTime.Format(time.RFC3339)))
	} else {
		t.DeleteTime = types.StringNull()
	}

	if am.PurgeTime != nil {
		t.PurgeTime = types.StringPointerValue(ptr.Get(am.PurgeTime.Format(time.RFC3339)))
	} else {
		t.PurgeTime = types.StringNull()
	}

	if am.Usages != nil {
		usages := make([]tfcommon.TypedUsage, 0, len(am.Usages))

		for _, entity := range am.Usages {
			tmp, d := commonconv.TypedUsageAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			usages = append(usages, *tmp)
		}

		usagesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.TypedUsage).GetSchema().Attributes),
		}, usages)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Usages = usagesList
	} else {
		t.Usages = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.TypedUsage).GetSchema().Attributes),
		})
	}

	if am.Description != nil {
		t.Description = types.StringPointerValue(am.Description)
	} else {
		t.Description = types.StringNull()
	}

	if am.Id != nil {
		t.Id = types.StringPointerValue(ptr.Get(am.Id.ID()))
	} else {
		t.Id = types.StringNull()
	}

	return &t, diags
}

func PostgresClusterUserMetadataTFToAPIRequestModel(ctx context.Context, plan *tfmodel.PostgresClusterUserMetadata) (*apimodel.PostgresClusterUserMetadataRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.PostgresClusterUserMetadataRequest

	if !plan.DisplayName.IsNull() && !plan.DisplayName.IsUnknown() {
		am.DisplayName = plan.DisplayName.ValueStringPointer()
	}

	if !plan.Usages.IsNull() && !plan.Usages.IsUnknown() {
		usages := make([]tfcommon.TypedUsage, 0)
		dUsages := plan.Usages.ElementsAs(ctx, &usages, false)
		diags = append(diags, dUsages...)
		if diags.HasError() {
			return nil, diags
		}

		am.Usages = make([]commonapimodel.TypedUsageRequest, 0, len(usages))

		for _, entity := range usages {
			tmp, d := commonconv.TypedUsageTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Usages = append(am.Usages, *tmp)
		}
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		am.Description = plan.Description.ValueStringPointer()
	}

	return &am, diags
}
