// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type KafkaEndpointBrokerAddressDnsStatus struct {
	Name types.String `tfsdk:"name"`
}

func (s *KafkaEndpointBrokerAddressDnsStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описание DNS-имен, назначенных адресу брокера в пользовательской сети.`,
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}
