// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	apimodel "go.mws.cloud/go-sdk/service/compute/model"
	"go.mws.cloud/go-sdk/service/resources/references/compute"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/compute/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/compute/model"
)

func TestDiskBackupSourceAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.DiskBackupSourceOptionalResponse{}
	_, diags := conv.DiskBackupSourceAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestDiskBackupSourceOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.DiskBackupSourceRequest{}

	emptyApiModelResponse, err := apimodel.DiskBackupSourceRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.DiskBackupSourceAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.DiskBackupSourceTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.DiskBackupSourceRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateDiskBackupSourceRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.DiskBackupSource
	var stateTfModel tfmodel.DiskBackupSource
	stateTfModel.Disk = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfmodel.DiskBackupSourceDisk).GetSchema().Attributes))

	expectedUpdateModel := &apimodel.UpdateDiskBackupSourceRequest{
		Disk: optional.OptionalNil[apimodel.UpdateDiskBackupSourceDiskRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.DiskBackupSourceTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}

func TestDiskBackupSourceDiskAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.DiskBackupSourceDiskOptionalResponse{}
	_, diags := conv.DiskBackupSourceDiskAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestDiskBackupSourceDiskOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.DiskBackupSourceDiskRequest{
		Id: compute.NewMustDiskRef("projectID", "diskID"),
	}

	emptyApiModelResponse, err := apimodel.DiskBackupSourceDiskRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.DiskBackupSourceDiskAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.DiskBackupSourceDiskTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.DiskBackupSourceDiskRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateDiskBackupSourceDiskRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.DiskBackupSourceDisk
	var stateTfModel tfmodel.DiskBackupSourceDisk

	expectedUpdateModel := &apimodel.UpdateDiskBackupSourceDiskRequest{}

	result, diags := conv.DiskBackupSourceDiskTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
