// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	"go.mws.cloud/go-sdk/service/compute/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/compute/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/compute/model"
)

func TestOsSpecAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.OsSpecOptionalResponse{}
	_, diags := conv.OsSpecAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestOsSpecOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.OsSpecRequest{}

	emptyApiModelResponse, err := model.OsSpecRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.OsSpecAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.OsSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.OsSpecRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateOsSpecRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.OsSpec
	var stateTfModel tfmodel.OsSpec
	stateTfModel.Metadata = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfmodel.OsSpecMetadata).GetSchema().Attributes))

	expectedUpdateModel := &model.UpdateOsSpecRequest{
		Metadata: optional.OptionalNil[model.UpdateOsSpecMetadataRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.OsSpecTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}

func TestOsSpecMetadataAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.OsSpecMetadataOptionalResponse{}
	_, diags := conv.OsSpecMetadataAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestOsSpecMetadataOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.OsSpecMetadataRequest{}

	emptyApiModelResponse, err := model.OsSpecMetadataRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.OsSpecMetadataAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.OsSpecMetadataTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.OsSpecMetadataRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateOsSpecMetadataRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.OsSpecMetadata
	var stateTfModel tfmodel.OsSpecMetadata

	expectedUpdateModel := &model.UpdateOsSpecMetadataRequest{}

	result, diags := conv.OsSpecMetadataTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
