// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"
	"time"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	apimodel "go.mws.cloud/go-sdk/service/mpostgres/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/model"
)

func PostgresUserAdditionalRoleAPIResponseToTFModel(ctx context.Context, am *apimodel.PostgresUserAdditionalRoleResponse) (*tfmodel.PostgresUserAdditionalRole, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.PostgresUserAdditionalRole

	if am.Name != nil {
		t.Name = types.StringPointerValue(ptr.Get(string(*am.Name)))
	} else {
		t.Name = types.StringNull()
	}

	if am.ExpiresAt != nil {
		t.ExpiresAt = types.StringPointerValue(ptr.Get(am.ExpiresAt.Format(time.RFC3339)))
	} else {
		t.ExpiresAt = types.StringNull()
	}

	return &t, diags
}

func PostgresUserAdditionalRoleTFToAPIRequestModel(ctx context.Context, tm *tfmodel.PostgresUserAdditionalRole) (*apimodel.PostgresUserAdditionalRoleRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.PostgresUserAdditionalRoleRequest

	if !tm.Name.IsNull() && !tm.Name.IsUnknown() {
		am.Name = ptr.Get(apimodel.PostgresUserAdditionalRoleNameRequest(tm.Name.ValueString()))
	}

	if !tm.ExpiresAt.IsNull() && !tm.ExpiresAt.IsUnknown() {
		tmpExpiresAt, err := time.Parse(time.RFC3339, tm.ExpiresAt.ValueString())
		if err != nil {
			diags.AddError("time string parsing", err.Error())
			return nil, diags
		}
		am.ExpiresAt = &tmpExpiresAt
	}

	return &am, diags
}
