// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"
	"time"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	common "go.mws.cloud/go-sdk/service/common/model"
	apimodel "go.mws.cloud/go-sdk/service/mpostgres/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/model"
)

func PostgresBackupAPIResponseToTFModel(ctx context.Context, am *apimodel.PostgresBackupResponse) (*tfmodel.PostgresBackup, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.PostgresBackup

	if am.Kind != nil {
		t.Kind = types.StringPointerValue(am.Kind)
	} else {
		t.Kind = types.StringNull()
	}

	if am.Metadata != nil {
		metadataTmp, d := PostgresBackupMetadataAPIResponseToTFModel(ctx, am.Metadata)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		metadataTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.PostgresBackupMetadata).GetSchema().Attributes),
			*metadataTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Metadata = metadataTfObject
	} else {
		t.Metadata = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.PostgresBackupMetadata).GetSchema().Attributes))
	}

	if am.Status != nil {
		statusTmp, d := PostgresBackupStatusAPIResponseToTFModel(ctx, am.Status)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		statusTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.PostgresBackupStatus).GetSchema().Attributes),
			*statusTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Status = statusTfObject
	} else {
		t.Status = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.PostgresBackupStatus).GetSchema().Attributes))
	}

	return &t, diags
}

func PostgresBackupTFToAPIRequestModel(ctx context.Context, tm *tfmodel.PostgresBackup) (*apimodel.PostgresBackupRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.PostgresBackupRequest

	if !tm.Metadata.IsNull() && !tm.Metadata.IsUnknown() {
		metadataTfModel := tfmodel.PostgresBackupMetadata{}
		metadataDiag := tm.Metadata.As(ctx, &metadataTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, metadataDiag...)
		if diags.HasError() {
			return nil, diags
		}

		metadataTmp, metadataDiag := PostgresBackupMetadataTFToAPIRequestModel(ctx, &metadataTfModel)
		diags = append(diags, metadataDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Metadata = metadataTmp
	}

	return &am, diags
}

func PostgresBackupMetadataAPIResponseToTFModel(ctx context.Context, am *apimodel.PostgresBackupMetadataResponse) (*tfmodel.PostgresBackupMetadata, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.PostgresBackupMetadata

	if am.DisplayName != nil {
		t.DisplayName = types.StringPointerValue(am.DisplayName)
	} else {
		t.DisplayName = types.StringNull()
	}

	if am.CreateTime != nil {
		t.CreateTime = types.StringPointerValue(ptr.Get(am.CreateTime.Format(time.RFC3339)))
	} else {
		t.CreateTime = types.StringNull()
	}

	if am.DeleteTime != nil {
		t.DeleteTime = types.StringPointerValue(ptr.Get(am.DeleteTime.Format(time.RFC3339)))
	} else {
		t.DeleteTime = types.StringNull()
	}

	if am.PurgeTime != nil {
		t.PurgeTime = types.StringPointerValue(ptr.Get(am.PurgeTime.Format(time.RFC3339)))
	} else {
		t.PurgeTime = types.StringNull()
	}

	if am.Usages != nil {
		usages := make([]tfcommon.TypedUsage, 0, len(am.Usages))

		for _, entity := range am.Usages {
			tmp, d := commonconv.TypedUsageAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			usages = append(usages, *tmp)
		}

		usagesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.TypedUsage).GetSchema().Attributes),
		}, usages)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Usages = usagesList
	} else {
		t.Usages = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.TypedUsage).GetSchema().Attributes),
		})
	}

	if am.Description != nil {
		t.Description = types.StringPointerValue(am.Description)
	} else {
		t.Description = types.StringNull()
	}

	if am.Id != nil {
		t.Id = types.StringPointerValue(ptr.Get(am.Id.ID()))
	} else {
		t.Id = types.StringNull()
	}

	return &t, diags
}

func PostgresBackupMetadataTFToAPIRequestModel(ctx context.Context, tm *tfmodel.PostgresBackupMetadata) (*apimodel.PostgresBackupMetadataRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.PostgresBackupMetadataRequest

	if !tm.DisplayName.IsNull() && !tm.DisplayName.IsUnknown() {
		am.DisplayName = tm.DisplayName.ValueStringPointer()
	}

	if !tm.Usages.IsNull() && !tm.Usages.IsUnknown() {
		usages := make([]tfcommon.TypedUsage, 0)
		dUsages := tm.Usages.ElementsAs(ctx, &usages, false)
		diags = append(diags, dUsages...)
		if diags.HasError() {
			return nil, diags
		}
		am.Usages = make([]common.TypedUsageRequest, 0, len(usages))

		for _, entity := range usages {
			tmp, d := commonconv.TypedUsageTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Usages = append(am.Usages, *tmp)
		}
	}

	if !tm.Description.IsNull() && !tm.Description.IsUnknown() {
		am.Description = tm.Description.ValueStringPointer()
	}

	return &am, diags
}

func PostgresBackupSpecAPIResponseToTFModel(ctx context.Context, am *apimodel.PostgresBackupSpecResponse) (*tfmodel.PostgresBackupSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.PostgresBackupSpec

	return &t, diags
}

func PostgresBackupSpecTFToAPIRequestModel(ctx context.Context, tm *tfmodel.PostgresBackupSpec) (*apimodel.PostgresBackupSpecRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.PostgresBackupSpecRequest

	return &am, diags
}
