// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	apimodel "go.mws.cloud/go-sdk/service/mpostgres/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/model"
)

func PostgresClusterBackupDailyAPIResponseToTFModel(ctx context.Context, am *apimodel.PostgresClusterBackupDailyResponse) (*tfmodel.PostgresClusterBackupDaily, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.PostgresClusterBackupDaily

	if am.Hour != nil {
		t.Hour = types.Int64PointerValue(ptr.Get(int64(*am.Hour)))
	} else {
		t.Hour = types.Int64Null()
	}

	return &t, diags
}

func PostgresClusterBackupDailyTFToAPIRequestModel(ctx context.Context, tm *tfmodel.PostgresClusterBackupDaily) (*apimodel.PostgresClusterBackupDailyRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.PostgresClusterBackupDailyRequest

	if !tm.Hour.IsNull() && !tm.Hour.IsUnknown() {
		am.Hour = ptr.Get(int(tm.Hour.ValueInt64()))
	}

	return &am, diags
}
