// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AuthorizedKeyModel struct {
	AuthorizedKeyParam  types.String `tfsdk:"authorized_key"`
	ProjectParam        types.String `tfsdk:"project"`
	ServiceAccountParam types.String `tfsdk:"service_account"`
	AuthorizedKey
}
