// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

type AddressStatus struct {
	tfcommon.ResourceStatus
	IpAddress types.String `tfsdk:"ip_address"`
}

func (s *AddressStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Статус адреса.`,
		Attributes: map[string]schema.Attribute{
			"ready": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.ResourceStatusReady).GetSchema().Attributes,
				MarkdownDescription: `Информация о статусе реконсиляции`,
				Computed:            true,
			},
			"ip_address": schema.StringAttribute{
				MarkdownDescription: `Присвоенный адрес. Совпадает с запрошенным ipAddress из спецификации, если последний указан при создании адреса.`,
				Computed:            true,
			},
		},
	}
}
