// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	localobjectplanmodifier "go.mws.cloud/terraform-provider-mws/internal/planmodifier/objectplanmodifier"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

type EgressNat struct {
	Kind           types.String `tfsdk:"kind"`
	Metadata       types.Object `tfsdk:"metadata"`
	Status         types.Object `tfsdk:"status"`
	Internal       types.Object `tfsdk:"internal"`
	External       types.Object `tfsdk:"external"`
	PortAllocation types.Object `tfsdk:"port_allocation"`
}

func (s *EgressNat) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описывает Egress (Many-to-Many) NAT-шлюз.`,
		Attributes: map[string]schema.Attribute{
			"kind": schema.StringAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes,
				MarkdownDescription: `Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров.`,
				Computed:            true,
				Optional:            true,
			},
			"status": schema.SingleNestedAttribute{
				Attributes:          new(EgressNatStatus).GetSchema().Attributes,
				MarkdownDescription: `Описывает статус Egress (Many-to-Many) NAT-шлюза.`,
				Computed:            true,
			},
			"internal": schema.SingleNestedAttribute{
				Attributes:          new(EgressNatSpecInternal).GetSchema().Attributes,
				MarkdownDescription: `Группирующий элемент для всего, что касается внутренних ресурсов.`,
				Required:            true,
			},
			"external": schema.SingleNestedAttribute{
				Attributes:          new(EgressNatSpecExternal).GetSchema().Attributes,
				MarkdownDescription: `Группирующий элемент для всего, что касается внешней части (ресурсов, доступных извне).`,
				Required:            true,
			},
			"port_allocation": schema.SingleNestedAttribute{
				Attributes:          new(EgressNatSpecPortAllocation).GetSchema().Attributes,
				MarkdownDescription: `Описывает настройки управления портами.`,
				Optional:            true,
				PlanModifiers: []planmodifier.Object{
					localobjectplanmodifier.RequiresReplaceIfRemoved(),
				},
			},
		},
	}
}
