// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ResourceAddressSpec struct {
	Subnet    types.String `tfsdk:"subnet"`
	IpAddress types.String `tfsdk:"ip_address"`
	Dns       types.List   `tfsdk:"dns"`
}

func (s *ResourceAddressSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Спецификация внутреннего адреса.`,
		Attributes: map[string]schema.Attribute{
			"subnet": schema.StringAttribute{
				MarkdownDescription: `Подсеть облачной сети к которой принадлежит адрес. В случае приватного адреса, он всегда принадлежит к некоторой подсети внутри облачной сети.`,
				Required:            true,
			},
			"ip_address": schema.StringAttribute{
				MarkdownDescription: `Значение IP адреса.`,
				Optional:            true,
			},
			"dns": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: new(VpcAddressDnsSpec).GetSchema().Attributes,
				},
				Optional: true,
			},
		},
	}
}
