// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ImageModel struct {
	ProjectParam types.String `tfsdk:"project"`
	ImageParam   types.String `tfsdk:"image"`
	Image
}
