// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SnapshotModel struct {
	ProjectParam  types.String `tfsdk:"project"`
	SnapshotParam types.String `tfsdk:"snapshot"`
	Snapshot
}
