// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type StorageSpec struct {
	Disks      types.List `tfsdk:"disks"`
	LocalDisks types.List `tfsdk:"local_disks"`
}

func (s *StorageSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"disks": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: new(StorageDiskSpecOrRefWithAttachments).GetSchema().Attributes,
				},
				Computed: true,
			},
			"local_disks": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: new(StorageLocalDiskSpec).GetSchema().Attributes,
				},
				Computed: true,
			},
		},
	}
}
