// Code generated by mwsapigen, DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	ctxvalues "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/vpc/client"
	resourcesdk "go.mws.cloud/go-sdk/service/vpc/sdk"
	"go.mws.cloud/terraform-provider-mws/internal/cmp"
	"go.mws.cloud/terraform-provider-mws/internal/diag"
	provider "go.mws.cloud/terraform-provider-mws/internal/provider/public"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/vpc/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/vpc/model"
)

var (
	_ datasource.DataSource = &SubnetDataSource{}
)

type SubnetDataSource struct {
	sdk    *resourcesdk.Subnet
	config *provider.Config
}

type SubnetModel struct {
	NetworkParam types.String `tfsdk:"network"`
	ProjectParam types.String `tfsdk:"project"`
	SubnetParam  types.String `tfsdk:"subnet"`
	tfmodel.Subnet
}

func NewSubnetDataSource() datasource.DataSource {
	return &SubnetDataSource{}
}

func (m *SubnetDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	tflog.Info(ctx, "SubnetDataSource.Metadata")
	resp.TypeName = req.ProviderTypeName + "_vpc_subnet"
}

func (m *SubnetDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	tflog.Info(ctx, "SubnetDataSource.Schema")
	resp.Schema = new(tfmodel.Subnet).GetSchema()
	resp.Schema.Attributes["network"] = schema.StringAttribute{
		MarkdownDescription: `Имя сети`,
		Required:            true,
	}
	resp.Schema.Attributes["project"] = schema.StringAttribute{
		MarkdownDescription: `Путь к проекту`,
		Optional:            true,
		Computed:            true,
	}
	resp.Schema.Attributes["subnet"] = schema.StringAttribute{
		MarkdownDescription: `Имя подсети`,
		Required:            true,
	}
}

func (m *SubnetDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	var err error
	tflog.Info(ctx, "SubnetDataSource.Configure")
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*provider.Data)
	if !ok || providerData == nil {
		resp.Diagnostics.AddError("Internal Provider Error", "Unexpected type of req.ProviderData")
		return
	}

	m.config = providerData.Config

	m.sdk, err = resourcesdk.NewSubnet(ctx, providerData.SDK)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create SDK client for Subnet",
			diag.FormatError(err),
		)
		return
	}
}

func (m *SubnetDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	tflog.Info(ctx, "SubnetDataSource.Read")
	var data SubnetModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	apiRes, err := m.sdk.GetSubnet(
		ctx,
		client.GetSubnetRequest{
			Project: data.ProjectParam.ValueString(),
			Network: data.NetworkParam.ValueString(),
			Subnet:  data.SubnetParam.ValueString(),
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Get Subnet",
			diag.FormatError(err),
		)
		return
	}

	tfRes, diags := conv.SubnetAPIOptionalResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "SubnetDataSource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.Subnet = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
