// Code generated by mwsapigen, DO NOT EDIT.

package mpostgres

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"go.mws.cloud/go-sdk/mws/wait"
	ctxvalues "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/mpostgres/client"
	resourcesdk "go.mws.cloud/go-sdk/service/mpostgres/sdk"
	mpostgresref "go.mws.cloud/go-sdk/service/resources/references/mpostgres"
	"go.mws.cloud/terraform-provider-mws/internal/cmp"
	"go.mws.cloud/terraform-provider-mws/internal/diag"
	provider "go.mws.cloud/terraform-provider-mws/internal/provider/public"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/model"
)

var (
	_ resource.Resource                = &BackupResource{}
	_ resource.ResourceWithImportState = &BackupResource{}
)

type BackupResource struct {
	sdk    *resourcesdk.PostgresBackup
	config *provider.Config
}

type BackupModel struct {
	BackupParam  types.String   `tfsdk:"backup"`
	ClusterParam types.String   `tfsdk:"cluster"`
	ProjectParam types.String   `tfsdk:"project"`
	Timeouts     timeouts.Value `tfsdk:"timeouts"`
	ID           types.String   `tfsdk:"id"`
	tfmodel.PostgresBackup
}

func NewBackupResource() resource.Resource {
	return &BackupResource{}
}

func (m *BackupResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	tflog.Info(ctx, "BackupResource.Metadata")
	resp.TypeName = req.ProviderTypeName + "_mpostgres_backup"
}

func (m *BackupResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	tflog.Info(ctx, "BackupResource.Schema")
	resp.Schema = new(tfmodel.PostgresBackup).GetSchema()
	resp.Schema.Attributes["backup"] = schema.StringAttribute{
		MarkdownDescription: `Backup базы данных.`,
		Required:            true,
	}
	resp.Schema.Attributes["cluster"] = schema.StringAttribute{
		MarkdownDescription: `Название или идентификатор кластера.`,
		Required:            true,
	}
	resp.Schema.Attributes["project"] = schema.StringAttribute{
		MarkdownDescription: `Путь к проекту`,
		Optional:            true,
		Computed:            true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}
	resp.Schema.Attributes["timeouts"] = timeouts.Attributes(ctx, timeouts.Opts{
		Create: true,
		Update: true,
		Delete: true,
	})
	resp.Schema.Attributes["id"] = schema.StringAttribute{
		Computed: true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}
}

func (m *BackupResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	var err error
	tflog.Info(ctx, "BackupResource.Configure")
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*provider.Data)
	if !ok || providerData == nil {
		resp.Diagnostics.AddError("Internal Provider Error", "Unexpected type of req.ProviderData")
		return
	}

	m.config = providerData.Config

	m.sdk, err = resourcesdk.NewPostgresBackup(ctx, providerData.SDK)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create SDK client for Backup",
			diag.FormatError(err),
		)
		return
	}
}

func (m *BackupResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "BackupResource.Create")
	var data BackupModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Create(ctx, 1800*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "BackupResource.Timeouts")
		return
	}

	bodyRequest, diags := conv.PostgresBackupTFToAPIRequestModel(ctx, &data.PostgresBackup)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "BackupResource.TFToAPI")
		return
	}

	apiRes, err := m.sdk.CreatePostgresBackup(
		ctx,
		client.UpsertPostgresBackupRequest{
			Project: data.ProjectParam.ValueString(),
			Cluster: data.ClusterParam.ValueString(),
			Backup:  data.BackupParam.ValueString(),
			Body:    *bodyRequest,
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create Backup",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Id.ID())

	tfRes, diags := conv.PostgresBackupAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "BackupResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.PostgresBackup = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (m *BackupResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	tflog.Info(ctx, "BackupResource.Read")
	var data BackupModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	apiRes, err := m.sdk.GetPostgresBackup(
		ctx,
		client.GetPostgresBackupRequest{
			Project: data.ProjectParam.ValueString(),
			Cluster: data.ClusterParam.ValueString(),
			Backup:  data.BackupParam.ValueString(),
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Get Backup",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Id.ID())

	tfRes, diags := conv.PostgresBackupAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "BackupResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.PostgresBackup = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (m *BackupResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	tflog.Info(ctx, "BackupResource.Update")
	var data BackupModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Update(ctx, 1800*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "BackupResource.Timeouts")
		return
	}

	bodyRequest, diags := conv.PostgresBackupTFToAPIRequestModel(ctx, &data.PostgresBackup)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "BackupResource.TFToAPI")
		return
	}

	apiRes, err := m.sdk.UpdatePostgresBackup(
		ctx,
		client.UpdatePostgresBackupRequest{
			Project: data.ProjectParam.ValueString(),
			Cluster: data.ClusterParam.ValueString(),
			Backup:  data.BackupParam.ValueString(),
			Body:    bodyRequest.AsUpdateModel(),
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Update Backup",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Id.ID())

	tfRes, diags := conv.PostgresBackupAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "BackupResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.PostgresBackup = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (m *BackupResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	tflog.Info(ctx, "BackupResource.Delete")
	var data BackupModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(data.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	data.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	resourceWaiterTimeout, diags := data.Timeouts.Delete(ctx, 1800*time.Second)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "BackupResource.Timeouts")
		return
	}

	err := m.sdk.DeletePostgresBackup(
		ctx,
		client.DeletePostgresBackupRequest{
			Project: data.ProjectParam.ValueString(),
			Cluster: data.ClusterParam.ValueString(),
			Backup:  data.BackupParam.ValueString(),
		},
		client.WithWait(wait.WithTimeout(resourceWaiterTimeout)),
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Delete Backup",
			diag.FormatError(err),
		)
		return
	}
}

func (m *BackupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Info(ctx, "BackupResource.ImportState")

	var data BackupModel

	ref, err := mpostgresref.ParsePostgresBackupRef(ctx, req.ID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Parse reference for Backup",
			diag.FormatError(err),
		)
		return
	}

	apiRes, err := m.sdk.GetPostgresBackup(
		ctx,
		client.GetPostgresBackupRequest{
			Backup:  string(ref.ResourceName()),
			Cluster: ref.GetCluster(),
			Project: ref.GetProject(),
		})
	if err != nil {
		resp.Diagnostics.AddError(
			"Get Backup",
			diag.FormatError(err),
		)
		return
	}

	data.ID = types.StringValue(apiRes.Metadata.Id.ID())

	tfRes, diags := conv.PostgresBackupAPIResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "BackupResource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	data.PostgresBackup = *tfRes

	data.BackupParam = types.StringValue(string(ref.ResourceName()))
	data.ClusterParam = types.StringValue(ref.GetCluster())
	data.ProjectParam = types.StringValue(ref.GetProject())

	var rwTimeouts timeouts.Value
	resp.Diagnostics.Append(resp.State.GetAttribute(ctx, path.Root("timeouts"), &rwTimeouts)...)
	if resp.Diagnostics.HasError() {
		tflog.Debug(ctx, "BackupResource.timeouts.GetAttribute")
		return
	}
	data.Timeouts = rwTimeouts

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
