// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/secretmanager/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/secretmanager/converter"
)

func TestSecretVersionStatusAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.SecretVersionStatusResponse{
		ResourceStatusResponse: commonmodel.ResourceStatusResponse{
			Ready: commonmodel.ResourceStatusReadyResponse{
				State: "",
			},
		},
	}
	_, diags := conv.SecretVersionStatusAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
