// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"go.mws.cloud/go-sdk/service/nlb/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/nlb/model"
)

func NlbRuleAPIOptionalResponseToTFModel(ctx context.Context, am *model.NlbRuleOptionalResponse) (*tfmodel.NlbRule, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NlbRule

	t.ProtoPort = types.StringValue(am.ProtoPort)

	if val, ok := am.TargetPort.Get(); ok {
		t.TargetPort = types.Int64Value(int64(val))
	} else {
		t.TargetPort = types.Int64Null()
	}

	if am.TargetAddressGroups != nil {
		targetAddressGroups := make([]tfcommon.VpcAddressGroupSpecOrRef, 0, len(am.TargetAddressGroups))

		for _, entity := range am.TargetAddressGroups {
			tmp, d := commonconv.VpcAddressGroupSpecOrRefAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			targetAddressGroups = append(targetAddressGroups, *tmp)
		}

		targetAddressGroupsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.VpcAddressGroupSpecOrRef).GetSchema().Attributes),
		}, targetAddressGroups)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.TargetAddressGroups = targetAddressGroupsList
	} else {
		t.TargetAddressGroups = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.VpcAddressGroupSpecOrRef).GetSchema().Attributes),
		})
	}

	if val, ok := am.HealthCheck.Get(); ok {
		healthCheckTmp, d := NlbHealthCheckAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		healthCheckTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.NlbHealthCheck).GetSchema().Attributes),
			*healthCheckTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.HealthCheck = healthCheckTfObject
	} else {
		t.HealthCheck = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.NlbHealthCheck).GetSchema().Attributes))
	}

	return &t, diags
}
