// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	apimodel "go.mws.cloud/go-sdk/service/nlb/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/nlb/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/nlb/model"
)

func TestNlbAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.NlbOptionalResponse{}
	_, diags := conv.NlbAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestNlbOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.NlbRequest{
		Spec: apimodel.NlbSpecRequest{
			Listener: apimodel.NlbListenerRequest{},
			Rules:    []apimodel.NlbRuleRequest{},
		},
	}

	emptyApiModelResponse, err := apimodel.NlbRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.NlbAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.NlbTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.NlbRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateNlbRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.Nlb
	var stateTfModel tfmodel.Nlb
	stateTfModel.Metadata = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes))

	expectedUpdateModel := &apimodel.UpdateNlbRequest{
		Metadata: optional.OptionalNil[commonapimodel.UpdateCommonTypedResourceMetadataRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.NlbTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
