// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	apimodel "go.mws.cloud/go-sdk/service/certmanager/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/certmanager/model"
)

func CertificateManagementTypeAPIToTFModel(ctx context.Context, am *apimodel.CertificateManagementType) (tfmodel.CertificateManagementType, tfdiag.Diagnostics) {
	if am == nil {
		return tfmodel.CertificateManagementType{}, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.CertificateManagementType

	t = tfmodel.CertificateManagementType(types.StringValue(string(*am)))

	return t, diags
}

func CertificateManagementTypeTFToAPIModel(ctx context.Context, tm tfmodel.CertificateManagementType) (*apimodel.CertificateManagementType, tfdiag.Diagnostics) {
	var diags tfdiag.Diagnostics
	var am apimodel.CertificateManagementType

	var tmp = types.String(tm)
	if tmp.IsNull() {
		return nil, diags
	}
	am = apimodel.CertificateManagementType(tmp.ValueString())

	return &am, diags
}
