// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"go.mws.cloud/go-sdk/service/certmanager/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/certmanager/model"
)

func CertificateChallengeTypeAPIToTFModel(ctx context.Context, am *model.CertificateChallengeType) (tfmodel.CertificateChallengeType, tfdiag.Diagnostics) {
	if am == nil {
		return tfmodel.CertificateChallengeType{}, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.CertificateChallengeType

	t = tfmodel.CertificateChallengeType(types.StringValue(string(*am)))

	return t, diags
}

func CertificateChallengeTypeTFToAPIModel(ctx context.Context, plan tfmodel.CertificateChallengeType) (*model.CertificateChallengeType, tfdiag.Diagnostics) {
	var diags tfdiag.Diagnostics
	var am model.CertificateChallengeType

	var tmp = types.String(plan)
	if tmp.IsNull() {
		return nil, diags
	}
	am = model.CertificateChallengeType(tmp.ValueString())

	return &am, diags
}
