// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NodeGroupModel struct {
	ProjectParam       types.String `tfsdk:"project"`
	ClusterNameParam   types.String `tfsdk:"cluster_name"`
	NodeGroupNameParam types.String `tfsdk:"node_group_name"`
	NodeGroup
}
