// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

func TestTypedResourceMetadataConverters(t *testing.T) {
	t.Parallel()
	apiModel := commonmodel.TypedResourceMetadata{}

	tfModel, diags := commonconv.TypedResourceMetadataAPIToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())

	result, diags := commonconv.TypedResourceMetadataTFToAPIModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	require.Equal(t, apiModel, *result)
}

func TestTypedResourceMetadataResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := commonmodel.TypedResourceMetadataRequest{}

	apiModelResponse, err := commonmodel.TypedResourceMetadataRequestToResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := commonconv.TypedResourceMetadataAPIResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := commonconv.TypedResourceMetadataTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := commonmodel.TypedResourceMetadataRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestTypedResourceMetadataOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := commonmodel.TypedResourceMetadataRequest{}

	apiModelResponse, err := commonmodel.TypedResourceMetadataRequestToOptionalResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := commonconv.TypedResourceMetadataAPIOptionalResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := commonconv.TypedResourceMetadataTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := commonmodel.TypedResourceMetadataRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdateTypedResourceMetadataConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfcommon.TypedResourceMetadata
	var stateTfModel tfcommon.TypedResourceMetadata

	expectedUpdateModel := &commonmodel.UpdateTypedResourceMetadata{}

	result, diags := commonconv.TypedResourceMetadataTFToAPIUpdateModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}

func TestUpdateTypedResourceMetadataRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfcommon.TypedResourceMetadata
	var stateTfModel tfcommon.TypedResourceMetadata

	expectedUpdateModel := &commonmodel.UpdateTypedResourceMetadataRequest{}

	result, diags := commonconv.TypedResourceMetadataTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
