// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/mclickhouse/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mclickhouse/converter"
)

func TestClickhouseClusterBootstrapAdminSpecAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.ClickhouseClusterBootstrapAdminSpecOptionalResponse{}
	_, diags := conv.ClickhouseClusterBootstrapAdminSpecAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestClickhouseClusterBootstrapAdminSpecOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.ClickhouseClusterBootstrapAdminSpecRequest{
		Username: "username",
	}

	emptyApiModelResponse, err := apimodel.ClickhouseClusterBootstrapAdminSpecRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.ClickhouseClusterBootstrapAdminSpecAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.ClickhouseClusterBootstrapAdminSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.ClickhouseClusterBootstrapAdminSpecRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}
