// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mclickhouse/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mclickhouse/converter"
)

func TestClickhouseInstanceHealthAPIToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ClickhouseInstanceHealth("")
	_, diags := conv.ClickhouseInstanceHealthAPIToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
