// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mclickhouse/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mclickhouse/converter"
)

func TestClickhouseDataDiskTypeAPIToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.ClickhouseDataDiskType("")
	_, diags := conv.ClickhouseDataDiskTypeAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
