// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	tfattr "github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	"go.mws.cloud/go-sdk/service/vpc/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/vpc/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func TestAddressAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.AddressOptionalResponse{}
	_, diags := conv.AddressAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestAddressOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.AddressRequest{
		Spec: model.VpcAddressSpecRequest{
			Subnet: vpc.NewMustSubnetRef("projectID", "networkID", "subnetID"),
		},
	}

	emptyApiModelResponse, err := model.AddressRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.AddressAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.AddressTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.AddressRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateAddressRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.Address
	var stateTfModel tfmodel.Address
	stateTfModel.Metadata = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes))
	stateTfModel.Dns = types.ListValueMust(types.ObjectType{
		AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.VpcAddressDnsSpec).GetSchema().Attributes),
	}, []tfattr.Value{})

	expectedUpdateModel := &model.UpdateAddressRequest{
		Metadata: optional.OptionalNil[commonmodel.UpdateCommonTypedResourceMetadataRequest]{
			Set:  true,
			Null: true,
		},
		Spec: optional.NewOptional(model.UpdateVpcAddressSpecRequest{
			Dns: optional.OptionalNil[[]commonmodel.UpdateVpcAddressDnsSpecRequest]{
				Set:  true,
				Null: true,
			},
		}),
	}

	result, diags := conv.AddressTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
