// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/vpc/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/vpc/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func TestExternalAddressOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.ExternalAddressRequest{
		Spec: model.VpcExternalAddressSpecRequest{},
	}

	apiModelResponse, err := model.ExternalAddressRequestToOptionalResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.ExternalAddressAPIOptionalResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.ExternalAddressTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.ExternalAddressRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdateExternalAddressRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.ExternalAddress
	var stateTfModel tfmodel.ExternalAddress
	stateTfModel.Metadata = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes))

	expectedUpdateModel := &model.UpdateExternalAddressRequest{
		Metadata: optional.OptionalNil[commonmodel.UpdateCommonTypedResourceMetadataRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.ExternalAddressTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
