// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/vpc/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/vpc/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func TestOneToOneNatSpecExternalAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.OneToOneNatSpecExternalOptionalResponse{}
	_, diags := conv.OneToOneNatSpecExternalAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestOneToOneNatSpecExternalOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.OneToOneNatSpecExternalRequest{
		Address: commonmodel.ResourceExternalAddressSpecOrRefRequest{},
	}

	emptyApiModelResponse, err := model.OneToOneNatSpecExternalRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.OneToOneNatSpecExternalAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.OneToOneNatSpecExternalTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.OneToOneNatSpecExternalRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateOneToOneNatSpecExternalRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.OneToOneNatSpecExternal
	var stateTfModel tfmodel.OneToOneNatSpecExternal

	expectedUpdateModel := &model.UpdateOneToOneNatSpecExternalRequest{}

	result, diags := conv.OneToOneNatSpecExternalTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
