// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	apimodel "go.mws.cloud/go-sdk/service/vpc/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/vpc/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func TestOneToOneNatSpecInternalAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.OneToOneNatSpecInternalOptionalResponse{}
	_, diags := conv.OneToOneNatSpecInternalAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestOneToOneNatSpecInternalOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.OneToOneNatSpecInternalRequest{
		Address: commonapimodel.ResourceAddressSpecOrRefRequest{},
	}

	emptyApiModelResponse, err := apimodel.OneToOneNatSpecInternalRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.OneToOneNatSpecInternalAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.OneToOneNatSpecInternalTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.OneToOneNatSpecInternalRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateOneToOneNatSpecInternalRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.OneToOneNatSpecInternal
	var stateTfModel tfmodel.OneToOneNatSpecInternal

	expectedUpdateModel := &apimodel.UpdateOneToOneNatSpecInternalRequest{}

	result, diags := conv.OneToOneNatSpecInternalTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
