// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/vpc/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/vpc/converter"
)

func TestRouteStatusAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.RouteStatusResponse{}
	_, diags := conv.RouteStatusAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
