// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	tfattr "github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/stretchr/testify/require"
	"go.mws.cloud/go-sdk/pkg/apimodels/ipaddress"

	"go.mws.cloud/go-sdk/pkg/optional"
	"go.mws.cloud/go-sdk/service/vpc/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/vpc/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func TestSubnetDhcpOptionsAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.SubnetDhcpOptionsOptionalResponse{}
	_, diags := conv.SubnetDhcpOptionsAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestSubnetDhcpOptionsOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.SubnetDhcpOptionsRequest{}

	emptyApiModelResponse, err := model.SubnetDhcpOptionsRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.SubnetDhcpOptionsAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.SubnetDhcpOptionsTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.SubnetDhcpOptionsRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestSubnetDhcpOptionsAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.SubnetDhcpOptionsResponse{}
	_, diags := conv.SubnetDhcpOptionsAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestSubnetDhcpOptionsResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.SubnetDhcpOptionsRequest{}

	emptyApiModelResponse, err := model.SubnetDhcpOptionsRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.SubnetDhcpOptionsAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.SubnetDhcpOptionsTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.SubnetDhcpOptionsRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateSubnetDhcpOptionsRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.SubnetDhcpOptions
	var stateTfModel tfmodel.SubnetDhcpOptions
	stateTfModel.DomainName = types.StringValue("")
	stateTfModel.DomainNameServers = types.ListValueMust(types.StringType, []tfattr.Value{})
	stateTfModel.NtpServers = types.ListValueMust(types.StringType, []tfattr.Value{})

	expectedUpdateModel := &model.UpdateSubnetDhcpOptionsRequest{
		DomainName: optional.OptionalNil[string]{
			Set:  true,
			Null: true,
		},
		DomainNameServers: optional.OptionalNil[[]ipaddress.IP4Address]{
			Set:  true,
			Null: true,
		},
		NtpServers: optional.OptionalNil[[]ipaddress.IP4Address]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.SubnetDhcpOptionsTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
