// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/vpc/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/vpc/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func TestVpcAddressGroupAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.VpcAddressGroupOptionalResponse{}
	_, diags := conv.VpcAddressGroupAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestVpcAddressGroupOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.VpcAddressGroupRequest{
		Spec: commonmodel.VpcAddressGroupSpecRequest{
			Addresses: []commonmodel.ResourceAddressSpecOrRefRequest{},
		},
	}

	emptyApiModelResponse, err := model.VpcAddressGroupRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.VpcAddressGroupAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.VpcAddressGroupTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.VpcAddressGroupRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateVpcAddressGroupRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.VpcAddressGroup
	var stateTfModel tfmodel.VpcAddressGroup
	stateTfModel.Metadata = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes))

	expectedUpdateModel := &model.UpdateVpcAddressGroupRequest{
		Metadata: optional.OptionalNil[commonmodel.UpdateCommonTypedResourceMetadataRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.VpcAddressGroupTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
