// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/queue/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/queue/converter"
)

func TestConsumerGroupStatusAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.ConsumerGroupStatusResponse{
		ResourceStatusResponse: commonmodel.ResourceStatusResponse{
			Ready: commonmodel.ResourceStatusReadyResponse{
				State: "",
			},
		},
	}
	_, diags := conv.ConsumerGroupStatusAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
