// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type BackupDataSourceModel struct {
	ProjectParam types.String `tfsdk:"project"`
	ClusterParam types.String `tfsdk:"cluster"`
	BackupParam  types.String `tfsdk:"backup"`
	PostgresBackup
}
