// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ClusterUserDataSourceModel struct {
	ProjectParam types.String `tfsdk:"project"`
	ClusterParam types.String `tfsdk:"cluster"`
	UserParam    types.String `tfsdk:"user"`
	PostgresClusterUser
}
