// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
)

type PostgresBackup struct {
	Kind     types.String `tfsdk:"kind"`
	Metadata types.Object `tfsdk:"metadata"`
	Status   types.Object `tfsdk:"status"`
}

func (s *PostgresBackup) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Резервное копирование в Managed PostgreSQL позволяет автоматизировать создание резервных копий кластера и его восстановление. С помощью резервных копий можно восстановить кластер в случае повреждения, потери данных или совершения ошибочных операций`,
		Attributes: map[string]schema.Attribute{
			"kind": schema.StringAttribute{
				Computed: true,
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes: new(PostgresBackupMetadata).GetSchema().Attributes,
				Computed:   true,
			},
			"status": schema.SingleNestedAttribute{
				Attributes: new(PostgresBackupStatus).GetSchema().Attributes,
				Computed:   true,
			},
		},
	}
}

type PostgresBackupMetadata struct {
	tfcommon.TypedResourceMetadata
	Id types.String `tfsdk:"id"`
}

func (s *PostgresBackupMetadata) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Представление поля Metadata анонимного типа структуры PostgresBackup`,
		Attributes: map[string]schema.Attribute{
			"display_name": schema.StringAttribute{
				MarkdownDescription: `Отображаемое имя. Необязательное поле, можно свободно задавать и изменять для удобства организации ресурсов`,
				Computed:            true,
			},
			"create_time": schema.StringAttribute{
				MarkdownDescription: `Дата создания объекта

Дата в формате RFC3339. Пример: 2006-01-02T15:04:05Z07:00`,
				Computed: true,
			},
			"delete_time": schema.StringAttribute{
				MarkdownDescription: `Время запроса на удаление ресурса (не фактическое время удаления)

Дата в формате RFC3339. Пример: 2006-01-02T15:04:05Z07:00`,
				Computed: true,
			},
			"purge_time": schema.StringAttribute{
				MarkdownDescription: `Время удаления ресурса

Дата в формате RFC3339. Пример: 2006-01-02T15:04:05Z07:00`,
				Computed: true,
			},
			"usages": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: new(tfcommon.TypedUsage).GetSchema().Attributes,
				},
				MarkdownDescription: `Связи с другими ресурсами. В зависимости от типа связи операции над ресурсом могут быть ограничены`,
				Computed:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: `Описание ресурса`,
				Computed:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: `Ссылка на типизированный референс`,
				Computed:            true,
			},
		},
	}
}
