// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PostgresExtensionSpec struct {
	Name types.String `tfsdk:"name"`
}

func (s *PostgresExtensionSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Спецификация расширения`,
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: `Имя расширения`,
				Computed:            true,
			},
		},
	}
}
