// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PostgresNetworkAddressSpec struct {
	Subnet types.String `tfsdk:"subnet"`
}

func (s *PostgresNetworkAddressSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описание подсети пользователя, используемой для подключения к узлам.`,
		Attributes: map[string]schema.Attribute{
			"subnet": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}
