// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"
	"encoding/json"
	"time"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	common "go.mws.cloud/go-sdk/service/common/model"
	apimodel "go.mws.cloud/go-sdk/service/mclickhouse/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mclickhouse/model"
)

func ClickhouseClusterAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.ClickhouseClusterOptionalResponse) (*tfmodel.ClickhouseCluster, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ClickhouseCluster

	if am.Kind != nil {
		t.Kind = types.StringPointerValue(am.Kind)
	} else {
		t.Kind = types.StringNull()
	}

	if val, ok := am.Metadata.Get(); ok {
		metadataTmp, d := ClickhouseClusterMetadataAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		metadataTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterMetadata).GetSchema().Attributes),
			*metadataTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Metadata = metadataTfObject
	} else {
		t.Metadata = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterMetadata).GetSchema().Attributes))
	}

	if am.Status != nil {
		statusTmp, d := ClickhouseClusterStatusAPIResponseToTFModel(ctx, am.Status)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		statusTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterStatus).GetSchema().Attributes),
			*statusTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Status = statusTfObject
	} else {
		t.Status = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterStatus).GetSchema().Attributes))
	}

	if val, ok := am.Spec.Active.Get(); ok {
		t.Active = types.BoolValue(val)
	} else {
		t.Active = types.BoolNull()
	}

	t.Version = types.StringValue(am.Spec.Version)

	if val, ok := am.Spec.Endpoints.Get(); ok {
		endpoints := make([]tfmodel.ClickhouseEndpoint, 0, len(val))

		for _, entity := range val {
			tmp, d := ClickhouseEndpointAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			endpoints = append(endpoints, *tmp)
		}

		endpointsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ClickhouseEndpoint).GetSchema().Attributes),
		}, endpoints)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Endpoints = endpointsList
	} else {
		t.Endpoints = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ClickhouseEndpoint).GetSchema().Attributes),
		})
	}

	if val, ok := am.Spec.Coordinator.Get(); ok {
		coordinatorTmp, d := ClickhouseClusterCoordinatorAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		coordinatorTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterCoordinator).GetSchema().Attributes),
			*coordinatorTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Coordinator = coordinatorTfObject
	} else {
		t.Coordinator = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterCoordinator).GetSchema().Attributes))
	}

	if am.Spec.Shards != nil {
		shards := make([]tfmodel.ClickhouseClusterShard, 0, len(am.Spec.Shards))

		for _, entity := range am.Spec.Shards {
			tmp, d := ClickhouseClusterShardAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			shards = append(shards, *tmp)
		}

		shardsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterShard).GetSchema().Attributes),
		}, shards)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Shards = shardsList
	} else {
		t.Shards = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterShard).GetSchema().Attributes),
		})
	}

	if val, ok := am.Spec.Config.Get(); ok {
		config := make(map[string]types.String, len(val))

		for k, entity := range val {
			config[k] = types.StringValue(string(entity))
		}

		configMap, d := types.MapValueFrom(ctx, types.StringType, config)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Config = configMap
	} else {
		t.Config = types.MapNull(types.StringType)
	}

	if val, ok := am.Spec.Storage.Get(); ok {
		storageTmp, d := ClickhouseStorageConfigurationAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		storageTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClickhouseStorageConfiguration).GetSchema().Attributes),
			*storageTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Storage = storageTfObject
	} else {
		t.Storage = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClickhouseStorageConfiguration).GetSchema().Attributes))
	}

	bootstrapAdminTmp, d := ClickhouseClusterBootstrapAdminSpecAPIOptionalResponseToTFModel(ctx, &am.Spec.BootstrapAdmin)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	bootstrapAdminTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterBootstrapAdminSpec).GetSchema().Attributes),
		*bootstrapAdminTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.BootstrapAdmin = bootstrapAdminTfObject

	if val, ok := am.Spec.Backup.Get(); ok {
		backupTmp, d := ClickhouseClusterBackupAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		backupTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterBackup).GetSchema().Attributes),
			*backupTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Backup = backupTfObject
	} else {
		t.Backup = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterBackup).GetSchema().Attributes))
	}

	if val, ok := am.Spec.MaintenanceWindow.Get(); ok {
		maintenanceWindowTmp, d := commonconv.MaintenanceWindowAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		maintenanceWindowTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfcommon.MaintenanceWindow).GetSchema().Attributes),
			*maintenanceWindowTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.MaintenanceWindow = maintenanceWindowTfObject
	} else {
		t.MaintenanceWindow = types.ObjectNull(tfconv.GetAttributesTypes(new(tfcommon.MaintenanceWindow).GetSchema().Attributes))
	}

	return &t, diags
}

func ClickhouseClusterTFToAPIRequestModel(ctx context.Context, tm *tfmodel.ClickhouseCluster) (*apimodel.ClickhouseClusterRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.ClickhouseClusterRequest

	if !tm.Metadata.IsNull() && !tm.Metadata.IsUnknown() {
		metadataTfModel := tfmodel.ClickhouseClusterMetadata{}
		metadataDiag := tm.Metadata.As(ctx, &metadataTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, metadataDiag...)
		if diags.HasError() {
			return nil, diags
		}

		metadataTmp, metadataDiag := ClickhouseClusterMetadataTFToAPIRequestModel(ctx, &metadataTfModel)
		diags = append(diags, metadataDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Metadata = metadataTmp
	}

	if !tm.Active.IsNull() && !tm.Active.IsUnknown() {
		am.Spec.Active = tm.Active.ValueBoolPointer()
	}

	if !tm.Version.IsNull() && !tm.Version.IsUnknown() {
		am.Spec.Version = tm.Version.ValueString()
	}

	if !tm.Endpoints.IsNull() && !tm.Endpoints.IsUnknown() {
		endpoints := make([]tfmodel.ClickhouseEndpoint, 0)
		dEndpoints := tm.Endpoints.ElementsAs(ctx, &endpoints, false)
		diags = append(diags, dEndpoints...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.Endpoints = make([]apimodel.ClickhouseEndpointRequest, 0, len(endpoints))

		for _, entity := range endpoints {
			tmp, d := ClickhouseEndpointTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Spec.Endpoints = append(am.Spec.Endpoints, *tmp)
		}
	}

	if !tm.Coordinator.IsNull() && !tm.Coordinator.IsUnknown() {
		coordinatorTfModel := tfmodel.ClickhouseClusterCoordinator{}
		coordinatorDiag := tm.Coordinator.As(ctx, &coordinatorTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, coordinatorDiag...)
		if diags.HasError() {
			return nil, diags
		}

		coordinatorTmp, coordinatorDiag := ClickhouseClusterCoordinatorTFToAPIRequestModel(ctx, &coordinatorTfModel)
		diags = append(diags, coordinatorDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.Coordinator = coordinatorTmp
	}

	if !tm.Shards.IsNull() && !tm.Shards.IsUnknown() {
		shards := make([]tfmodel.ClickhouseClusterShard, 0)
		dShards := tm.Shards.ElementsAs(ctx, &shards, false)
		diags = append(diags, dShards...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.Shards = make([]apimodel.ClickhouseClusterShardRequest, 0, len(shards))

		for _, entity := range shards {
			tmp, d := ClickhouseClusterShardTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Spec.Shards = append(am.Spec.Shards, *tmp)
		}
	}

	if !tm.Config.IsNull() && !tm.Config.IsUnknown() {
		config := make(map[string]types.String)
		dConfig := tm.Config.ElementsAs(ctx, &config, false)
		diags = append(diags, dConfig...)
		if diags.HasError() {
			return nil, diags
		}

		am.Spec.Config = make(map[string]json.RawMessage, len(config))

		for k, entity := range config {
			am.Spec.Config[k] = json.RawMessage(entity.ValueString())
		}
	}

	if !tm.Storage.IsNull() && !tm.Storage.IsUnknown() {
		storageTfModel := tfmodel.ClickhouseStorageConfiguration{}
		storageDiag := tm.Storage.As(ctx, &storageTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, storageDiag...)
		if diags.HasError() {
			return nil, diags
		}

		storageTmp, storageDiag := ClickhouseStorageConfigurationTFToAPIRequestModel(ctx, &storageTfModel)
		diags = append(diags, storageDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.Storage = storageTmp
	}

	if !tm.BootstrapAdmin.IsNull() && !tm.BootstrapAdmin.IsUnknown() {
		bootstrapAdminTfModel := tfmodel.ClickhouseClusterBootstrapAdminSpec{}
		bootstrapAdminDiag := tm.BootstrapAdmin.As(ctx, &bootstrapAdminTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, bootstrapAdminDiag...)
		if diags.HasError() {
			return nil, diags
		}

		bootstrapAdminTmp, bootstrapAdminDiag := ClickhouseClusterBootstrapAdminSpecTFToAPIRequestModel(ctx, &bootstrapAdminTfModel)
		diags = append(diags, bootstrapAdminDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.BootstrapAdmin = *bootstrapAdminTmp
	}

	if !tm.Backup.IsNull() && !tm.Backup.IsUnknown() {
		backupTfModel := tfmodel.ClickhouseClusterBackup{}
		backupDiag := tm.Backup.As(ctx, &backupTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, backupDiag...)
		if diags.HasError() {
			return nil, diags
		}

		backupTmp, backupDiag := ClickhouseClusterBackupTFToAPIRequestModel(ctx, &backupTfModel)
		diags = append(diags, backupDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.Backup = backupTmp
	}

	if !tm.MaintenanceWindow.IsNull() && !tm.MaintenanceWindow.IsUnknown() {
		maintenanceWindowTfModel := tfcommon.MaintenanceWindow{}
		maintenanceWindowDiag := tm.MaintenanceWindow.As(ctx, &maintenanceWindowTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, maintenanceWindowDiag...)
		if diags.HasError() {
			return nil, diags
		}

		maintenanceWindowTmp, maintenanceWindowDiag := commonconv.MaintenanceWindowTFToAPIRequestModel(ctx, &maintenanceWindowTfModel)
		diags = append(diags, maintenanceWindowDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec.MaintenanceWindow = maintenanceWindowTmp
	}

	return &am, diags
}

func ClickhouseClusterMetadataAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.ClickhouseClusterMetadataOptionalResponse) (*tfmodel.ClickhouseClusterMetadata, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ClickhouseClusterMetadata

	if val, ok := am.DisplayName.Get(); ok {
		t.DisplayName = types.StringValue(val)
	} else {
		t.DisplayName = types.StringNull()
	}

	if am.CreateTime != nil {
		t.CreateTime = types.StringPointerValue(ptr.Get(am.CreateTime.Format(time.RFC3339)))
	} else {
		t.CreateTime = types.StringNull()
	}

	if am.DeleteTime != nil {
		t.DeleteTime = types.StringPointerValue(ptr.Get(am.DeleteTime.Format(time.RFC3339)))
	} else {
		t.DeleteTime = types.StringNull()
	}

	if am.PurgeTime != nil {
		t.PurgeTime = types.StringPointerValue(ptr.Get(am.PurgeTime.Format(time.RFC3339)))
	} else {
		t.PurgeTime = types.StringNull()
	}

	if val, ok := am.Usages.Get(); ok {
		usages := make([]tfcommon.TypedUsage, 0, len(val))

		for _, entity := range val {
			tmp, d := commonconv.TypedUsageAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			usages = append(usages, *tmp)
		}

		usagesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.TypedUsage).GetSchema().Attributes),
		}, usages)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Usages = usagesList
	} else {
		t.Usages = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.TypedUsage).GetSchema().Attributes),
		})
	}

	if val, ok := am.Description.Get(); ok {
		t.Description = types.StringValue(val)
	} else {
		t.Description = types.StringNull()
	}

	if am.Id != nil {
		t.Id = types.StringPointerValue(ptr.Get(am.Id.ID()))
	} else {
		t.Id = types.StringNull()
	}

	return &t, diags
}

func ClickhouseClusterMetadataTFToAPIRequestModel(ctx context.Context, tm *tfmodel.ClickhouseClusterMetadata) (*apimodel.ClickhouseClusterMetadataRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.ClickhouseClusterMetadataRequest

	if !tm.DisplayName.IsNull() && !tm.DisplayName.IsUnknown() {
		am.DisplayName = tm.DisplayName.ValueStringPointer()
	}

	if !tm.Usages.IsNull() && !tm.Usages.IsUnknown() {
		usages := make([]tfcommon.TypedUsage, 0)
		dUsages := tm.Usages.ElementsAs(ctx, &usages, false)
		diags = append(diags, dUsages...)
		if diags.HasError() {
			return nil, diags
		}
		am.Usages = make([]common.TypedUsageRequest, 0, len(usages))

		for _, entity := range usages {
			tmp, d := commonconv.TypedUsageTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Usages = append(am.Usages, *tmp)
		}
	}

	if !tm.Description.IsNull() && !tm.Description.IsUnknown() {
		am.Description = tm.Description.ValueStringPointer()
	}

	return &am, diags
}
