// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	apimodel "go.mws.cloud/go-sdk/service/mclickhouse/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mclickhouse/model"
)

func ClickhouseClusterResourceAPIResponseToTFModel(ctx context.Context, am *apimodel.ClickhouseClusterResourceResponse) (*tfmodel.ClickhouseClusterResource, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ClickhouseClusterResource

	t.Active = types.BoolValue(am.Active)

	t.Version = types.StringValue(am.Version)

	if am.Endpoints != nil {
		endpoints := make([]tfmodel.ClickhouseEndpointResource, 0, len(am.Endpoints))

		for _, entity := range am.Endpoints {
			tmp, d := ClickhouseEndpointResourceAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			endpoints = append(endpoints, *tmp)
		}

		endpointsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ClickhouseEndpointResource).GetSchema().Attributes),
		}, endpoints)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Endpoints = endpointsList
	} else {
		t.Endpoints = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ClickhouseEndpointResource).GetSchema().Attributes),
		})
	}

	if am.Coordinator != nil {
		coordinatorTmp, d := ClickhouseClusterCoordinatorResourceAPIResponseToTFModel(ctx, am.Coordinator)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		coordinatorTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterCoordinatorResource).GetSchema().Attributes),
			*coordinatorTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Coordinator = coordinatorTfObject
	} else {
		t.Coordinator = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterCoordinatorResource).GetSchema().Attributes))
	}

	if am.Shards != nil {
		shards := make([]tfmodel.ClickhouseClusterShardResource, 0, len(am.Shards))

		for _, entity := range am.Shards {
			tmp, d := ClickhouseClusterShardResourceAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			shards = append(shards, *tmp)
		}

		shardsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterShardResource).GetSchema().Attributes),
		}, shards)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Shards = shardsList
	} else {
		t.Shards = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterShardResource).GetSchema().Attributes),
		})
	}

	if am.Config != nil {
		config := make(map[string]types.String, len(am.Config))

		for k, entity := range am.Config {
			config[k] = types.StringValue(string(entity))
		}

		configMap, d := types.MapValueFrom(ctx, types.StringType, config)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Config = configMap
	} else {
		t.Config = types.MapNull(types.StringType)
	}

	if am.Storage != nil {
		storageTmp, d := ClickhouseStorageConfigurationAPIResponseToTFModel(ctx, am.Storage)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		storageTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClickhouseStorageConfiguration).GetSchema().Attributes),
			*storageTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Storage = storageTfObject
	} else {
		t.Storage = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClickhouseStorageConfiguration).GetSchema().Attributes))
	}

	maintenanceWindowTmp, d := commonconv.MaintenanceWindowAPIResponseToTFModel(ctx, &am.MaintenanceWindow)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	maintenanceWindowTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfcommon.MaintenanceWindow).GetSchema().Attributes),
		*maintenanceWindowTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.MaintenanceWindow = maintenanceWindowTfObject

	backupTmp, d := ClickhouseClusterBackupResourceAPIResponseToTFModel(ctx, &am.Backup)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	backupTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.ClickhouseClusterBackupResource).GetSchema().Attributes),
		*backupTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.Backup = backupTfObject

	return &t, diags
}
