// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"go.mws.cloud/go-sdk/service/mclickhouse/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mclickhouse/model"
)

func ClickhouseInstanceHealthAPIToTFModel(ctx context.Context, am *model.ClickhouseInstanceHealth) (tfmodel.ClickhouseInstanceHealth, tfdiag.Diagnostics) {
	if am == nil {
		return tfmodel.ClickhouseInstanceHealth{}, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ClickhouseInstanceHealth

	t = tfmodel.ClickhouseInstanceHealth(types.StringValue(string(*am)))

	return t, diags
}

func ClickhouseInstanceHealthTFToAPIModel(ctx context.Context, plan tfmodel.ClickhouseInstanceHealth) (*model.ClickhouseInstanceHealth, tfdiag.Diagnostics) {
	var diags tfdiag.Diagnostics
	var am model.ClickhouseInstanceHealth

	var tmp = types.String(plan)
	if tmp.IsNull() {
		return nil, diags
	}
	am = model.ClickhouseInstanceHealth(tmp.ValueString())

	return &am, diags
}
