// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mkafka/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mkafka/converter"
)

func TestKafkaS3PropertiesAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.KafkaS3PropertiesOptionalResponse{}
	_, diags := conv.KafkaS3PropertiesAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
