// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/mkafka/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mkafka/converter"
)

func TestKafkaConnectorAPIOptionalResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.KafkaConnectorOptionalResponse{
		Spec: model.KafkaConnectorSpecOptionalResponse{},
	}
	_, diags := conv.KafkaConnectorAPIOptionalResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestKafkaConnectorMetadataAPIOptionalResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.KafkaConnectorMetadataOptionalResponse{
		TypedResourceMetadataOptionalResponse: commonmodel.TypedResourceMetadataOptionalResponse{},
	}
	_, diags := conv.KafkaConnectorMetadataAPIOptionalResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
