// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	apimodel "go.mws.cloud/go-sdk/service/mkafka/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/mkafka/converter"
)

func TestKafkaDataDiskSpecAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.KafkaDataDiskSpecResponse{}
	_, diags := conv.KafkaDataDiskSpecAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestKafkaDataDiskSpecResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.KafkaDataDiskSpecRequest{
		Size: bytesize.MustParseString("0 B"),
	}

	emptyApiModelResponse, err := apimodel.KafkaDataDiskSpecRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.KafkaDataDiskSpecAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.KafkaDataDiskSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.KafkaDataDiskSpecRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}
