// Code generated by mwsapigen, DO NOT EDIT.

package secretmanager

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	ctxvalues "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/secretmanager/client"
	resourcesdk "go.mws.cloud/go-sdk/service/secretmanager/sdk"
	"go.mws.cloud/terraform-provider-mws/internal/cmp"
	"go.mws.cloud/terraform-provider-mws/internal/diag"
	provider "go.mws.cloud/terraform-provider-mws/internal/provider/public"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/secretmanager/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/secretmanager/model"
)

var (
	_ datasource.DataSource = &SecretRoleBindingDataSource{}
)

type SecretRoleBindingDataSource struct {
	sdk    *resourcesdk.SecretRoleBinding
	config *provider.Config
}

func NewSecretRoleBindingDataSource() datasource.DataSource {
	return &SecretRoleBindingDataSource{}
}

func (m *SecretRoleBindingDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	tflog.Info(ctx, "SecretRoleBindingDataSource.Metadata")
	resp.TypeName = req.ProviderTypeName + "_secretmanager_secret_role_binding"
}

func (m *SecretRoleBindingDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	tflog.Info(ctx, "SecretRoleBindingDataSource.Schema")
	resp.Schema = new(tfmodel.SecretRoleBinding).GetSchema()
	resp.Schema.Attributes["name"] = schema.StringAttribute{
		MarkdownDescription: `Имя секрета.`,
		Required:            true,
	}
	resp.Schema.Attributes["project"] = schema.StringAttribute{
		MarkdownDescription: `Путь к проекту.`,
		Optional:            true,
		Computed:            true,
	}
	resp.Schema.Attributes["role_binding"] = schema.StringAttribute{
		Required: true,
	}
}

func (m *SecretRoleBindingDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	var err error
	tflog.Info(ctx, "SecretRoleBindingDataSource.Configure")
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*provider.Data)
	if !ok || providerData == nil {
		resp.Diagnostics.AddError("Internal Provider Error", "Unexpected type of req.ProviderData")
		return
	}

	m.config = providerData.Config

	m.sdk, err = resourcesdk.NewSecretRoleBinding(ctx, providerData.SDK)
	if err != nil {
		resp.Diagnostics.AddError(
			"Create SDK client for SecretRoleBinding",
			diag.FormatError(err),
		)
		return
	}
}

func (m *SecretRoleBindingDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	tflog.Info(ctx, "SecretRoleBindingDataSource.Read")

	var config tfmodel.SecretRoleBindingModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectParam := cmp.Or(config.ProjectParam, m.config.Project)
	if projectParam.IsNull() || projectParam.IsUnknown() {
		resp.Diagnostics.AddError(
			"Configuration Error",
			`Parameter "project" is null or unknown`,
		)
		return
	}
	config.ProjectParam = projectParam
	ctx = ctxvalues.With(ctx, "project", projectParam.String())

	apiRes, err := m.sdk.GetRoleBinding(
		ctx,
		client.GetRoleBindingRequest{
			Project:     config.ProjectParam.ValueString(),
			Name:        config.NameParam.ValueString(),
			RoleBinding: config.RoleBindingParam.ValueString(),
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Get SecretRoleBinding",
			diag.FormatError(err),
		)
		return
	}

	tfRes, diags := conv.SecretRoleBindingAPIOptionalResponseToTFModel(ctx, apiRes)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || tfRes == nil {
		tflog.Debug(ctx, "SecretRoleBindingDataSource.ApiToTfConvert.tfRes", map[string]any{"res": tfRes})
		return
	}

	config.SecretRoleBinding = *tfRes

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
