// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/vpc/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func EgressNatSpecExternalAPIOptionalResponseToTFModel(ctx context.Context, am *model.EgressNatSpecExternalOptionalResponse) (*tfmodel.EgressNatSpecExternal, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.EgressNatSpecExternal

	if am.Addresses != nil {
		addresses := make([]tfcommon.ResourceExternalAddressSpecOrRef, 0, len(am.Addresses))

		for _, entity := range am.Addresses {
			tmp, d := commonconv.ResourceExternalAddressSpecOrRefAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			addresses = append(addresses, *tmp)
		}

		addressesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.ResourceExternalAddressSpecOrRef).GetSchema().Attributes),
		}, addresses)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Addresses = addressesList
	} else {
		t.Addresses = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfcommon.ResourceExternalAddressSpecOrRef).GetSchema().Attributes),
		})
	}

	return &t, diags
}

func EgressNatSpecExternalTFToAPIRequestModel(ctx context.Context, plan *tfmodel.EgressNatSpecExternal) (*model.EgressNatSpecExternalRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.EgressNatSpecExternalRequest

	if !plan.Addresses.IsNull() && !plan.Addresses.IsUnknown() {
		addresses := make([]tfcommon.ResourceExternalAddressSpecOrRef, 0)
		dAddresses := plan.Addresses.ElementsAs(ctx, &addresses, false)
		diags = append(diags, dAddresses...)
		if diags.HasError() {
			return nil, diags
		}

		am.Addresses = make([]commonmodel.ResourceExternalAddressSpecOrRefRequest, 0, len(addresses))

		for _, entity := range addresses {
			tmp, d := commonconv.ResourceExternalAddressSpecOrRefTFToAPIRequestModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			am.Addresses = append(am.Addresses, *tmp)
		}
	}

	return &am, diags
}

func EgressNatSpecExternalTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.EgressNatSpecExternal) (*model.UpdateEgressNatSpecExternalRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.EgressNatSpecExternal{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateEgressNatSpecExternalRequest

	if !plan.Addresses.Equal(state.Addresses) {
		if !plan.Addresses.IsNull() && !plan.Addresses.IsUnknown() {
			addresses := make([]tfcommon.ResourceExternalAddressSpecOrRef, 0)
			dAddresses := plan.Addresses.ElementsAs(ctx, &addresses, false)
			diags = append(diags, dAddresses...)
			if diags.HasError() {
				return nil, diags
			}

			addressesTmp := make([]commonmodel.UpdateResourceExternalAddressSpecOrRefRequest, 0, len(addresses))

			for _, entity := range addresses {
				stateEntity := tfcommon.ResourceExternalAddressSpecOrRef{}
				tmp, d := commonconv.ResourceExternalAddressSpecOrRefTFToAPIUpdateRequestModel(ctx, &entity, &stateEntity)
				diags = append(diags, d...)
				if diags.HasError() {
					return nil, diags
				}
				addressesTmp = append(addressesTmp, *tmp)
			}
			am.Addresses.SetTo(addressesTmp)
		}
	}

	return &am, diags
}
