// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	apimodel "go.mws.cloud/go-sdk/service/vpc/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func NlbStatusAPIResponseToTFModel(ctx context.Context, am *apimodel.NlbStatusResponse) (*tfmodel.NlbStatus, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NlbStatus

	readyTmp, d := commonconv.ResourceStatusReadyAPIResponseToTFModel(ctx, &am.Ready)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	readyTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfcommon.ResourceStatusReady).GetSchema().Attributes),
		*readyTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.Ready = readyTfObject

	if am.Listener != nil {
		listenerTmp, d := NlbStatusListenerAPIResponseToTFModel(ctx, am.Listener)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		listenerTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.NlbStatusListener).GetSchema().Attributes),
			*listenerTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Listener = listenerTfObject
	} else {
		t.Listener = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.NlbStatusListener).GetSchema().Attributes))
	}

	if am.TargetAddressGroups != nil {
		targetAddressGroupsTmp, d := NlbTargetAddressGroupsStatusAPIResponseToTFModel(ctx, am.TargetAddressGroups)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		targetAddressGroupsTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.NlbTargetAddressGroupsStatus).GetSchema().Attributes),
			*targetAddressGroupsTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.TargetAddressGroups = targetAddressGroupsTfObject
	} else {
		t.TargetAddressGroups = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.NlbTargetAddressGroupsStatus).GetSchema().Attributes))
	}

	if am.Rules != nil {
		rules := make([]tfmodel.NlbStatusRule, 0, len(am.Rules))

		for _, entity := range am.Rules {
			tmp, d := NlbStatusRuleAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			rules = append(rules, *tmp)
		}

		rulesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.NlbStatusRule).GetSchema().Attributes),
		}, rules)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Rules = rulesList
	} else {
		t.Rules = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.NlbStatusRule).GetSchema().Attributes),
		})
	}

	return &t, diags
}
