// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	apimodel "go.mws.cloud/go-sdk/service/vpc/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/vpc/model"
)

func NlbStatusRuleAPIResponseToTFModel(ctx context.Context, am *apimodel.NlbStatusRuleResponse) (*tfmodel.NlbStatusRule, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NlbStatusRule

	t.ProtoPort = types.StringValue(am.ProtoPort)

	if am.TargetPort != nil {
		t.TargetPort = types.Int64PointerValue(ptr.Get(int64(*am.TargetPort)))
	} else {
		t.TargetPort = types.Int64Null()
	}

	if am.TargetAddressGroups != nil {
		targetAddressGroups := make([]tfmodel.VpcAddressGroupSpecOrRef, 0, len(am.TargetAddressGroups))

		for _, entity := range am.TargetAddressGroups {
			tmp, d := VpcAddressGroupSpecOrRefAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			targetAddressGroups = append(targetAddressGroups, *tmp)
		}

		targetAddressGroupsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.VpcAddressGroupSpecOrRef).GetSchema().Attributes),
		}, targetAddressGroups)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.TargetAddressGroups = targetAddressGroupsList
	} else {
		t.TargetAddressGroups = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.VpcAddressGroupSpecOrRef).GetSchema().Attributes),
		})
	}

	if am.TargetStatuses != nil {
		targetStatuses := make([]tfmodel.NlbStatusRealStatus, 0, len(am.TargetStatuses))

		for _, entity := range am.TargetStatuses {
			tmp, d := NlbStatusRealStatusAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			targetStatuses = append(targetStatuses, *tmp)
		}

		targetStatusesList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.NlbStatusRealStatus).GetSchema().Attributes),
		}, targetStatuses)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.TargetStatuses = targetStatusesList
	} else {
		t.TargetStatuses = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.NlbStatusRealStatus).GetSchema().Attributes),
		})
	}

	if am.HealthCheck != nil {
		healthCheckTmp, d := NlbStatusHealthCheckAPIResponseToTFModel(ctx, am.HealthCheck)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		healthCheckTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.NlbStatusHealthCheck).GetSchema().Attributes),
			*healthCheckTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.HealthCheck = healthCheckTfObject
	} else {
		t.HealthCheck = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.NlbStatusHealthCheck).GetSchema().Attributes))
	}

	return &t, diags
}
