// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/compute/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/compute/converter"
)

func TestAddressSpecAPIOptionalResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.AddressSpecOptionalResponse{
		Subnet: vpc.NewMustSubnetRef("projectID", "networkID", "subnetID"),
	}
	_, diags := conv.AddressSpecAPIOptionalResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
