// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/compute/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/compute/converter"
)

func TestAddressSpecAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.AddressSpecOptionalResponse{}
	_, diags := conv.AddressSpecAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
