// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/compute/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/compute/converter"
)

func TestDiskAPIOptionalResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.DiskOptionalResponse{
		Spec: model.DiskSpecOptionalResponse{
			Zone: "zone",
		},
	}
	_, diags := conv.DiskAPIOptionalResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
