// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	localint64planmodifier "go.mws.cloud/terraform-provider-mws/internal/planmodifier/int64planmodifier"
	localmapplanmodifier "go.mws.cloud/terraform-provider-mws/internal/planmodifier/mapplanmodifier"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

type Topic struct {
	Kind           types.String `tfsdk:"kind"`
	Metadata       types.Object `tfsdk:"metadata"`
	Status         types.Object `tfsdk:"status"`
	PartitionCount types.Int64  `tfsdk:"partition_count"`
	TopicId        types.String `tfsdk:"topic_id"`
	Config         types.Map    `tfsdk:"config"`
}

func (s *Topic) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"kind": schema.StringAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes,
				MarkdownDescription: `Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров`,
				Computed:            true,
				Optional:            true,
			},
			"status": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.ResourceStatus).GetSchema().Attributes,
				MarkdownDescription: `Текущее состояние ресурса, вычисляемое системой`,
				Computed:            true,
			},
			"partition_count": schema.Int64Attribute{
				MarkdownDescription: `Кол-во партиций топика`,
				Optional:            true,
				PlanModifiers: []planmodifier.Int64{
					localint64planmodifier.RequiresReplaceIfRemoved(),
				},
			},
			"topic_id": schema.StringAttribute{
				MarkdownDescription: `Идентификатор топика`,
				Computed:            true,
			},
			"config": schema.MapAttribute{
				ElementType: types.StringType,
				MarkdownDescription: `Конфигурация Kafka-топика.
Ключи и значения соответствуют стандартным
[настройкам топиков Kafka](https://kafka.apache.org/documentation/#topicconfigs).
Все значения передаются как строки`,
				Optional: true,
				PlanModifiers: []planmodifier.Map{
					localmapplanmodifier.RequiresReplaceIfRemoved(),
				},
			},
		},
	}
}
