// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mkafka/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/model"
)

func TestKafkaEndpointExternalAccessesAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.KafkaEndpointExternalAccessesResponse{}
	_, diags := conv.KafkaEndpointExternalAccessesAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestKafkaEndpointExternalAccessesResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.KafkaEndpointExternalAccessesRequest{
		Allowed: false,
	}

	emptyApiModelResponse, err := model.KafkaEndpointExternalAccessesRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.KafkaEndpointExternalAccessesAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.KafkaEndpointExternalAccessesTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.KafkaEndpointExternalAccessesRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateKafkaEndpointExternalAccessesRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.KafkaEndpointExternalAccesses
	var stateTfModel tfmodel.KafkaEndpointExternalAccesses

	expectedUpdateModel := &model.UpdateKafkaEndpointExternalAccessesRequest{}

	result, diags := conv.KafkaEndpointExternalAccessesTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
