// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	apimodel "go.mws.cloud/go-sdk/service/mkafka/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/model"
)

func TestKafkaTopicAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.KafkaTopicResponse{}
	_, diags := conv.KafkaTopicAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestKafkaTopicResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.KafkaTopicRequest{
		Spec: apimodel.KafkaTopicSpecRequest{},
	}

	emptyApiModelResponse, err := apimodel.KafkaTopicRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.KafkaTopicAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.KafkaTopicTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.KafkaTopicRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateKafkaTopicRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.KafkaTopic
	var stateTfModel tfmodel.KafkaTopic
	stateTfModel.Metadata = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfmodel.KafkaTopicMetadata).GetSchema().Attributes))

	expectedUpdateModel := &apimodel.UpdateKafkaTopicRequest{
		Metadata: optional.OptionalNil[apimodel.UpdateKafkaTopicMetadataRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.KafkaTopicTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}

func TestKafkaTopicMetadataAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.KafkaTopicMetadataResponse{}
	_, diags := conv.KafkaTopicMetadataAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestKafkaTopicMetadataResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.KafkaTopicMetadataRequest{
		TypedResourceMetadataRequest: commonapimodel.TypedResourceMetadataRequest{},
	}

	emptyApiModelResponse, err := apimodel.KafkaTopicMetadataRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.KafkaTopicMetadataAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.KafkaTopicMetadataTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.KafkaTopicMetadataRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateKafkaTopicMetadataRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.KafkaTopicMetadata
	var stateTfModel tfmodel.KafkaTopicMetadata

	expectedUpdateModel := &apimodel.UpdateKafkaTopicMetadataRequest{}

	result, diags := conv.KafkaTopicMetadataTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
