// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mkafka/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/model"
)

func TestKafkaEndpointExternalAddressSpecAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.KafkaEndpointExternalAddressSpecResponse{}
	_, diags := conv.KafkaEndpointExternalAddressSpecAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestKafkaEndpointExternalAddressSpecResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.KafkaEndpointExternalAddressSpecRequest{}

	emptyApiModelResponse, err := model.KafkaEndpointExternalAddressSpecRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.KafkaEndpointExternalAddressSpecAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.KafkaEndpointExternalAddressSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.KafkaEndpointExternalAddressSpecRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateKafkaEndpointExternalAddressSpecRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.KafkaEndpointExternalAddressSpec
	var stateTfModel tfmodel.KafkaEndpointExternalAddressSpec

	expectedUpdateModel := &model.UpdateKafkaEndpointExternalAddressSpecRequest{}

	result, diags := conv.KafkaEndpointExternalAddressSpecTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
