// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mkafka/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/model"
)

func TestKafkaS3PropertiesOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.KafkaS3PropertiesRequest{
		BucketName:  "bucketName",
		AccessKeyId: "accessKeyId",
		Endpoint:    "endpoint",
	}

	apiModelResponse, err := model.KafkaS3PropertiesRequestToOptionalResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.KafkaS3PropertiesAPIOptionalResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.KafkaS3PropertiesTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.KafkaS3PropertiesRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdateKafkaS3PropertiesRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.KafkaS3Properties
	var stateTfModel tfmodel.KafkaS3Properties

	expectedUpdateModel := &model.UpdateKafkaS3PropertiesRequest{}

	result, diags := conv.KafkaS3PropertiesTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
