// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mkafka/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/model"
)

func TestKafkaClusterRoleResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.KafkaClusterRoleRequest{
		Name: "",
	}

	apiModelResponse, err := model.KafkaClusterRoleRequestToResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.KafkaClusterRoleAPIResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.KafkaClusterRoleTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.KafkaClusterRoleRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdateKafkaClusterRoleRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.KafkaClusterRole
	var stateTfModel tfmodel.KafkaClusterRole

	expectedUpdateModel := &model.UpdateKafkaClusterRoleRequest{}

	result, diags := conv.KafkaClusterRoleTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
