// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	apimodel "go.mws.cloud/go-sdk/service/vpc/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/vpc/model"
)

func FirewallRuleSourceAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.FirewallRuleSourceOptionalResponse) (*tfmodel.FirewallRuleSource, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.FirewallRuleSource

	if val, ok := am.Spec.Get(); ok {
		specTmp, d := FirewallRuleSourceSpecAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		specTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.FirewallRuleSourceSpec).GetSchema().Attributes),
			*specTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Spec = specTfObject
	} else {
		t.Spec = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.FirewallRuleSourceSpec).GetSchema().Attributes))
	}

	return &t, diags
}

func FirewallRuleSourceTFToAPIRequestModel(ctx context.Context, tm *tfmodel.FirewallRuleSource) (*apimodel.FirewallRuleSourceRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.FirewallRuleSourceRequest

	if !tm.Spec.IsNull() && !tm.Spec.IsUnknown() {
		specTfModel := tfmodel.FirewallRuleSourceSpec{}
		specDiag := tm.Spec.As(ctx, &specTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, specDiag...)
		if diags.HasError() {
			return nil, diags
		}

		specTmp, specDiag := FirewallRuleSourceSpecTFToAPIRequestModel(ctx, &specTfModel)
		diags = append(diags, specDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec = specTmp
	}

	return &am, diags
}
