// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	"go.mws.cloud/go-sdk/service/vpc/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/vpc/model"
)

func SubnetAPIOptionalResponseToTFModel(ctx context.Context, am *model.SubnetOptionalResponse) (*tfmodel.Subnet, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.Subnet

	if am.Kind != nil {
		t.Kind = types.StringPointerValue(am.Kind)
	} else {
		t.Kind = types.StringNull()
	}

	if val, ok := am.Metadata.Get(); ok {
		metadataTmp, d := commonconv.CommonTypedResourceMetadataAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		metadataTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes),
			*metadataTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Metadata = metadataTfObject
	} else {
		t.Metadata = types.ObjectNull(tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes))
	}

	if am.Status != nil {
		statusTmp, d := SubnetStatusAPIResponseToTFModel(ctx, am.Status)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		statusTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.SubnetStatus).GetSchema().Attributes),
			*statusTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Status = statusTfObject
	} else {
		t.Status = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.SubnetStatus).GetSchema().Attributes))
	}

	if val, ok := am.Spec.Region.Get(); ok {
		t.Region = types.StringPointerValue(ptr.Get(val.Path()))
	} else {
		t.Region = types.StringNull()
	}

	t.Cidr = types.StringValue(ptr.Value(am.Spec.Cidr.RawValue()))

	if val, ok := am.Spec.DhcpOptions.Get(); ok {
		dhcpOptionsTmp, d := SubnetDhcpOptionsAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		dhcpOptionsTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.SubnetDhcpOptions).GetSchema().Attributes),
			*dhcpOptionsTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.DhcpOptions = dhcpOptionsTfObject
	} else {
		t.DhcpOptions = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.SubnetDhcpOptions).GetSchema().Attributes))
	}

	return &t, diags
}
