// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PostgresNetworkAddress struct {
	Ref            types.String `tfsdk:"ref"`
	Spec           types.Object `tfsdk:"spec"`
	ExternalAccess types.Object `tfsdk:"external_access"`
}

func (s *PostgresNetworkAddress) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описание адресов, в которые будет трансляция из service-vpc.`,
		Attributes: map[string]schema.Attribute{
			"ref": schema.StringAttribute{
				MarkdownDescription: `Идентификатор адреса для подключения к узлу`,
				Optional:            true,
			},
			"spec": schema.SingleNestedAttribute{
				Attributes:          new(PostgresNetworkAddressSpec).GetSchema().Attributes,
				MarkdownDescription: `Описание подсети пользователя, используемой для подключения к узлам`,
				Optional:            true,
			},
			"external_access": schema.SingleNestedAttribute{
				Attributes:          new(PostgresExternalAccessSpec).GetSchema().Attributes,
				MarkdownDescription: `Описание адреса для внешнего подключения к кластеру`,
				Optional:            true,
			},
		},
	}
}
