// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PostgresClusterBackupDaily struct {
	Hour types.Int64 `tfsdk:"hour"`
}

func (s *PostgresClusterBackupDaily) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Спецификация ежедневного автоматического бэкапирования`,
		Attributes: map[string]schema.Attribute{
			"hour": schema.Int64Attribute{
				MarkdownDescription: `Час начала автоматического бэкапирования`,
				Optional:            true,
			},
		},
	}
}
