// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
)

type CryptoKeyRoleBinding struct {
	Kind             types.String `tfsdk:"kind"`
	Metadata         types.Object `tfsdk:"metadata"`
	Status           types.Object `tfsdk:"status"`
	Subject          types.Object `tfsdk:"subject"`
	Role             types.String `tfsdk:"role"`
	SupportRequestId types.String `tfsdk:"support_request_id"`
}

func (s *CryptoKeyRoleBinding) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"kind": schema.StringAttribute{
				Computed: true,
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes,
				MarkdownDescription: `Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров.`,
				Computed:            true,
			},
			"status": schema.SingleNestedAttribute{
				Attributes: new(tfcommon.CommonRoleBindingStatus).GetSchema().Attributes,
				Computed:   true,
			},
			"subject": schema.SingleNestedAttribute{
				Attributes: new(tfcommon.CommonRoleBindingSpecSubject).GetSchema().Attributes,
				Computed:   true,
			},
			"role": schema.StringAttribute{
				MarkdownDescription: `Роль, определяющая права субъекта на ресурс`,
				Computed:            true,
			},
			"support_request_id": schema.StringAttribute{
				MarkdownDescription: `Идентификатор запроса в службу поддержки, в рамках которого был создан биндинг`,
				Computed:            true,
			},
		},
	}
}
