// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CryptoKeyVersionsListDataSourceModel struct {
	ProjectParam types.String `tfsdk:"project"`
	KeyParam     types.String `tfsdk:"key"`
	FilterParam  types.String `tfsdk:"filter"`
	OrderByParam types.String `tfsdk:"order_by"`
	CryptoKeyVersionList
}
