// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CryptoKeyModel struct {
	KeyParam     types.String `tfsdk:"key"`
	ProjectParam types.String `tfsdk:"project"`
	CryptoKey
}
