// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/secretmanager/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/secretmanager/converter"
)

func TestSecretRoleBindingAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.SecretRoleBindingOptionalResponse{}
	_, diags := conv.SecretRoleBindingAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
