// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	apimodel "go.mws.cloud/go-sdk/service/compute/model"
	"go.mws.cloud/go-sdk/service/resources/references/compute"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/compute/model"
)

func DiskBackupSourceAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.DiskBackupSourceOptionalResponse) (*tfmodel.DiskBackupSource, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.DiskBackupSource

	if val, ok := am.Disk.Get(); ok {
		diskTmp, d := DiskBackupSourceDiskAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		diskTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.DiskBackupSourceDisk).GetSchema().Attributes),
			*diskTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Disk = diskTfObject
	} else {
		t.Disk = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.DiskBackupSourceDisk).GetSchema().Attributes))
	}

	return &t, diags
}

func DiskBackupSourceTFToAPIRequestModel(ctx context.Context, plan *tfmodel.DiskBackupSource) (*apimodel.DiskBackupSourceRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.DiskBackupSourceRequest

	if !plan.Disk.IsNull() && !plan.Disk.IsUnknown() {
		diskPlan := tfmodel.DiskBackupSourceDisk{}
		diskPlanDiag := plan.Disk.As(ctx, &diskPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, diskPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		diskTmp, diskDiag := DiskBackupSourceDiskTFToAPIRequestModel(ctx, &diskPlan)
		diags = append(diags, diskDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Disk = diskTmp
	}

	return &am, diags
}

func DiskBackupSourceDiskAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.DiskBackupSourceDiskOptionalResponse) (*tfmodel.DiskBackupSourceDisk, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.DiskBackupSourceDisk

	t.Id = types.StringValue(am.Id.Path())

	return &t, diags
}

func DiskBackupSourceDiskTFToAPIRequestModel(ctx context.Context, plan *tfmodel.DiskBackupSourceDisk) (*apimodel.DiskBackupSourceDiskRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.DiskBackupSourceDiskRequest

	if !plan.Id.IsNull() && !plan.Id.IsUnknown() {
		idRef, err := compute.ParseDiskRef(ctx, plan.Id.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Id = idRef
	}

	return &am, diags
}
