// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AddressGroupModel struct {
	AddressGroupParam types.String `tfsdk:"address_group"`
	NetworkParam      types.String `tfsdk:"network"`
	ProjectParam      types.String `tfsdk:"project"`
	VpcAddressGroup
}
