// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ExternalAddressDataSourceModel struct {
	ProjectParam         types.String `tfsdk:"project"`
	ExternalAddressParam types.String `tfsdk:"external_address"`
	ExternalAddress
}
