// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FirewallRuleDestinationSpec struct {
	Cidrs types.List `tfsdk:"cidrs"`
}

func (s *FirewallRuleDestinationSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Спецификация группы адресов.`,
		Attributes: map[string]schema.Attribute{
			"cidrs": schema.ListAttribute{
				ElementType:         types.StringType,
				MarkdownDescription: `Диапазоны IPv4 адресов, которые входят в группу.`,
				Computed:            true,
			},
		},
	}
}
