// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
)

type Network struct {
	Kind           types.String `tfsdk:"kind"`
	Metadata       types.Object `tfsdk:"metadata"`
	Status         types.Object `tfsdk:"status"`
	Mtu            types.Int64  `tfsdk:"mtu"`
	InternetAccess types.Bool   `tfsdk:"internet_access"`
}

func (s *Network) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Сеть — это виртуальный аналог физической сети на базе инфраструктуры MWS`,
		Attributes: map[string]schema.Attribute{
			"kind": schema.StringAttribute{
				Computed: true,
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes,
				MarkdownDescription: `Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров.`,
				Computed:            true,
			},
			"status": schema.SingleNestedAttribute{
				Attributes: new(NetworkStatus).GetSchema().Attributes,
				Computed:   true,
			},
			"mtu": schema.Int64Attribute{
				Computed: true,
			},
			"internet_access": schema.BoolAttribute{
				Computed: true,
			},
		},
	}
}
