// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NlbAddressGroupStatus struct {
	Ref types.String `tfsdk:"ref"`
}

func (s *NlbAddressGroupStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Статус группы адресов балансировщика.`,
		Attributes: map[string]schema.Attribute{
			"ref": schema.StringAttribute{
				MarkdownDescription: `Ссылка на группу адресов.`,
				Computed:            true,
			},
		},
	}
}
