// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NlbHealthCheckProtocol struct {
	Http  types.Object `tfsdk:"http"`
	Https types.Object `tfsdk:"https"`
	Tcp   types.Object `tfsdk:"tcp"`
}

func (s *NlbHealthCheckProtocol) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Конфигурация протокола проверки работоспособности.`,
		Attributes: map[string]schema.Attribute{
			"http": schema.SingleNestedAttribute{
				Attributes:          new(NlbHealthCheckHttp).GetSchema().Attributes,
				MarkdownDescription: `Конфигурация проверки работоспособности по протоколу HTTP.`,
				Computed:            true,
			},
			"https": schema.SingleNestedAttribute{
				Attributes:          new(NlbHealthCheckHttps).GetSchema().Attributes,
				MarkdownDescription: `Конфигурация проверки работоспособности по протоколу HTTPS.`,
				Computed:            true,
			},
			"tcp": schema.SingleNestedAttribute{
				Attributes:          new(NlbHealthCheckTcp).GetSchema().Attributes,
				MarkdownDescription: `Конфигурация проверки работоспособности по протоколу TCP.`,
				Computed:            true,
			},
		},
	}
}
