// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NlbListenerExternal struct {
	Address types.Object `tfsdk:"address"`
}

func (s *NlbListenerExternal) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Конфигурация IP-адреса внутреннего балансировщика.`,
		Attributes: map[string]schema.Attribute{
			"address": schema.SingleNestedAttribute{
				Attributes:          new(ResourceExternalAddressSpecOrRef).GetSchema().Attributes,
				MarkdownDescription: `Описывает ссылку на внешний адрес или спецификацию внешнего адреса как дополнительный ресурс.`,
				Computed:            true,
			},
		},
	}
}
