// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
)

func TestCommonTypedResourceMetadataAPIToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := commonmodel.CommonTypedResourceMetadata{}
	_, diags := commonconv.CommonTypedResourceMetadataAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestCommonTypedResourceMetadataAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := commonmodel.CommonTypedResourceMetadataResponse{}
	_, diags := commonconv.CommonTypedResourceMetadataAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestCommonTypedResourceMetadataAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := commonmodel.CommonTypedResourceMetadataOptionalResponse{}
	_, diags := commonconv.CommonTypedResourceMetadataAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
