// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
)

func TestCommonTypedResourceMetadataAPIToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := commonmodel.CommonTypedResourceMetadata{}
	_, diags := commonconv.CommonTypedResourceMetadataAPIToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestCommonTypedResourceMetadataAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := commonmodel.CommonTypedResourceMetadataResponse{}
	_, diags := commonconv.CommonTypedResourceMetadataAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestCommonTypedResourceMetadataAPIOptionalResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := commonmodel.CommonTypedResourceMetadataOptionalResponse{}
	_, diags := commonconv.CommonTypedResourceMetadataAPIOptionalResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
