// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/iam"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
)

func TestCommonRoleBindingFederationAPIToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := commonapimodel.CommonRoleBindingFederation{}
	_, diags := commonconv.CommonRoleBindingFederationAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestCommonRoleBindingFederationAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := commonapimodel.CommonRoleBindingFederationResponse{}
	_, diags := commonconv.CommonRoleBindingFederationAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestCommonRoleBindingFederationAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := commonapimodel.CommonRoleBindingFederationOptionalResponse{}
	_, diags := commonconv.CommonRoleBindingFederationAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestCommonRoleBindingFederationConverters(t *testing.T) {
	t.Parallel()
	emptyApiModel := commonapimodel.CommonRoleBindingFederation{
		Id: iam.NewMustUserFederationRef("organizationID", "userFederationID"),
	}

	tfModel, diags := commonconv.CommonRoleBindingFederationAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())

	result, diags := commonconv.CommonRoleBindingFederationTFToAPIModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	require.Equal(t, emptyApiModel, *result)
}

func TestCommonRoleBindingFederationResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := commonapimodel.CommonRoleBindingFederationRequest{
		Id: iam.NewMustUserFederationRef("organizationID", "userFederationID"),
	}

	emptyApiModelResponse, err := commonapimodel.CommonRoleBindingFederationRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := commonconv.CommonRoleBindingFederationAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := commonconv.CommonRoleBindingFederationTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := commonapimodel.CommonRoleBindingFederationRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestCommonRoleBindingFederationOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := commonapimodel.CommonRoleBindingFederationRequest{
		Id: iam.NewMustUserFederationRef("organizationID", "userFederationID"),
	}

	emptyApiModelResponse, err := commonapimodel.CommonRoleBindingFederationRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := commonconv.CommonRoleBindingFederationAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := commonconv.CommonRoleBindingFederationTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := commonapimodel.CommonRoleBindingFederationRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}
