// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/common/model"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
)

func TestTypedResourceMetadataAPIToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.TypedResourceMetadata{}
	_, diags := commonconv.TypedResourceMetadataAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestTypedResourceMetadataAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.TypedResourceMetadataResponse{}
	_, diags := commonconv.TypedResourceMetadataAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestTypedResourceMetadataAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.TypedResourceMetadataOptionalResponse{}
	_, diags := commonconv.TypedResourceMetadataAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestTypedResourceMetadataConverters(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.TypedResourceMetadata{}

	tfModel, diags := commonconv.TypedResourceMetadataAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())

	result, diags := commonconv.TypedResourceMetadataTFToAPIModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	require.Equal(t, emptyApiModel, *result)
}

func TestTypedResourceMetadataResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.TypedResourceMetadataRequest{}

	emptyApiModelResponse, err := apimodel.TypedResourceMetadataRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := commonconv.TypedResourceMetadataAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := commonconv.TypedResourceMetadataTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.TypedResourceMetadataRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestTypedResourceMetadataOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.TypedResourceMetadataRequest{}

	emptyApiModelResponse, err := apimodel.TypedResourceMetadataRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := commonconv.TypedResourceMetadataAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := commonconv.TypedResourceMetadataTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.TypedResourceMetadataRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}
