// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
)

func TestVpcAddressGroupSpecOrRefAPIToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := commonmodel.VpcAddressGroupSpecOrRef{}
	_, diags := commonconv.VpcAddressGroupSpecOrRefAPIToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestVpcAddressGroupSpecOrRefAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := commonmodel.VpcAddressGroupSpecOrRefResponse{}
	_, diags := commonconv.VpcAddressGroupSpecOrRefAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}

func TestVpcAddressGroupSpecOrRefAPIOptionalResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := commonmodel.VpcAddressGroupSpecOrRefOptionalResponse{}
	_, diags := commonconv.VpcAddressGroupSpecOrRefAPIOptionalResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
