// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/certmanager/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/certmanager/converter"
)

func TestCertificateManagementTypeAPIToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.CertificateManagementType("")
	_, diags := conv.CertificateManagementTypeAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
