// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/certmanager/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/certmanager/converter"
)

func TestCertificateManagedSpecAPIOptionalResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.CertificateManagedSpecOptionalResponse{}
	_, diags := conv.CertificateManagedSpecAPIOptionalResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
