// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/certmanager/model"
	conv "go.mws.cloud/terraform-provider-mws/service/datasources/certmanager/converter"
)

func TestCertificateStatusAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.CertificateStatusResponse{}
	_, diags := conv.CertificateStatusAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
