// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	apimodel "go.mws.cloud/go-sdk/service/nlb/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/nlb/model"
)

func NlbHealthCheckTcpAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.NlbHealthCheckTcpOptionalResponse) (*tfmodel.NlbHealthCheckTcp, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NlbHealthCheckTcp

	t.Port = types.Int64Value(int64(am.Port))

	return &t, diags
}

func NlbHealthCheckTcpTFToAPIRequestModel(ctx context.Context, plan *tfmodel.NlbHealthCheckTcp) (*apimodel.NlbHealthCheckTcpRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.NlbHealthCheckTcpRequest

	if !plan.Port.IsNull() && !plan.Port.IsUnknown() {
		am.Port = int(plan.Port.ValueInt64())
	}

	return &am, diags
}

func NlbHealthCheckTcpTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.NlbHealthCheckTcp) (*apimodel.UpdateNlbHealthCheckTcpRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.NlbHealthCheckTcp{}
	}

	var diags tfdiag.Diagnostics
	var am apimodel.UpdateNlbHealthCheckTcpRequest

	if !plan.Port.Equal(state.Port) {
		if !plan.Port.IsNull() && !plan.Port.IsUnknown() {
			am.Port.SetTo(int(plan.Port.ValueInt64()))
		}
	}

	return &am, diags
}
