// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	"go.mws.cloud/go-sdk/service/nlb/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/resources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/nlb/model"
)

func NlbListenerInternalAPIOptionalResponseToTFModel(ctx context.Context, am *model.NlbListenerInternalOptionalResponse) (*tfmodel.NlbListenerInternal, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NlbListenerInternal

	addressTmp, d := commonconv.ResourceAddressSpecOrRefAPIOptionalResponseToTFModel(ctx, &am.Address)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	addressTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfcommon.ResourceAddressSpecOrRef).GetSchema().Attributes),
		*addressTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.Address = addressTfObject

	return &t, diags
}

func NlbListenerInternalTFToAPIRequestModel(ctx context.Context, plan *tfmodel.NlbListenerInternal) (*model.NlbListenerInternalRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am model.NlbListenerInternalRequest

	if !plan.Address.IsNull() && !plan.Address.IsUnknown() {
		addressPlan := tfcommon.ResourceAddressSpecOrRef{}
		addressPlanDiag := plan.Address.As(ctx, &addressPlan, basetypes.ObjectAsOptions{})
		diags = append(diags, addressPlanDiag...)
		if diags.HasError() {
			return nil, diags
		}

		addressTmp, addressDiag := commonconv.ResourceAddressSpecOrRefTFToAPIRequestModel(ctx, &addressPlan)
		diags = append(diags, addressDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Address = *addressTmp
	}

	return &am, diags
}

func NlbListenerInternalTFToAPIUpdateRequestModel(ctx context.Context, plan, state *tfmodel.NlbListenerInternal) (*model.UpdateNlbListenerInternalRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}
	if state == nil {
		state = &tfmodel.NlbListenerInternal{}
	}

	var diags tfdiag.Diagnostics
	var am model.UpdateNlbListenerInternalRequest

	if !plan.Address.Equal(state.Address) {
		if !plan.Address.IsNull() && !plan.Address.IsUnknown() {
			addressPlan := tfcommon.ResourceAddressSpecOrRef{}
			addressPlanDiag := plan.Address.As(ctx, &addressPlan, basetypes.ObjectAsOptions{})
			diags = append(diags, addressPlanDiag...)
			if diags.HasError() {
				return nil, diags
			}

			addressState := tfcommon.ResourceAddressSpecOrRef{}
			if !state.Address.IsNull() && !state.Address.IsUnknown() {
				addressStateDiag := state.Address.As(ctx, &addressState, basetypes.ObjectAsOptions{})
				diags = append(diags, addressStateDiag...)
				if diags.HasError() {
					return nil, diags
				}
			}

			addressTmp, addressDiag := commonconv.ResourceAddressSpecOrRefTFToAPIUpdateRequestModel(ctx, &addressPlan, &addressState)
			diags = append(diags, addressDiag...)
			if diags.HasError() {
				return nil, diags
			}
			am.Address.SetTo(*addressTmp)
		}
	}

	return &am, diags
}
