// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
)

func ResourceExternalAddressSpecAPIToTFModel(ctx context.Context, am *commonapimodel.ResourceExternalAddressSpec) (*tfcommon.ResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressSpec

	if am.NatGateway != nil {
		t.NatGateway = types.StringPointerValue(ptr.Get(am.NatGateway.Path()))
	} else {
		t.NatGateway = types.StringNull()
	}

	return &t, diags
}

func ResourceExternalAddressSpecAPIResponseToTFModel(ctx context.Context, am *commonapimodel.ResourceExternalAddressSpecResponse) (*tfcommon.ResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressSpec

	if am.NatGateway != nil {
		t.NatGateway = types.StringPointerValue(ptr.Get(am.NatGateway.Path()))
	} else {
		t.NatGateway = types.StringNull()
	}

	return &t, diags
}

func ResourceExternalAddressSpecAPIOptionalResponseToTFModel(ctx context.Context, am *commonapimodel.ResourceExternalAddressSpecOptionalResponse) (*tfcommon.ResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfcommon.ResourceExternalAddressSpec

	if val, ok := am.NatGateway.Get(); ok {
		t.NatGateway = types.StringPointerValue(ptr.Get(val.Path()))
	} else {
		t.NatGateway = types.StringNull()
	}

	return &t, diags
}

func ResourceExternalAddressSpecTFToAPIModel(ctx context.Context, plan *tfcommon.ResourceExternalAddressSpec) (*commonapimodel.ResourceExternalAddressSpec, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.ResourceExternalAddressSpec

	if !plan.NatGateway.IsNull() && !plan.NatGateway.IsUnknown() {
		natGatewayRef, err := vpc.ParseNatGatewayRef(ctx, plan.NatGateway.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.NatGateway = &natGatewayRef
	}

	return &am, diags
}

func ResourceExternalAddressSpecTFToAPIRequestModel(ctx context.Context, plan *tfcommon.ResourceExternalAddressSpec) (*commonapimodel.ResourceExternalAddressSpecRequest, tfdiag.Diagnostics) {
	if plan == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am commonapimodel.ResourceExternalAddressSpecRequest

	if !plan.NatGateway.IsNull() && !plan.NatGateway.IsUnknown() {
		natGatewayRef, err := vpc.ParseNatGatewayRef(ctx, plan.NatGateway.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.NatGateway = &natGatewayRef
	}

	return &am, diags
}
