// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
)

func TestBackupTriggerAPIToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.BackupTrigger("")
	_, diags := conv.BackupTriggerAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestBackupTriggerConverters(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.BackupTrigger("")

	tfModel, diags := conv.BackupTriggerAPIToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())

	result, diags := conv.BackupTriggerTFToAPIModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	require.Equal(t, emptyApiModel, *result)
}
