// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/model"
)

func TestPostgresExternalAccessSpecAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.PostgresExternalAccessSpecResponse{}
	_, diags := conv.PostgresExternalAccessSpecAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestPostgresExternalAccessSpecResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.PostgresExternalAccessSpecRequest{
		Allowed: false,
	}

	emptyApiModelResponse, err := model.PostgresExternalAccessSpecRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PostgresExternalAccessSpecAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PostgresExternalAccessSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.PostgresExternalAccessSpecRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdatePostgresExternalAccessSpecRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.PostgresExternalAccessSpec
	var stateTfModel tfmodel.PostgresExternalAccessSpec

	expectedUpdateModel := &model.UpdatePostgresExternalAccessSpecRequest{}

	result, diags := conv.PostgresExternalAccessSpecTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
