// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/model"
)

func TestPostgresUserAdditionalRoleResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.PostgresUserAdditionalRoleRequest{}

	apiModelResponse, err := model.PostgresUserAdditionalRoleRequestToResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PostgresUserAdditionalRoleAPIResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PostgresUserAdditionalRoleTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.PostgresUserAdditionalRoleRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdatePostgresUserAdditionalRoleRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.PostgresUserAdditionalRole
	var stateTfModel tfmodel.PostgresUserAdditionalRole

	expectedUpdateModel := &model.UpdatePostgresUserAdditionalRoleRequest{}

	result, diags := conv.PostgresUserAdditionalRoleTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
