// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
)

func TestPostgresClusterStatusBackupDailyAPIResponseToTFModel(t *testing.T) {
	t.Parallel()
	apiModel := model.PostgresClusterStatusBackupDailyResponse{
		Hour: 0,
	}
	_, diags := conv.PostgresClusterStatusBackupDailyAPIResponseToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())
}
