// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	commonapimodel "go.mws.cloud/go-sdk/service/common/model"
	apimodel "go.mws.cloud/go-sdk/service/mpostgres/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/model"
)

func TestPostgresBackupAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.PostgresBackupResponse{}
	_, diags := conv.PostgresBackupAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestPostgresBackupResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.PostgresBackupRequest{}

	emptyApiModelResponse, err := apimodel.PostgresBackupRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PostgresBackupAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PostgresBackupTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.PostgresBackupRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdatePostgresBackupRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.PostgresBackup
	var stateTfModel tfmodel.PostgresBackup
	stateTfModel.Metadata = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfmodel.PostgresBackupMetadata).GetSchema().Attributes))

	expectedUpdateModel := &apimodel.UpdatePostgresBackupRequest{
		Metadata: optional.OptionalNil[apimodel.UpdatePostgresBackupMetadataRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.PostgresBackupTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}

func TestPostgresBackupMetadataAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.PostgresBackupMetadataResponse{}
	_, diags := conv.PostgresBackupMetadataAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestPostgresBackupMetadataResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.PostgresBackupMetadataRequest{
		TypedResourceMetadataRequest: commonapimodel.TypedResourceMetadataRequest{},
	}

	emptyApiModelResponse, err := apimodel.PostgresBackupMetadataRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PostgresBackupMetadataAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PostgresBackupMetadataTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.PostgresBackupMetadataRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdatePostgresBackupMetadataRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.PostgresBackupMetadata
	var stateTfModel tfmodel.PostgresBackupMetadata

	expectedUpdateModel := &apimodel.UpdatePostgresBackupMetadataRequest{}

	result, diags := conv.PostgresBackupMetadataTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}

func TestPostgresBackupSpecAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.PostgresBackupSpecResponse{}
	_, diags := conv.PostgresBackupSpecAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestPostgresBackupSpecResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.PostgresBackupSpecRequest{}

	emptyApiModelResponse, err := apimodel.PostgresBackupSpecRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PostgresBackupSpecAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PostgresBackupSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.PostgresBackupSpecRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdatePostgresBackupSpecRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.PostgresBackupSpec
	var stateTfModel tfmodel.PostgresBackupSpec

	expectedUpdateModel := &apimodel.UpdatePostgresBackupSpecRequest{}

	result, diags := conv.PostgresBackupSpecTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
