// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
)

func TestPostgresUserAccessControlPolicyConverters(t *testing.T) {
	t.Parallel()
	apiModel := model.PostgresUserAccessControlPolicy("")

	tfModel, diags := conv.PostgresUserAccessControlPolicyAPIToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())

	result, diags := conv.PostgresUserAccessControlPolicyTFToAPIModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	require.Equal(t, apiModel, *result)
}
