// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/model"
)

func TestPostgresInstanceResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.PostgresInstanceRequest{
		Count: 0,
	}

	apiModelResponse, err := model.PostgresInstanceRequestToResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PostgresInstanceAPIResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PostgresInstanceTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.PostgresInstanceRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdatePostgresInstanceRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.PostgresInstance
	var stateTfModel tfmodel.PostgresInstance

	expectedUpdateModel := &model.UpdatePostgresInstanceRequest{}

	result, diags := conv.PostgresInstanceTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
