// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/mpostgres/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mpostgres/converter"
)

func TestPostgresInstanceAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.PostgresInstanceResponse{}
	_, diags := conv.PostgresInstanceAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestPostgresInstanceResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.PostgresInstanceRequest{
		Count: 0,
	}

	emptyApiModelResponse, err := apimodel.PostgresInstanceRequestToResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PostgresInstanceAPIResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PostgresInstanceTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.PostgresInstanceRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}
