// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	"go.mws.cloud/go-sdk/service/queue/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/queue/model"
)

func ConsumerGroupStatusAPIResponseToTFModel(ctx context.Context, am *model.ConsumerGroupStatusResponse) (*tfmodel.ConsumerGroupStatus, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ConsumerGroupStatus

	readyTmp, d := commonconv.ResourceStatusReadyAPIResponseToTFModel(ctx, &am.Ready)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	readyTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfcommon.ResourceStatusReady).GetSchema().Attributes),
		*readyTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.Ready = readyTfObject

	if am.State != nil {
		stateTmp, d := ConsumerGroupStateAPIToTFModel(ctx, am.State)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.State = stateTmp
	} else {
		t.State = types.StringNull()
	}

	if am.GenerationId != nil {
		t.GenerationId = types.Int64PointerValue(ptr.Get(int64(*am.GenerationId)))
	} else {
		t.GenerationId = types.Int64Null()
	}

	if am.ProtocolType != nil {
		t.ProtocolType = types.StringPointerValue(am.ProtocolType)
	} else {
		t.ProtocolType = types.StringNull()
	}

	if am.ProtocolData != nil {
		t.ProtocolData = types.StringPointerValue(am.ProtocolData)
	} else {
		t.ProtocolData = types.StringNull()
	}

	if am.Members != nil {
		members := make([]tfmodel.ConsumerGroupMember, 0, len(am.Members))

		for _, entity := range am.Members {
			tmp, d := ConsumerGroupMemberAPIResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			members = append(members, *tmp)
		}

		membersList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ConsumerGroupMember).GetSchema().Attributes),
		}, members)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Members = membersList
	} else {
		t.Members = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.ConsumerGroupMember).GetSchema().Attributes),
		})
	}

	return &t, diags
}
