// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	apimodel "go.mws.cloud/go-sdk/service/mk8s/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/model"
)

func TestClusterPublicEndpointSpecOrRefAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.ClusterPublicEndpointSpecOrRefOptionalResponse{}
	_, diags := conv.ClusterPublicEndpointSpecOrRefAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestClusterPublicEndpointSpecOrRefOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.ClusterPublicEndpointSpecOrRefRequest{}

	emptyApiModelResponse, err := apimodel.ClusterPublicEndpointSpecOrRefRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.ClusterPublicEndpointSpecOrRefAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.ClusterPublicEndpointSpecOrRefTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.ClusterPublicEndpointSpecOrRefRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateClusterPublicEndpointSpecOrRefRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.ClusterPublicEndpointSpecOrRef
	var stateTfModel tfmodel.ClusterPublicEndpointSpecOrRef
	stateTfModel.Ref = types.StringValue("")
	stateTfModel.Spec = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfmodel.ClusterPublicEndpointSpec).GetSchema().Attributes))

	expectedUpdateModel := &apimodel.UpdateClusterPublicEndpointSpecOrRefRequest{
		Ref: optional.OptionalNil[vpc.ExternalAddressRef]{
			Set:  true,
			Null: true,
		},
		Spec: optional.OptionalNil[apimodel.UpdateClusterPublicEndpointSpecRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.ClusterPublicEndpointSpecOrRefTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
