// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/mk8s/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/model"
)

func TestNodeGroupVersionControlSpecOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.NodeGroupVersionControlSpecRequest{}

	apiModelResponse, err := model.NodeGroupVersionControlSpecRequestToOptionalResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.NodeGroupVersionControlSpecAPIOptionalResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.NodeGroupVersionControlSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.NodeGroupVersionControlSpecRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdateNodeGroupVersionControlSpecRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.NodeGroupVersionControlSpec
	var stateTfModel tfmodel.NodeGroupVersionControlSpec
	stateTfModel.MaintenanceWindow = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfcommon.MaintenanceWindow).GetSchema().Attributes))

	expectedUpdateModel := &model.UpdateNodeGroupVersionControlSpecRequest{
		MaintenanceWindow: optional.OptionalNil[commonmodel.UpdateMaintenanceWindowRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.NodeGroupVersionControlSpecTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
