// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mk8s/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/model"
)

func TestNodeTaintSpecOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.NodeTaintSpecRequest{
		Key:    "key",
		Value:  "value",
		Effect: "",
	}

	apiModelResponse, err := model.NodeTaintSpecRequestToOptionalResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.NodeTaintSpecAPIOptionalResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.NodeTaintSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.NodeTaintSpecRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestNodeTaintSpecResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.NodeTaintSpecRequest{
		Key:    "key",
		Value:  "value",
		Effect: "",
	}

	apiModelResponse, err := model.NodeTaintSpecRequestToResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.NodeTaintSpecAPIResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.NodeTaintSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.NodeTaintSpecRequestToResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdateNodeTaintSpecRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.NodeTaintSpec
	var stateTfModel tfmodel.NodeTaintSpec

	expectedUpdateModel := &model.UpdateNodeTaintSpecRequest{}

	result, diags := conv.NodeTaintSpecTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
