// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/pkg/optional"
	"go.mws.cloud/go-sdk/service/mk8s/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mk8s/model"
)

func TestPluginsSpecOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.PluginsSpecRequest{}

	apiModelResponse, err := model.PluginsSpecRequestToOptionalResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PluginsSpecAPIOptionalResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PluginsSpecTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.PluginsSpecRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdatePluginsSpecRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.PluginsSpec
	var stateTfModel tfmodel.PluginsSpec
	stateTfModel.Cni = tfconv.MustKnownObjectValue(tfconv.GetAttributesTypes(new(tfmodel.PluginsSpecCni).GetSchema().Attributes))

	expectedUpdateModel := &model.UpdatePluginsSpecRequest{
		Cni: optional.OptionalNil[model.UpdatePluginsSpecCniRequest]{
			Set:  true,
			Null: true,
		},
	}

	result, diags := conv.PluginsSpecTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}

func TestPluginsSpecCniOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	apiModelRequest := model.PluginsSpecCniRequest{}

	apiModelResponse, err := model.PluginsSpecCniRequestToOptionalResponse(&apiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.PluginsSpecCniAPIOptionalResponseToTFModel(context.Background(), apiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.PluginsSpecCniTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.PluginsSpecCniRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *apiModelResponse, *result)
}

func TestUpdatePluginsSpecCniRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.PluginsSpecCni
	var stateTfModel tfmodel.PluginsSpecCni

	expectedUpdateModel := &model.UpdatePluginsSpecCniRequest{}

	result, diags := conv.PluginsSpecCniTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
