// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/resources/common/model"
)

type AuthorizedKeyStatus struct {
	tfcommon.ResourceStatus
	PrivateKey     types.String `tfsdk:"private_key"`
	PrivateKeyFile types.String `tfsdk:"private_key_file"`
	PublicKey      types.String `tfsdk:"public_key"`
	LastAuthTime   types.String `tfsdk:"last_auth_time"`
	Active         types.Bool   `tfsdk:"active"`
}

func (s *AuthorizedKeyStatus) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: ``,
		Attributes: map[string]schema.Attribute{
			"ready": schema.SingleNestedAttribute{
				Attributes:          new(tfcommon.ResourceStatusReady).GetSchema().Attributes,
				MarkdownDescription: `Информация о статусе реконсиляции`,
				Computed:            true,
			},
			"private_key": schema.StringAttribute{
				MarkdownDescription: `Закрытый ключ, сгенерированный на стороне сервиса`,
				Sensitive:           true,
				Computed:            true,
			},
			"private_key_file": schema.StringAttribute{
				MarkdownDescription: `Файл с закрытым ключом, сгенерированным на стороне сервиса, в формате base64`,
				Sensitive:           true,
				Computed:            true,
			},
			"public_key": schema.StringAttribute{
				MarkdownDescription: `Открытый ключ, сгенерированный на стороне сервиса`,
				Computed:            true,
			},
			"last_auth_time": schema.StringAttribute{
				MarkdownDescription: `Время последней аутентификации

Дата в формате RFC3339. Пример: 2006-01-02T15:04:05Z07:00`,
				Computed: true,
			},
			"active": schema.BoolAttribute{
				MarkdownDescription: `Флаг активности ключа`,
				Computed:            true,
			},
		},
	}
}
