// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ServiceAccountModel struct {
	ProjectParam        types.String   `tfsdk:"project"`
	ServiceAccountParam types.String   `tfsdk:"service_account"`
	Timeouts            timeouts.Value `tfsdk:"timeouts"`
	ID                  types.String   `tfsdk:"id"`
	ServiceAccount
}
