// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"go.mws.cloud/go-sdk/service/certmanager/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/certmanager/model"
)

func CertificateManagedSpecAPIOptionalResponseToTFModel(ctx context.Context, am *model.CertificateManagedSpecOptionalResponse) (*tfmodel.CertificateManagedSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.CertificateManagedSpec

	if val, ok := am.PreferredChallengeType.Get(); ok {
		preferredChallengeTypeTmp, d := CertificateChallengeTypeAPIToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.PreferredChallengeType = preferredChallengeTypeTmp
	} else {
		t.PreferredChallengeType = types.StringNull()
	}

	if val, ok := am.Provider.Get(); ok {
		providerTmp, d := CertificateProviderAPIToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Provider = providerTmp
	} else {
		t.Provider = types.StringNull()
	}

	if val, ok := am.Issuer.Get(); ok {
		issuerTmp, d := CertificateManagedSpecIssuerAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		issuerTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.CertificateManagedSpecIssuer).GetSchema().Attributes),
			*issuerTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Issuer = issuerTfObject
	} else {
		t.Issuer = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.CertificateManagedSpecIssuer).GetSchema().Attributes))
	}

	if val, ok := am.Domains.Get(); ok {
		domains := make([]types.String, 0, len(val))

		for _, entity := range val {
			domains = append(domains, types.StringValue(entity))
		}

		domainsList, d := types.ListValueFrom(ctx, types.StringType, domains)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Domains = domainsList
	} else {
		t.Domains = types.ListNull(types.StringType)
	}

	return &t, diags
}
