// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type BackupModel struct {
	BackupParam  types.String `tfsdk:"backup"`
	ClusterParam types.String `tfsdk:"cluster"`
	ProjectParam types.String `tfsdk:"project"`
	ClickhouseBackup
}
