// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

type ClickhouseEndpointExternalAddressSpec struct {
}

func (s *ClickhouseEndpointExternalAddressSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описание шаблона внешнего адреса, который будет использоваться при выделении адресов.`,
		Attributes:          map[string]schema.Attribute{},
	}
}
