// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ClickhouseClusterBootstrapAdminSpec struct {
	Username types.String `tfsdk:"username"`
}

func (s *ClickhouseClusterBootstrapAdminSpec) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Добавление пользователей при создании кластера Clickhouse.`,
		Attributes: map[string]schema.Attribute{
			"username": schema.StringAttribute{
				MarkdownDescription: `Имя учетной записи администратора.`,
				Computed:            true,
			},
		},
	}
}
