// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ClickhouseClusterCoordinatorResource struct {
	Type      ClickhouseCoordinatorType `tfsdk:"type"`
	Resources types.Object              `tfsdk:"resources"`
	Instances types.List                `tfsdk:"instances"`
}

func (s *ClickhouseClusterCoordinatorResource) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описание координаторов кластера.`,
		Attributes: map[string]schema.Attribute{
			"type": schema.StringAttribute{
				MarkdownDescription: `Тип координатора. Если не указано, то при наличии более одного хоста, используется Clickhouse Keeper`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"CLICKHOUSE_KEEPER",
						"ZOOKEEPER",
					),
				},
				Computed: true,
			},
			"resources": schema.SingleNestedAttribute{
				Attributes: new(ClickhouseCoordinatorHWResources).GetSchema().Attributes,
				MarkdownDescription: `Параметры виртуальной машины, где будет работать Clickhouse Keeper/Zookeeper. В случае наличия только одного хоста, 
Zookeeper/Clickhouse Keeper не поднимаются при отсутствии параметра, в противном случае, параметр должен быть задан.
`,
				Computed: true,
			},
			"instances": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: new(ClickhouseClusterCoordinatorInstanceResource).GetSchema().Attributes,
				},
				MarkdownDescription: `Описание инстансов координатора.`,
				Computed:            true,
			},
		},
	}
}
