// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ClickhouseClusterCoordinatorInstance struct {
	Count types.Int64  `tfsdk:"count"`
	Zone  types.String `tfsdk:"zone"`
}

func (s *ClickhouseClusterCoordinatorInstance) GetSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: `Описание инстанса координатора.`,
		Attributes: map[string]schema.Attribute{
			"count": schema.Int64Attribute{
				MarkdownDescription: `Количество инстансов в зоне доступности`,
				Computed:            true,
			},
			"zone": schema.StringAttribute{
				MarkdownDescription: `Зона доступности`,
				Computed:            true,
			},
		},
	}
}
