// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"go.mws.cloud/go-sdk/pkg/apimodels/cidraddress"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	apimodel "go.mws.cloud/go-sdk/service/mk8s/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/mk8s/model"
)

func ClusterSpecNetworkAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.ClusterSpecNetworkOptionalResponse) (*tfmodel.ClusterSpecNetwork, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ClusterSpecNetwork

	primaryEndpointTmp, d := ClusterPrimaryEndpointSpecOrRefAPIOptionalResponseToTFModel(ctx, &am.PrimaryEndpoint)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	primaryEndpointTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.ClusterPrimaryEndpointSpecOrRef).GetSchema().Attributes),
		*primaryEndpointTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.PrimaryEndpoint = primaryEndpointTfObject

	if val, ok := am.PublicEndpoint.Get(); ok {
		publicEndpointTmp, d := ClusterPublicEndpointSpecOrRefAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		publicEndpointTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClusterPublicEndpointSpecOrRef).GetSchema().Attributes),
			*publicEndpointTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.PublicEndpoint = publicEndpointTfObject
	} else {
		t.PublicEndpoint = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClusterPublicEndpointSpecOrRef).GetSchema().Attributes))
	}

	t.PodsCidr = types.StringValue(ptr.Value(am.PodsCidr.RawValue()))

	t.ServicesCidr = types.StringValue(ptr.Value(am.ServicesCidr.RawValue()))

	return &t, diags
}

func ClusterSpecNetworkTFToAPIRequestModel(ctx context.Context, tm *tfmodel.ClusterSpecNetwork) (*apimodel.ClusterSpecNetworkRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.ClusterSpecNetworkRequest

	if !tm.PrimaryEndpoint.IsNull() && !tm.PrimaryEndpoint.IsUnknown() {
		primaryEndpointTfModel := tfmodel.ClusterPrimaryEndpointSpecOrRef{}
		primaryEndpointDiag := tm.PrimaryEndpoint.As(ctx, &primaryEndpointTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, primaryEndpointDiag...)
		if diags.HasError() {
			return nil, diags
		}

		primaryEndpointTmp, primaryEndpointDiag := ClusterPrimaryEndpointSpecOrRefTFToAPIRequestModel(ctx, &primaryEndpointTfModel)
		diags = append(diags, primaryEndpointDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.PrimaryEndpoint = *primaryEndpointTmp
	}

	if !tm.PublicEndpoint.IsNull() && !tm.PublicEndpoint.IsUnknown() {
		publicEndpointTfModel := tfmodel.ClusterPublicEndpointSpecOrRef{}
		publicEndpointDiag := tm.PublicEndpoint.As(ctx, &publicEndpointTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, publicEndpointDiag...)
		if diags.HasError() {
			return nil, diags
		}

		publicEndpointTmp, publicEndpointDiag := ClusterPublicEndpointSpecOrRefTFToAPIRequestModel(ctx, &publicEndpointTfModel)
		diags = append(diags, publicEndpointDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.PublicEndpoint = publicEndpointTmp
	}

	if !tm.PodsCidr.IsNull() && !tm.PodsCidr.IsUnknown() {
		tmpPodsCidr, err := cidraddress.ParseCIDR4AddressString(tm.PodsCidr.ValueString())
		if err != nil {
			diags.AddError("CIDR4Address string parsing", err.Error())
			return nil, diags
		}
		am.PodsCidr = tmpPodsCidr
	}

	if !tm.ServicesCidr.IsNull() && !tm.ServicesCidr.IsUnknown() {
		tmpServicesCidr, err := cidraddress.ParseCIDR4AddressString(tm.ServicesCidr.ValueString())
		if err != nil {
			diags.AddError("CIDR4Address string parsing", err.Error())
			return nil, diags
		}
		am.ServicesCidr = tmpServicesCidr
	}

	return &am, diags
}
