// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	apimodel "go.mws.cloud/go-sdk/service/mk8s/model"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/mk8s/model"
)

func ClusterPublicEndpointSpecOrRefAPIOptionalResponseToTFModel(ctx context.Context, am *apimodel.ClusterPublicEndpointSpecOrRefOptionalResponse) (*tfmodel.ClusterPublicEndpointSpecOrRef, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.ClusterPublicEndpointSpecOrRef

	if val, ok := am.Ref.Get(); ok {
		t.Ref = types.StringPointerValue(ptr.Get(val.Path()))
	} else {
		t.Ref = types.StringNull()
	}

	if val, ok := am.Spec.Get(); ok {
		specTmp, d := ClusterPublicEndpointSpecAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		specTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.ClusterPublicEndpointSpec).GetSchema().Attributes),
			*specTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Spec = specTfObject
	} else {
		t.Spec = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.ClusterPublicEndpointSpec).GetSchema().Attributes))
	}

	return &t, diags
}

func ClusterPublicEndpointSpecOrRefTFToAPIRequestModel(ctx context.Context, tm *tfmodel.ClusterPublicEndpointSpecOrRef) (*apimodel.ClusterPublicEndpointSpecOrRefRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.ClusterPublicEndpointSpecOrRefRequest

	if !tm.Ref.IsNull() && !tm.Ref.IsUnknown() {
		refRef, err := vpc.ParseExternalAddressRef(ctx, tm.Ref.ValueString())
		if err != nil {
			diags.AddError("reference parsing", err.Error())
			return nil, diags
		}
		am.Ref = &refRef
	}

	if !tm.Spec.IsNull() && !tm.Spec.IsUnknown() {
		specTfModel := tfmodel.ClusterPublicEndpointSpec{}
		specDiag := tm.Spec.As(ctx, &specTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, specDiag...)
		if diags.HasError() {
			return nil, diags
		}

		specTmp, specDiag := ClusterPublicEndpointSpecTFToAPIRequestModel(ctx, &specTfModel)
		diags = append(diags, specDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Spec = specTmp
	}

	return &am, diags
}
