// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	"go.mws.cloud/go-sdk/service/mk8s/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/mk8s/model"
)

func LocalDiskSpecAPIOptionalResponseToTFModel(ctx context.Context, am *model.LocalDiskSpecOptionalResponse) (*tfmodel.LocalDiskSpec, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.LocalDiskSpec

	t.Name = types.StringValue(am.Name)

	if val, ok := am.DeviceName.Get(); ok {
		t.DeviceName = types.StringValue(val)
	} else {
		t.DeviceName = types.StringNull()
	}

	t.Size = types.StringValue(ptr.Value(am.Size.RawValue()))

	return &t, diags
}
