// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	"go.mws.cloud/go-sdk/service/mk8s/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	commonconv "go.mws.cloud/terraform-provider-mws/service/datasources/common/converter"
	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/datasources/mk8s/model"
)

func NodeGroupAPIOptionalResponseToTFModel(ctx context.Context, am *model.NodeGroupOptionalResponse) (*tfmodel.NodeGroup, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.NodeGroup

	if am.Kind != nil {
		t.Kind = types.StringPointerValue(am.Kind)
	} else {
		t.Kind = types.StringNull()
	}

	if val, ok := am.Metadata.Get(); ok {
		metadataTmp, d := commonconv.CommonTypedResourceMetadataAPIOptionalResponseToTFModel(ctx, &val)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		metadataTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes),
			*metadataTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Metadata = metadataTfObject
	} else {
		t.Metadata = types.ObjectNull(tfconv.GetAttributesTypes(new(tfcommon.CommonTypedResourceMetadata).GetSchema().Attributes))
	}

	if am.Status != nil {
		statusTmp, d := NodeGroupStatusAPIResponseToTFModel(ctx, am.Status)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		statusTfObject, d := types.ObjectValueFrom(ctx,
			tfconv.GetAttributesTypes(new(tfmodel.NodeGroupStatus).GetSchema().Attributes),
			*statusTmp)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}
		t.Status = statusTfObject
	} else {
		t.Status = types.ObjectNull(tfconv.GetAttributesTypes(new(tfmodel.NodeGroupStatus).GetSchema().Attributes))
	}

	t.Zone = types.StringValue(am.Spec.Zone)

	subnetTmp, d := NodeGroupSpecSubnetAPIOptionalResponseToTFModel(ctx, &am.Spec.Subnet)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	subnetTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecSubnet).GetSchema().Attributes),
		*subnetTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.Subnet = subnetTfObject

	vmTypeTmp, d := NodeGroupSpecVmTypeAPIOptionalResponseToTFModel(ctx, &am.Spec.VmType)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	vmTypeTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecVmType).GetSchema().Attributes),
		*vmTypeTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.VmType = vmTypeTfObject

	if val, ok := am.Spec.ImageStorageSize.Get(); ok {
		t.ImageStorageSize = types.StringValue(ptr.Value(val.RawValue()))
	} else {
		t.ImageStorageSize = types.StringNull()
	}

	if val, ok := am.Spec.ImageStorageIops.Get(); ok {
		t.ImageStorageIops = types.Int64Value(val)
	} else {
		t.ImageStorageIops = types.Int64Null()
	}

	if val, ok := am.Spec.LocalDisks.Get(); ok {
		localDisks := make([]tfmodel.LocalDiskSpec, 0, len(val))

		for _, entity := range val {
			tmp, d := LocalDiskSpecAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			localDisks = append(localDisks, *tmp)
		}

		localDisksList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.LocalDiskSpec).GetSchema().Attributes),
		}, localDisks)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.LocalDisks = localDisksList
	} else {
		t.LocalDisks = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.LocalDiskSpec).GetSchema().Attributes),
		})
	}

	scaleTmp, d := NodeGroupSpecScaleAPIOptionalResponseToTFModel(ctx, &am.Spec.Scale)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	scaleTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecScale).GetSchema().Attributes),
		*scaleTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.Scale = scaleTfObject

	if val, ok := am.Spec.Labels.Get(); ok {
		labels := make([]tfmodel.NodeLabelSpec, 0, len(val))

		for _, entity := range val {
			tmp, d := NodeLabelSpecAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			labels = append(labels, *tmp)
		}

		labelsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.NodeLabelSpec).GetSchema().Attributes),
		}, labels)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Labels = labelsList
	} else {
		t.Labels = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.NodeLabelSpec).GetSchema().Attributes),
		})
	}

	if val, ok := am.Spec.Taints.Get(); ok {
		taints := make([]tfmodel.NodeTaintSpec, 0, len(val))

		for _, entity := range val {
			tmp, d := NodeTaintSpecAPIOptionalResponseToTFModel(ctx, &entity)
			diags = append(diags, d...)
			if diags.HasError() {
				return nil, diags
			}
			taints = append(taints, *tmp)
		}

		taintsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.NodeTaintSpec).GetSchema().Attributes),
		}, taints)
		diags = append(diags, d...)
		if diags.HasError() {
			return nil, diags
		}

		t.Taints = taintsList
	} else {
		t.Taints = types.ListNull(types.ObjectType{
			AttrTypes: tfconv.GetAttributesTypes(new(tfmodel.NodeTaintSpec).GetSchema().Attributes),
		})
	}

	versionControlTmp, d := NodeGroupVersionControlSpecAPIOptionalResponseToTFModel(ctx, &am.Spec.VersionControl)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	versionControlTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.NodeGroupVersionControlSpec).GetSchema().Attributes),
		*versionControlTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.VersionControl = versionControlTfObject

	rolloutStrategyTmp, d := NodeGroupSpecRolloutStrategyAPIOptionalResponseToTFModel(ctx, &am.Spec.RolloutStrategy)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	rolloutStrategyTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecRolloutStrategy).GetSchema().Attributes),
		*rolloutStrategyTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.RolloutStrategy = rolloutStrategyTfObject

	serviceAccountTmp, d := NodeGroupSpecServiceAccountAPIOptionalResponseToTFModel(ctx, &am.Spec.ServiceAccount)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	serviceAccountTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.NodeGroupSpecServiceAccount).GetSchema().Attributes),
		*serviceAccountTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.ServiceAccount = serviceAccountTfObject

	return &t, diags
}
