// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfcommon "go.mws.cloud/terraform-provider-mws/service/datasources/common/model"
)

type TopicRoleBindingsListDataSourceModel struct {
	ProjectParam types.String `tfsdk:"project"`
	TopicParam   types.String `tfsdk:"topic"`
	FilterParam  types.String `tfsdk:"filter"`
	OrderByParam types.String `tfsdk:"order_by"`
	tfcommon.CommonRoleBindingList
}
