// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/mclickhouse/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mclickhouse/converter"
)

func TestClickhouseBackupStatusAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.ClickhouseBackupStatusResponse{}
	_, diags := conv.ClickhouseBackupStatusAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestClickhouseBackupStatusBackupAPIResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.ClickhouseBackupStatusBackupResponse{}
	_, diags := conv.ClickhouseBackupStatusBackupAPIResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}
