// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	apimodel "go.mws.cloud/go-sdk/service/mclickhouse/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mclickhouse/converter"
)

func TestClickhouseClusterBackupAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := apimodel.ClickhouseClusterBackupOptionalResponse{}
	_, diags := conv.ClickhouseClusterBackupAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestClickhouseClusterBackupOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := apimodel.ClickhouseClusterBackupRequest{}

	emptyApiModelResponse, err := apimodel.ClickhouseClusterBackupRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.ClickhouseClusterBackupAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.ClickhouseClusterBackupTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := apimodel.ClickhouseClusterBackupRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}
