// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mclickhouse/model"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mclickhouse/converter"
)

func TestClickhouseDataDiskTypeConverters(t *testing.T) {
	t.Parallel()
	apiModel := model.ClickhouseDataDiskType("")

	tfModel, diags := conv.ClickhouseDataDiskTypeAPIToTFModel(context.Background(), &apiModel)
	require.False(t, diags.HasError())

	result, diags := conv.ClickhouseDataDiskTypeTFToAPIModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	require.Equal(t, apiModel, *result)
}
