// Code generated by mwsapigen, DO NOT EDIT.

package converter_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	"go.mws.cloud/go-sdk/service/mclickhouse/model"
	"go.mws.cloud/go-sdk/service/resources/references/mclickhouse"
	conv "go.mws.cloud/terraform-provider-mws/service/resources/mclickhouse/converter"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mclickhouse/model"
)

func TestClickhouseClusterCoordinatorAPIOptionalResponseToTFModelEmpty(t *testing.T) {
	t.Parallel()
	emptyApiModel := model.ClickhouseClusterCoordinatorOptionalResponse{}
	_, diags := conv.ClickhouseClusterCoordinatorAPIOptionalResponseToTFModel(context.Background(), &emptyApiModel)
	require.False(t, diags.HasError())
}

func TestClickhouseClusterCoordinatorOptionalResponseConverters(t *testing.T) {
	t.Parallel()
	emptyApiModelRequest := model.ClickhouseClusterCoordinatorRequest{
		Resources: model.ClickhouseCoordinatorHWResourcesRequest{
			VmType: mclickhouse.NewMustClickhouseVmTypeRef("vmTypeID"),
			Disk: model.ClickhouseInstanceDiskSpecRequest{
				Size: bytesize.MustParseString("0 B"),
				Type: "",
			},
		},
		Instances: []model.ClickhouseClusterCoordinatorInstanceRequest{},
	}

	emptyApiModelResponse, err := model.ClickhouseClusterCoordinatorRequestToOptionalResponse(&emptyApiModelRequest)
	require.NoError(t, err)

	tfModel, diags := conv.ClickhouseClusterCoordinatorAPIOptionalResponseToTFModel(context.Background(), emptyApiModelResponse)
	require.False(t, diags.HasError())

	filledApiModelRequest, diags := conv.ClickhouseClusterCoordinatorTFToAPIRequestModel(context.Background(), tfModel)
	require.False(t, diags.HasError())

	result, err := model.ClickhouseClusterCoordinatorRequestToOptionalResponse(filledApiModelRequest)
	require.NoError(t, err)

	require.Equal(t, *emptyApiModelResponse, *result)
}

func TestUpdateClickhouseClusterCoordinatorRequestConverters(t *testing.T) {
	t.Parallel()

	var nullPlanTfModel tfmodel.ClickhouseClusterCoordinator
	var stateTfModel tfmodel.ClickhouseClusterCoordinator

	expectedUpdateModel := &model.UpdateClickhouseClusterCoordinatorRequest{}

	result, diags := conv.ClickhouseClusterCoordinatorTFToAPIUpdateRequestModel(context.Background(), &nullPlanTfModel, &stateTfModel)
	require.False(t, diags.HasError())

	require.Equal(t, expectedUpdateModel, result)
}
