// Code generated by mwsapigen, DO NOT EDIT.

package converter

import (
	"context"

	tfdiag "github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	apimodel "go.mws.cloud/go-sdk/service/mkafka/model"
	tfconv "go.mws.cloud/terraform-provider-mws/internal/conv"
	tfmodel "go.mws.cloud/terraform-provider-mws/service/resources/mkafka/model"
)

func KafkaInstanceAPIResponseToTFModel(ctx context.Context, am *apimodel.KafkaInstanceResponse) (*tfmodel.KafkaInstance, tfdiag.Diagnostics) {
	if am == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var t tfmodel.KafkaInstance

	brokerTmp, d := KafkaInstanceSpecAPIResponseToTFModel(ctx, &am.Broker)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	brokerTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.KafkaInstanceSpec).GetSchema().Attributes),
		*brokerTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.Broker = brokerTfObject

	controllerTmp, d := KafkaControllerInstanceSpecAPIResponseToTFModel(ctx, &am.Controller)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	controllerTfObject, d := types.ObjectValueFrom(ctx,
		tfconv.GetAttributesTypes(new(tfmodel.KafkaControllerInstanceSpec).GetSchema().Attributes),
		*controllerTmp)
	diags = append(diags, d...)
	if diags.HasError() {
		return nil, diags
	}
	t.Controller = controllerTfObject

	return &t, diags
}

func KafkaInstanceTFToAPIRequestModel(ctx context.Context, tm *tfmodel.KafkaInstance) (*apimodel.KafkaInstanceRequest, tfdiag.Diagnostics) {
	if tm == nil {
		return nil, nil
	}

	var diags tfdiag.Diagnostics
	var am apimodel.KafkaInstanceRequest

	if !tm.Broker.IsNull() && !tm.Broker.IsUnknown() {
		brokerTfModel := tfmodel.KafkaInstanceSpec{}
		brokerDiag := tm.Broker.As(ctx, &brokerTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, brokerDiag...)
		if diags.HasError() {
			return nil, diags
		}

		brokerTmp, brokerDiag := KafkaInstanceSpecTFToAPIRequestModel(ctx, &brokerTfModel)
		diags = append(diags, brokerDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Broker = *brokerTmp
	}

	if !tm.Controller.IsNull() && !tm.Controller.IsUnknown() {
		controllerTfModel := tfmodel.KafkaControllerInstanceSpec{}
		controllerDiag := tm.Controller.As(ctx, &controllerTfModel, basetypes.ObjectAsOptions{})
		diags = append(diags, controllerDiag...)
		if diags.HasError() {
			return nil, diags
		}

		controllerTmp, controllerDiag := KafkaControllerInstanceSpecTFToAPIRequestModel(ctx, &controllerTfModel)
		diags = append(diags, controllerDiag...)
		if diags.HasError() {
			return nil, diags
		}
		am.Controller = *controllerTmp
	}

	return &am, diags
}
